#include <z64ovl/oot/debug.h>
#include <z64ovl/oot/helpers.h>
#include <z64ovl/oot/sfx.h>

#define OBJ_ID 1

typedef struct {
	z64_actor_t actor;
	/* uint8_t[16] debug_ex;*/
	uint8_t unknown[134];
} entity_t; /* 01CC */


/*** function prototypes ***/
void data_80A9EFE8(entity_t* en, z64_global_t* gl); /* 1 internal, 8 external, 183 lines */
void data_80A9F2A8(void); /* 1 internal, 3 external, 28 lines */
void data_80A9F408(entity_t* en, z64_global_t* gl); /* 2 internal, 7 external, 355 lines */
void data_80A9F9B4(void); /* 1 internal, 7 external, 96 lines */
void data_80A9FB1C(void); /* 1 internal, 1 external, 121 lines */
void data_80A9FCE8(entity_t* en, z64_global_t* gl); /* 0 internal, 9 external, 472 lines */
void func_80A9EFE0(entity_t* en, z64_actorfunc_t* state); /* 0 internal, 0 external, 2 lines */
void func_80A9F314(void); /* 0 internal, 1 external, 15 lines */
void func_80A9F350(entity_t* en, z64_global_t* gl); /* 0 internal, 2 external, 49 lines */
void func_80A9F938(void); /* 0 internal, 0 external, 35 lines */


/*** variables ***/
const uint32_t data_80AA0420[] =
{
	0x0A090000,
	0x10010000,
	0x02000000,
	0x00000001,
	0x00000000,
	0xFFCFFFFF,
	0x00000000,
	0x19010100,
	0x00C800C8,
	0x00000000,
	0x00000000
};
const uint32_t data_80AA044C[] =
{
	0x01000000,
	0x00400000,
	0x00800000
};
const uint32_t data_80AA0458[] =
{
	0x08000000,
	0x02000000,
	0x04000000
};
const uint32_t data_80AA0464[] =
{
	0x182E182E,
	0x182F182E
};
const uint32_t data_80AA046C[] =
{
	0x3DCCCCCD,
	0x3E19999A,
	0x3E4CCCCD,
	0x3E800000,
	0x3E99999A,
	0x3E800000,
	0x3E4CCCCD,
	0x3E19999A,
	0x00000000,
};
const uint32_t data_80AA0490[] =
{
	0x2E2E2F7A,
	0x5F656E5F,
	0x6D5F7468,
	0x756E6465,
	0x722E6300
};
const uint32_t data_80AA04A4[] =
{
	0x2E2E2F7A,
	0x5F656E5F,
	0x6D5F7468,
	0x756E6465,
	0x722E6300
};
const uint32_t data_80AA04B8[] =
{
	0x2E2E2F7A,
	0x5F656E5F,
	0x6D5F7468,
	0x756E6465,
	0x722E6300
};
const uint32_t data_80AA04CC[] =
{
	0x2E2E2F7A,
	0x5F656E5F,
	0x6D5F7468,
	0x756E6465,
	0x722E6300
};
const uint32_t data_80AA04E0[] =
{
	0x3DCCCCCD
};
const uint32_t data_80AA04E4[] =
{
	0x3DCCCCCD
};
const uint32_t data_80AA04E8[] =
{
	0x3E19999A
};
const uint32_t data_80AA04EC[] =
{
	0x3DCCCCCD
};
const uint32_t data_80AA04F0[] =
{
	0x3F599999
};
const uint32_t data_80AA04F4[] =
{
	0x3E19999A
};
const uint32_t data_80AA04F8[] =
{
	0x3E19999A
};
const uint32_t data_80AA04FC[] =
{
	0x3DCCCCCD
};
const uint32_t data_80AA0500[] =
{
	0x3F599999
};
const uint32_t data_80AA0504[] =
{
	0x3DCCCCCD
};
const uint32_t data_80AA0508[] =
{
	0x3DCCCCCD
};
const uint32_t data_80AA050C[] =
{
	0x3F199999
};
const uint32_t data_80AA0510[] =
{
	0x3FD55554
};
const uint32_t data_80AA0514[] =
{
	0x3CA3D70A
};
const uint32_t data_80AA0518[] =
{
	0xBF333333
};
const uint32_t data_80AA051C[] =
{
	0xBF199999
};
const uint32_t data_80AA0520[] =
{
	0xBF99999A
};
const uint32_t data_80AA0524[] =
{
	0xBFE66665
};
const uint32_t data_80AA0528[] =
{
	0xBFB33333
};
const uint32_t data_80AA052C[] =
{
	0x3F599999
};


/*** functions ***/
void func_80A9EFE0(entity_t* en, z64_actorfunc_t* state) /* 0 internal, 0 external, 2 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_80A9EFE0: \n"
	);
	asm(
		"jr              $ra                                    \n"
		"sw              $a1,448($a0)                           \n"
	);
}
void func_80A9F938(void) /* 0 internal, 0 external, 35 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_80A9F938: \n"
	);
	asm(
		"sw              $a1,4($sp)                             \n"
		"lhu             $t6,452($a0)                           \n"
		"slti            $at,$t6,2                              \n"
		"beql            $at,$zero,.L000034                     \n"
		"lwc1            $f0,432($a0)                           \n"
		"lbu             $v0,456($a0)                           \n"
		"slti            $at,$v0,40                             \n"
		"beq             $at,$zero,.L000035                     \n"
		"addiu           $t7,$v0,-40                            \n"
		"beq             $zero,$zero,.L000036                   \n"
		"sb              $zero,456($a0)                         \n"
		".L000035:                                              \n"
		"sb              $t7,456($a0)                           \n"
		".L000036:                                              \n"
		"lwc1            $f0,432($a0)                           \n"
		".L000034:                                              \n"
		"lwc1            $f2,444($a0)                           \n"
		"lwc1            $f12,428($a0)                          \n"
		"add.s           $f6,$f0,$f0                            \n"
		"lwc1            $f4,436($a0)                           \n"
		"lui             $at,%hi(data_80AA0508)                 \n"
		"c.lt.s          $f2,$f12                               \n"
		"add.s           $f8,$f4,$f6                            \n"
		"bc1f            .L000037                               \n"
		"swc1            $f8,436($a0)                           \n"
		"sub.s           $f10,$f12,$f2                          \n"
		"lwc1            $f16,%lo(data_80AA0508)($at)           \n"
		"mul.s           $f18,$f10,$f16                         \n"
		"add.s           $f4,$f2,$f18                           \n"
		"jr              $ra                                    \n"
		"swc1            $f4,444($a0)                           \n"
		".L000037:                                              \n"
		"swc1            $f12,444($a0)                          \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void data_80A9FCE8(entity_t* en, z64_global_t* gl) /* 0 internal, 9 external, 472 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_80A9FCE8: \n"
	);
	asm(
		"addiu           $sp,$sp,-176                           \n"
		"sw              $ra,60($sp)                            \n"
		"sw              $s0,56($sp)                            \n"
		"sw              $a0,176($sp)                           \n"
		"sw              $a1,180($sp)                           \n"
		"lw              $t7,7236($a1)                          \n"
		"lui             $a2,%hi(data_80AA0490)                 \n"
		"addiu           $a2,$a2,%lo(data_80AA0490)             \n"
		"sw              $t7,164($sp)                           \n"
		"lw              $a1,0($a1)                             \n"
		"addiu           $a0,$sp,136                            \n"
		"addiu           $a3,$zero,844                          \n"
		"jal             external_func_800C6AC4                 \n"
		"or              $s0,$a1,$zero                          \n"
		"lw              $t8,180($sp)                           \n"
		"jal             external_func_80093D84                 \n"
		"lw              $a0,0($t8)                             \n"
		"lui             $at,%hi(data_80AA0514)                 \n"
		"lwc1            $f12,%lo(data_80AA0514)($at)           \n"
		"addiu           $a3,$zero,1                            \n"
		"mfc1            $a2,$f12                               \n"
		"jal             external_func_800D0A8C                 \n"
		"mov.s           $f14,$f12                              \n"
		"lw              $v0,720($s0)                           \n"
		"lui             $t4,0xDA38                             \n"
		"ori             $t4,$t4,0x3                            \n"
		"addiu           $t9,$v0,8                              \n"
		"sw              $t9,720($s0)                           \n"
		"sw              $t4,0($v0)                             \n"
		"lw              $t5,180($sp)                           \n"
		"lui             $a1,%hi(data_80AA04A4)                 \n"
		"addiu           $a1,$a1,%lo(data_80AA04A4)             \n"
		"lw              $a0,0($t5)                             \n"
		"addiu           $a2,$zero,853                          \n"
		"jal             external_func_800D1A88                 \n"
		"sw              $v0,132($sp)                           \n"
		"lw              $v1,132($sp)                           \n"
		"lui             $t6,0xDB06                             \n"
		"addiu           $at,$zero,1                            \n"
		"sw              $v0,4($v1)                             \n"
		"lw              $t1,176($sp)                           \n"
		"ori             $t6,$t6,0x20                           \n"
		"addiu           $t0,$zero,255                          \n"
		"lbu             $v0,454($t1)                           \n"
		"or              $a1,$zero,$zero                        \n"
		"or              $a3,$zero,$zero                        \n"
		"beq             $v0,$zero,.L000050                     \n"
		"addiu           $t9,$zero,1                            \n"
		"bne             $v0,$at,.L000051                       \n"
		"nop                                                    \n"
		".L000050:                                              \n"
		"lw              $v0,720($s0)                           \n"
		"lui             $at,0x41F0                             \n"
		"mtc1            $at,$f4                                \n"
		"addiu           $t7,$v0,8                              \n"
		"sw              $t7,720($s0)                           \n"
		"sw              $t6,0($v0)                             \n"
		"lwc1            $f0,436($t1)                           \n"
		"lui             $at,0x41A0                             \n"
		"mtc1            $at,$f10                               \n"
		"mul.s           $f6,$f0,$f4                            \n"
		"lw              $t8,180($sp)                           \n"
		"addiu           $t6,$zero,64                           \n"
		"mul.s           $f16,$f0,$f10                          \n"
		"lw              $a0,0($t8)                             \n"
		"sw              $t6,16($sp)                            \n"
		"addiu           $t8,$zero,32                           \n"
		"sw              $t8,20($sp)                            \n"
		"sw              $t9,24($sp)                            \n"
		"trunc.w.s       $f8,$f6                                \n"
		"addiu           $t9,$zero,8                            \n"
		"addiu           $t4,$zero,8                            \n"
		"trunc.w.s       $f18,$f16                              \n"
		"mfc1            $t5,$f8                                \n"
		"sw              $t4,40($sp)                            \n"
		"sw              $t9,36($sp)                            \n"
		"andi            $t7,$t5,0xff                           \n"
		"subu            $a2,$t0,$t7                            \n"
		"mfc1            $t7,$f18                               \n"
		"sw              $zero,32($sp)                          \n"
		"sw              $v0,128($sp)                           \n"
		"andi            $t6,$t7,0xff                           \n"
		"subu            $t8,$t0,$t6                            \n"
		"jal             external_func_80094F40                 \n"
		"sw              $t8,28($sp)                            \n"
		"lw              $v1,128($sp)                           \n"
		"sw              $v0,4($v1)                             \n"
		"lw              $t1,176($sp)                           \n"
		"lbu             $v0,454($t1)                           \n"
		".L000051:                                              \n"
		"beq             $v0,$zero,.L000052                     \n"
		"lui             $t6,0xFA00                             \n"
		"addiu           $at,$zero,1                            \n"
		"beq             $v0,$at,.L000053                       \n"
		"lui             $t8,0xFA00                             \n"
		"beq             $zero,$zero,.L000054                   \n"
		"lw              $a0,164($sp)                           \n"
		".L000052:                                              \n"
		"lw              $v1,720($s0)                           \n"
		"ori             $t6,$t6,0x80                           \n"
		"lui             $at,0x437F                             \n"
		"addiu           $t7,$v1,8                              \n"
		"sw              $t7,720($s0)                           \n"
		"sw              $t6,0($v1)                             \n"
		"lwc1            $f4,432($t1)                           \n"
		"mtc1            $at,$f6                                \n"
		"addiu           $t9,$zero,1                            \n"
		"lui             $at,0x4F00                             \n"
		"mul.s           $f8,$f4,$f6                            \n"
		"cfc1            $t8,$f31                               \n"
		"ctc1            $t9,$f31                               \n"
		"nop                                                    \n"
		"cvt.w.s         $f10,$f8                               \n"
		"cfc1            $t9,$f31                               \n"
		"nop                                                    \n"
		"andi            $t9,$t9,0x78                           \n"
		"beql            $t9,$zero,.L000055                     \n"
		"mfc1            $t9,$f10                               \n"
		"mtc1            $at,$f10                               \n"
		"addiu           $t9,$zero,1                            \n"
		"sub.s           $f10,$f8,$f10                          \n"
		"ctc1            $t9,$f31                               \n"
		"nop                                                    \n"
		"cvt.w.s         $f10,$f10                              \n"
		"cfc1            $t9,$f31                               \n"
		"nop                                                    \n"
		"andi            $t9,$t9,0x78                           \n"
		"bne             $t9,$zero,.L000056                     \n"
		"nop                                                    \n"
		"mfc1            $t9,$f10                               \n"
		"lui             $at,0x8000                             \n"
		"beq             $zero,$zero,.L000057                   \n"
		"or              $t9,$t9,$at                            \n"
		".L000056:                                              \n"
		"beq             $zero,$zero,.L000057                   \n"
		"addiu           $t9,$zero,-1                           \n"
		"mfc1            $t9,$f10                               \n"
		".L000055:                                              \n"
		"nop                                                    \n"
		"bltz            $t9,.L000056                           \n"
		"nop                                                    \n"
		".L000057:                                              \n"
		"or              $t4,$t9,$zero                          \n"
		"andi            $t5,$t4,0xff                           \n"
		"addiu           $at,$zero,-22016                       \n"
		"or              $t7,$t5,$at                            \n"
		"sw              $t7,4($v1)                             \n"
		"lw              $v0,720($s0)                           \n"
		"ctc1            $t8,$f31                               \n"
		"lui             $t9,0x0401                             \n"
		"addiu           $t6,$v0,8                              \n"
		"sw              $t6,720($s0)                           \n"
		"addiu           $t9,$t9,10992                          \n"
		"lui             $t8,0xDE00                             \n"
		"sw              $t8,0($v0)                             \n"
		"sw              $t9,4($v0)                             \n"
		"lw              $v0,720($s0)                           \n"
		"lui             $t7,0x0401                             \n"
		"addiu           $t7,$t7,11280                          \n"
		"addiu           $t4,$v0,8                              \n"
		"sw              $t4,720($s0)                           \n"
		"lui             $t5,0xDE00                             \n"
		"sw              $t5,0($v0)                             \n"
		"beq             $zero,$zero,.L000058                   \n"
		"sw              $t7,4($v0)                             \n"
		".L000053:                                              \n"
		"lw              $v1,720($s0)                           \n"
		"ori             $t8,$t8,0x80                           \n"
		"lui             $at,0x437F                             \n"
		"addiu           $t6,$v1,8                              \n"
		"sw              $t6,720($s0)                           \n"
		"sw              $t8,0($v1)                             \n"
		"lwc1            $f16,432($t1)                          \n"
		"mtc1            $at,$f18                               \n"
		"addiu           $t4,$zero,1                            \n"
		"lui             $at,0x4F00                             \n"
		"mul.s           $f4,$f16,$f18                          \n"
		"cfc1            $t9,$f31                               \n"
		"ctc1            $t4,$f31                               \n"
		"nop                                                    \n"
		"cvt.w.s         $f6,$f4                                \n"
		"cfc1            $t4,$f31                               \n"
		"nop                                                    \n"
		"andi            $t4,$t4,0x78                           \n"
		"beql            $t4,$zero,.L000059                     \n"
		"mfc1            $t4,$f6                                \n"
		"mtc1            $at,$f6                                \n"
		"addiu           $t4,$zero,1                            \n"
		"sub.s           $f6,$f4,$f6                            \n"
		"ctc1            $t4,$f31                               \n"
		"nop                                                    \n"
		"cvt.w.s         $f6,$f6                                \n"
		"cfc1            $t4,$f31                               \n"
		"nop                                                    \n"
		"andi            $t4,$t4,0x78                           \n"
		"bne             $t4,$zero,.L000060                     \n"
		"nop                                                    \n"
		"mfc1            $t4,$f6                                \n"
		"lui             $at,0x8000                             \n"
		"beq             $zero,$zero,.L000061                   \n"
		"or              $t4,$t4,$at                            \n"
		".L000060:                                              \n"
		"beq             $zero,$zero,.L000061                   \n"
		"addiu           $t4,$zero,-1                           \n"
		"mfc1            $t4,$f6                                \n"
		".L000059:                                              \n"
		"nop                                                    \n"
		"bltz            $t4,.L000060                           \n"
		"nop                                                    \n"
		".L000061:                                              \n"
		"or              $t5,$t4,$zero                          \n"
		"lui             $at,0xAAFF                             \n"
		"ori             $at,$at,0xff00                         \n"
		"andi            $t7,$t5,0xff                           \n"
		"or              $t6,$t7,$at                            \n"
		"sw              $t6,4($v1)                             \n"
		"lw              $v0,720($s0)                           \n"
		"ctc1            $t9,$f31                               \n"
		"lui             $t4,0x0401                             \n"
		"addiu           $t8,$v0,8                              \n"
		"sw              $t8,720($s0)                           \n"
		"addiu           $t4,$t4,9584                           \n"
		"lui             $t9,0xDE00                             \n"
		"sw              $t9,0($v0)                             \n"
		"sw              $t4,4($v0)                             \n"
		"lw              $v0,720($s0)                           \n"
		"lui             $t6,0x0401                             \n"
		"addiu           $t6,$t6,9872                           \n"
		"addiu           $t5,$v0,8                              \n"
		"sw              $t5,720($s0)                           \n"
		"lui             $t7,0xDE00                             \n"
		"sw              $t7,0($v0)                             \n"
		"sw              $t6,4($v0)                             \n"
		".L000058:                                              \n"
		"lw              $a0,164($sp)                           \n"
		".L000054:                                              \n"
		"or              $a1,$zero,$zero                        \n"
		"jal             external_func_800D0930                 \n"
		"addiu           $a0,$a0,2528                           \n"
		"lw              $a0,176($sp)                           \n"
		"lui             $at,0x4396                             \n"
		"lui             $a2,0xC2C8                             \n"
		"lbu             $v0,455($a0)                           \n"
		"beql            $v0,$zero,.L000062                     \n"
		"mtc1            $zero,$f12                             \n"
		"addiu           $at,$zero,1                            \n"
		"beq             $v0,$at,.L000063                       \n"
		"addiu           $at,$zero,2                            \n"
		"beq             $v0,$at,.L000064                       \n"
		"addiu           $a2,$zero,0                            \n"
		"beq             $zero,$zero,.L000065                   \n"
		"nop                                                    \n"
		".L000063:                                              \n"
		"mtc1            $zero,$f12                             \n"
		"lui             $at,0x435C                             \n"
		"mtc1            $at,$f14                               \n"
		"mfc1            $a2,$f12                               \n"
		"jal             external_func_800D0984                 \n"
		"addiu           $a3,$zero,1                            \n"
		"lui             $at,%hi(data_80AA0518)                 \n"
		"lwc1            $f12,%lo(data_80AA0518)($at)           \n"
		"lui             $at,%hi(data_80AA051C)                 \n"
		"lui             $a2,0xBECC                             \n"
		"ori             $a2,$a2,0xcccd                         \n"
		"lwc1            $f14,%lo(data_80AA051C)($at)           \n"
		"jal             external_func_800D0A8C                 \n"
		"addiu           $a3,$zero,1                            \n"
		"lui             $at,0x4680                             \n"
		"mtc1            $at,$f12                               \n"
		"jal             external_func_800D0B70                 \n"
		"addiu           $a1,$zero,1                            \n"
		"beq             $zero,$zero,.L000065                   \n"
		"lw              $a0,176($sp)                           \n"
		"mtc1            $zero,$f12                             \n"
		".L000062:                                              \n"
		"mtc1            $at,$f14                               \n"
		"jal             external_func_800D0984                 \n"
		"addiu           $a3,$zero,1                            \n"
		"lui             $at,%hi(data_80AA0520)                 \n"
		"lwc1            $f12,%lo(data_80AA0520)($at)           \n"
		"lui             $at,0xBF80                             \n"
		"mtc1            $at,$f14                               \n"
		"lui             $a2,0xBF33                             \n"
		"ori             $a2,$a2,0x3333                         \n"
		"jal             external_func_800D0A8C                 \n"
		"addiu           $a3,$zero,1                            \n"
		"lui             $at,0x4680                             \n"
		"mtc1            $at,$f12                               \n"
		"jal             external_func_800D0B70                 \n"
		"addiu           $a1,$zero,1                            \n"
		"beq             $zero,$zero,.L000065                   \n"
		"lw              $a0,176($sp)                           \n"
		".L000064:                                              \n"
		"lui             $at,0x4348                             \n"
		"mtc1            $at,$f12                               \n"
		"lui             $at,0x43AF                             \n"
		"mtc1            $at,$f14                               \n"
		"jal             external_func_800D0984                 \n"
		"addiu           $a3,$zero,1                            \n"
		"lui             $at,%hi(data_80AA0524)                 \n"
		"lwc1            $f12,%lo(data_80AA0524)($at)           \n"
		"lui             $at,%hi(data_80AA0528)                 \n"
		"lui             $a2,0xBF33                             \n"
		"ori             $a2,$a2,0x3333                         \n"
		"lwc1            $f14,%lo(data_80AA0528)($at)           \n"
		"jal             external_func_800D0A8C                 \n"
		"addiu           $a3,$zero,1                            \n"
		"lui             $at,0x4680                             \n"
		"mtc1            $at,$f12                               \n"
		"jal             external_func_800D0B70                 \n"
		"addiu           $a1,$zero,1                            \n"
		"lw              $a0,176($sp)                           \n"
		".L000065:                                              \n"
		"lui             $at,%hi(data_80AA052C)                 \n"
		"lwc1            $f10,%lo(data_80AA052C)($at)           \n"
		"lwc1            $f8,440($a0)                           \n"
		"lui             $t5,0xFA00                             \n"
		"lui             $at,0x3F80                             \n"
		"c.le.s          $f10,$f8                               \n"
		"lw              $t2,180($sp)                           \n"
		"ori             $t5,$t5,0x80                           \n"
		"addiu           $t1,$zero,20                           \n"
		"bc1f            .L000066                               \n"
		"addiu           $a3,$zero,1                            \n"
		"lw              $t2,180($sp)                           \n"
		"lui             $at,0x3F80                             \n"
		"mtc1            $at,$f12                               \n"
		"lui             $at,0x0001                             \n"
		"addu            $t2,$t2,$at                            \n"
		"lw              $t8,7652($t2)                          \n"
		"lw              $v0,720($s0)                           \n"
		"lui             $at,%hi(data_80AA046C)                 \n"
		"andi            $t9,$t8,0x7                            \n"
		"sll             $t4,$t9,2                              \n"
		"addu            $at,$at,$t4                            \n"
		"lwc1            $f16,%lo(data_80AA046C)($at)           \n"
		"lui             $t7,0xFA00                             \n"
		"addiu           $t5,$v0,8                              \n"
		"sw              $t5,720($s0)                           \n"
		"ori             $t7,$t7,0x80                           \n"
		"lui             $at,0x40C0                             \n"
		"sw              $t7,0($v0)                             \n"
		"mtc1            $at,$f18                               \n"
		"lbu             $t8,456($a0)                           \n"
		"addiu           $at,$zero,-22016                       \n"
		"mul.s           $f4,$f16,$f18                          \n"
		"or              $t9,$t8,$at                            \n"
		"sw              $t9,4($v0)                             \n"
		"lw              $v0,720($s0)                           \n"
		"lui             $t7,0xFF64                             \n"
		"ori             $t7,$t7,0x80                           \n"
		"addiu           $t4,$v0,8                              \n"
		"sw              $t4,720($s0)                           \n"
		"lui             $t5,0xFB00                             \n"
		"addiu           $t1,$zero,40                           \n"
		"add.s           $f14,$f4,$f12                          \n"
		"sw              $t5,0($v0)                             \n"
		"beq             $zero,$zero,.L000067                   \n"
		"sw              $t7,4($v0)                             \n"
		".L000066:                                              \n"
		"mtc1            $at,$f12                               \n"
		"lui             $at,0x0001                             \n"
		"addu            $t2,$t2,$at                            \n"
		"lw              $t6,7652($t2)                          \n"
		"lw              $v0,720($s0)                           \n"
		"lui             $at,%hi(data_80AA046C)                 \n"
		"andi            $t8,$t6,0x7                            \n"
		"sll             $t9,$t8,2                              \n"
		"addu            $at,$at,$t9                            \n"
		"lwc1            $f0,%lo(data_80AA046C)($at)            \n"
		"addiu           $t4,$v0,8                              \n"
		"sw              $t4,720($s0)                           \n"
		"sw              $t5,0($v0)                             \n"
		"lbu             $t6,456($a0)                           \n"
		"lui             $at,0xAAFF                             \n"
		"ori             $at,$at,0xff00                         \n"
		"or              $t8,$t6,$at                            \n"
		"sw              $t8,4($v0)                             \n"
		"lw              $v0,720($s0)                           \n"
		"add.s           $f6,$f0,$f0                            \n"
		"lui             $t5,0x0064                             \n"
		"addiu           $t9,$v0,8                              \n"
		"sw              $t9,720($s0)                           \n"
		"ori             $t5,$t5,0xff80                         \n"
		"lui             $t4,0xFB00                             \n"
		"add.s           $f14,$f6,$f12                          \n"
		"sw              $t4,0($v0)                             \n"
		"sw              $t5,4($v0)                             \n"
		".L000067:                                              \n"
		"mfc1            $a2,$f14                               \n"
		"sw              $t1,156($sp)                           \n"
		"jal             external_func_800D0A8C                 \n"
		"sw              $t2,68($sp)                            \n"
		"lw              $v0,720($s0)                           \n"
		"lw              $t1,156($sp)                           \n"
		"lw              $t2,68($sp)                            \n"
		"lui             $t6,0xDA38                             \n"
		"addiu           $t7,$v0,8                              \n"
		"sw              $t7,720($s0)                           \n"
		"ori             $t6,$t6,0x3                            \n"
		"sw              $t6,0($v0)                             \n"
		"lw              $t8,180($sp)                           \n"
		"lui             $a1,%hi(data_80AA04B8)                 \n"
		"addiu           $a1,$a1,%lo(data_80AA04B8)             \n"
		"lw              $a0,0($t8)                             \n"
		"addiu           $a2,$zero,960                          \n"
		"sw              $v0,84($sp)                            \n"
		"sw              $t1,156($sp)                           \n"
		"jal             external_func_800D1A88                 \n"
		"sw              $t2,68($sp)                            \n"
		"lw              $v1,84($sp)                            \n"
		"lw              $t1,156($sp)                           \n"
		"lw              $t2,68($sp)                            \n"
		"sw              $v0,4($v1)                             \n"
		"lw              $v0,720($s0)                           \n"
		"lw              $t3,180($sp)                           \n"
		"lui             $t4,0xDB06                             \n"
		"addiu           $t9,$v0,8                              \n"
		"sw              $t9,720($s0)                           \n"
		"ori             $t4,$t4,0x24                           \n"
		"sw              $t4,0($v0)                             \n"
		"lw              $v1,7652($t2)                          \n"
		"lw              $a0,0($t3)                             \n"
		"addiu           $t5,$zero,32                           \n"
		"multu           $v1,$t1                                \n"
		"sll             $t8,$v1,2                              \n"
		"addiu           $t7,$zero,32                           \n"
		"addiu           $t6,$zero,1                            \n"
		"addu            $t8,$t8,$v1                            \n"
		"sll             $t8,$t8,2                              \n"
		"sw              $t6,24($sp)                            \n"
		"sw              $t7,20($sp)                            \n"
		"sw              $t5,16($sp)                            \n"
		"sll             $a2,$v1,2                              \n"
		"mflo            $t4                                    \n"
		"andi            $t5,$t4,0xff                           \n"
		"addiu           $t7,$zero,8                            \n"
		"addiu           $t6,$zero,8                            \n"
		"andi            $t9,$t8,0xff                           \n"
		"addu            $a2,$a2,$v1                            \n"
		"andi            $a2,$a2,0xff                           \n"
		"sw              $t9,28($sp)                            \n"
		"sw              $t6,40($sp)                            \n"
		"sw              $t7,36($sp)                            \n"
		"sw              $t5,32($sp)                            \n"
		"or              $a1,$zero,$zero                        \n"
		"or              $a3,$zero,$zero                        \n"
		"jal             external_func_80094F40                 \n"
		"sw              $v0,80($sp)                            \n"
		"lw              $t0,80($sp)                            \n"
		"lui             $t4,0x0401                             \n"
		"addiu           $t4,$t4,13840                          \n"
		"sw              $v0,4($t0)                             \n"
		"lw              $v0,720($s0)                           \n"
		"lui             $t9,0xDE00                             \n"
		"lui             $a2,%hi(data_80AA04CC)                 \n"
		"addiu           $t8,$v0,8                              \n"
		"sw              $t8,720($s0)                           \n"
		"sw              $t4,4($v0)                             \n"
		"sw              $t9,0($v0)                             \n"
		"lw              $t5,180($sp)                           \n"
		"addiu           $a2,$a2,%lo(data_80AA04CC)             \n"
		"addiu           $a0,$sp,136                            \n"
		"addiu           $a3,$zero,1031                         \n"
		"jal             external_func_800C6B54                 \n"
		"lw              $a1,0($t5)                             \n"
		"lw              $ra,60($sp)                            \n"
		"lw              $s0,56($sp)                            \n"
		"addiu           $sp,$sp,176                            \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
		"nop                                                    \n"
	);
}
void func_80A9F314(void) /* 0 internal, 1 external, 15 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_80A9F314: \n"
	);
	asm(
		"mtc1            $a1,$f12                               \n"
		"mtc1            $zero,$f4                              \n"
		"addiu           $sp,$sp,-32                            \n"
		"sw              $ra,28($sp)                            \n"
		"lui             $a2,0x4454                             \n"
		"lui             $a3,0x3E4C                             \n"
		"mfc1            $a1,$f12                               \n"
		"ori             $a3,$a3,0xcccd                         \n"
		"ori             $a2,$a2,0x8000                         \n"
		"jal             external_func_800773A8                 \n"
		"swc1            $f4,16($sp)                            \n"
		"lw              $ra,28($sp)                            \n"
		"addiu           $sp,$sp,32                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void func_80A9F350(entity_t* en, z64_global_t* gl) /* 0 internal, 2 external, 49 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_80A9F350: \n"
	);
	asm(
		"addiu           $sp,$sp,-40                            \n"
		"sw              $ra,28($sp)                            \n"
		"sw              $a0,40($sp)                            \n"
		"lw              $v0,7236($a1)                          \n"
		"lw              $t6,1664($v0)                          \n"
		"sll             $t7,$t6,14                             \n"
		"bgezl           $t7,.L000008                           \n"
		"lw              $t1,1660($v0)                          \n"
		"lb              $t8,2114($v0)                          \n"
		"lui             $a3,0x8013                             \n"
		"addiu           $a3,$a3,13280                          \n"
		"slti            $at,$t8,24                             \n"
		"bne             $at,$zero,.L000009                     \n"
		"addiu           $a0,$zero,6179                         \n"
		"lui             $t9,0x8013                             \n"
		"addiu           $t9,$t9,13288                          \n"
		"addiu           $a1,$v0,228                            \n"
		"sw              $a1,32($sp)                            \n"
		"sw              $t9,20($sp)                            \n"
		"addiu           $a2,$zero,4                            \n"
		"jal             external_func_800F738C                 \n"
		"sw              $a3,16($sp)                            \n"
		"lui             $a3,0x8013                             \n"
		"lui             $t0,0x8013                             \n"
		"addiu           $a3,$a3,13280                          \n"
		"addiu           $t0,$t0,13288                          \n"
		"lw              $a1,32($sp)                            \n"
		"sw              $t0,20($sp)                            \n"
		"sw              $a3,16($sp)                            \n"
		"addiu           $a0,$zero,6168                         \n"
		"jal             external_func_800F738C                 \n"
		"addiu           $a2,$zero,4                            \n"
		".L000009:                                              \n"
		"jal             external_func_8002D570                 \n"
		"lw              $a0,40($sp)                            \n"
		"beq             $zero,$zero,.L000010                   \n"
		"lw              $ra,28($sp)                            \n"
		"lw              $t1,1660($v0)                          \n"
		".L000008:                                              \n"
		"andi            $t2,$t1,0x1000                         \n"
		"bnel            $t2,$zero,.L000010                     \n"
		"lw              $ra,28($sp)                            \n"
		"jal             external_func_8002D570                 \n"
		"lw              $a0,40($sp)                            \n"
		"lw              $ra,28($sp)                            \n"
		".L000010:                                              \n"
		"addiu           $sp,$sp,40                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void data_80A9FB1C(void) /* 1 internal, 1 external, 121 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_80A9FB1C: \n"
	);
	asm(
		"addiu           $sp,$sp,-48                            \n"
		"sw              $s0,40($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,44($sp)                            \n"
		"sw              $a1,52($sp)                            \n"
		"lw              $t9,448($s0)                           \n"
		"jalr            $t9                                    \n"
		"nop                                                    \n"
		"lw              $a0,52($sp)                            \n"
		"jal             func_80A9F314                          \n"
		"lw              $a1,444($s0)                           \n"
		"lwc1            $f4,36($s0)                            \n"
		"lui             $at,0x437F                             \n"
		"lwc1            $f0,428($s0)                           \n"
		"trunc.w.s       $f6,$f4                                \n"
		"mtc1            $at,$f4                                \n"
		"lwc1            $f8,40($s0)                            \n"
		"lwc1            $f16,44($s0)                           \n"
		"mfc1            $a1,$f6                                \n"
		"mul.s           $f6,$f0,$f4                            \n"
		"trunc.w.s       $f10,$f8                               \n"
		"addiu           $v0,$zero,1                            \n"
		"sll             $a1,$a1,16                             \n"
		"sra             $a1,$a1,16                             \n"
		"mfc1            $a2,$f10                               \n"
		"trunc.w.s       $f18,$f16                              \n"
		"lui             $at,0x4F00                             \n"
		"sll             $a2,$a2,16                             \n"
		"sra             $a2,$a2,16                             \n"
		"cfc1            $t0,$f31                               \n"
		"ctc1            $v0,$f31                               \n"
		"mfc1            $a3,$f18                               \n"
		"addiu           $a0,$s0,412                            \n"
		"cvt.w.s         $f8,$f6                                \n"
		"sll             $a3,$a3,16                             \n"
		"sra             $a3,$a3,16                             \n"
		"cfc1            $v0,$f31                               \n"
		"nop                                                    \n"
		"andi            $v0,$v0,0x78                           \n"
		"beql            $v0,$zero,.L000044                     \n"
		"mfc1            $v0,$f8                                \n"
		"mtc1            $at,$f8                                \n"
		"addiu           $v0,$zero,1                            \n"
		"sub.s           $f8,$f6,$f8                            \n"
		"ctc1            $v0,$f31                               \n"
		"nop                                                    \n"
		"cvt.w.s         $f8,$f8                                \n"
		"cfc1            $v0,$f31                               \n"
		"nop                                                    \n"
		"andi            $v0,$v0,0x78                           \n"
		"bne             $v0,$zero,.L000045                     \n"
		"nop                                                    \n"
		"mfc1            $v0,$f8                                \n"
		"lui             $at,0x8000                             \n"
		"beq             $zero,$zero,.L000046                   \n"
		"or              $v0,$v0,$at                            \n"
		".L000045:                                              \n"
		"beq             $zero,$zero,.L000046                   \n"
		"addiu           $v0,$zero,-1                           \n"
		"mfc1            $v0,$f8                                \n"
		".L000044:                                              \n"
		"nop                                                    \n"
		"bltz            $v0,.L000045                           \n"
		"nop                                                    \n"
		".L000046:                                              \n"
		"lui             $at,0x42C8                             \n"
		"ctc1            $t0,$f31                               \n"
		"mtc1            $at,$f10                               \n"
		"addiu           $t2,$zero,1                            \n"
		"andi            $v0,$v0,0xff                           \n"
		"mul.s           $f16,$f0,$f10                          \n"
		"sw              $v0,16($sp)                            \n"
		"sw              $v0,20($sp)                            \n"
		"lui             $at,0x4F00                             \n"
		"cfc1            $t1,$f31                               \n"
		"ctc1            $t2,$f31                               \n"
		"nop                                                    \n"
		"cvt.w.s         $f18,$f16                              \n"
		"cfc1            $t2,$f31                               \n"
		"nop                                                    \n"
		"andi            $t2,$t2,0x78                           \n"
		"beql            $t2,$zero,.L000047                     \n"
		"mfc1            $t2,$f18                               \n"
		"mtc1            $at,$f18                               \n"
		"addiu           $t2,$zero,1                            \n"
		"sub.s           $f18,$f16,$f18                         \n"
		"ctc1            $t2,$f31                               \n"
		"nop                                                    \n"
		"cvt.w.s         $f18,$f18                              \n"
		"cfc1            $t2,$f31                               \n"
		"nop                                                    \n"
		"andi            $t2,$t2,0x78                           \n"
		"bne             $t2,$zero,.L000048                     \n"
		"nop                                                    \n"
		"mfc1            $t2,$f18                               \n"
		"lui             $at,0x8000                             \n"
		"beq             $zero,$zero,.L000049                   \n"
		"or              $t2,$t2,$at                            \n"
		".L000048:                                              \n"
		"beq             $zero,$zero,.L000049                   \n"
		"addiu           $t2,$zero,-1                           \n"
		"mfc1            $t2,$f18                               \n"
		".L000047:                                              \n"
		"nop                                                    \n"
		"bltz            $t2,.L000048                           \n"
		"nop                                                    \n"
		".L000049:                                              \n"
		"lui             $at,0x4448                             \n"
		"mtc1            $at,$f4                                \n"
		"ctc1            $t1,$f31                               \n"
		"sw              $t2,24($sp)                            \n"
		"mul.s           $f6,$f0,$f4                            \n"
		"trunc.w.s       $f8,$f6                                \n"
		"mfc1            $t4,$f8                                \n"
		"jal             external_func_80079D8C                 \n"
		"sw              $t4,28($sp)                            \n"
		"lw              $ra,44($sp)                            \n"
		"lw              $s0,40($sp)                            \n"
		"addiu           $sp,$sp,48                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void data_80A9F2A8(void) /* 1 internal, 3 external, 28 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_80A9F2A8: \n"
	);
	asm(
		"addiu           $sp,$sp,-32                            \n"
		"sw              $ra,28($sp)                            \n"
		"sw              $s0,24($sp)                            \n"
		"sw              $a0,32($sp)                            \n"
		"lbu             $t7,458($a0)                           \n"
		"or              $s0,$a1,$zero                          \n"
		"beql            $t7,$zero,.L000007                     \n"
		"lw              $a1,32($sp)                            \n"
		"jal             external_func_800876C8                 \n"
		"or              $a0,$a1,$zero                          \n"
		"lw              $a1,32($sp)                            \n"
		".L000007:                                              \n"
		"or              $a0,$s0,$zero                          \n"
		"jal             external_func_8005C3AC                 \n"
		"addiu           $a1,$a1,332                            \n"
		"or              $a0,$s0,$zero                          \n"
		"jal             func_80A9F314                          \n"
		"addiu           $a1,$zero,0                            \n"
		"lw              $t8,32($sp)                            \n"
		"or              $a0,$s0,$zero                          \n"
		"addiu           $a1,$s0,1960                           \n"
		"jal             external_func_8007A7C4                 \n"
		"lw              $a2,408($t8)                           \n"
		"lw              $ra,28($sp)                            \n"
		"lw              $s0,24($sp)                            \n"
		"addiu           $sp,$sp,32                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void data_80A9F9B4(void) /* 1 internal, 7 external, 96 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_80A9F9B4: \n"
	);
	asm(
		"addiu           $sp,$sp,-48                            \n"
		"sw              $ra,36($sp)                            \n"
		"sw              $s0,32($sp)                            \n"
		"sw              $a1,52($sp)                            \n"
		"lw              $t7,7236($a1)                          \n"
		"or              $s0,$a0,$zero                          \n"
		"addiu           $a0,$a0,428                            \n"
		"addiu           $a1,$zero,0                            \n"
		"lui             $a2,0x3D80                             \n"
		"jal             external_func_80077A00                 \n"
		"sw              $t7,44($sp)                            \n"
		"beql            $v0,$zero,.L000038                     \n"
		"lbu             $t8,457($s0)                           \n"
		"jal             external_func_8002D570                 \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000039                   \n"
		"lhu             $v0,452($s0)                           \n"
		"lbu             $t8,457($s0)                           \n"
		".L000038:                                              \n"
		"mtc1            $zero,$f6                              \n"
		"lui             $a2,0x3F19                             \n"
		"mtc1            $t8,$f4                                \n"
		"lui             $a3,0x3F4C                             \n"
		"ori             $a3,$a3,0xcccd                         \n"
		"cvt.s.w         $f4,$f4                                \n"
		"ori             $a2,$a2,0x999a                         \n"
		"addiu           $a0,$s0,80                             \n"
		"swc1            $f6,16($sp)                            \n"
		"mfc1            $a1,$f4                                \n"
		"jal             external_func_80078310                 \n"
		"nop                                                    \n"
		"or              $a0,$s0,$zero                          \n"
		"jal             external_func_8002D62C                 \n"
		"lw              $a1,80($s0)                            \n"
		"lui             $at,0x41C8                             \n"
		"mtc1            $at,$f10                               \n"
		"lwc1            $f8,80($s0)                            \n"
		"addiu           $a2,$s0,332                            \n"
		"or              $a1,$a2,$zero                          \n"
		"mul.s           $f16,$f8,$f10                          \n"
		"or              $a0,$s0,$zero                          \n"
		"trunc.w.s       $f18,$f16                              \n"
		"mfc1            $t0,$f18                               \n"
		"nop                                                    \n"
		"sh              $t0,396($s0)                           \n"
		"jal             external_func_800626DC                 \n"
		"sw              $a2,40($sp)                            \n"
		"lw              $a0,52($sp)                            \n"
		"lui             $at,0x0001                             \n"
		"ori             $at,$at,0x1e60                         \n"
		"lw              $a2,40($sp)                            \n"
		"jal             external_func_8005D79C                 \n"
		"addu            $a1,$a0,$at                            \n"
		"lhu             $v0,452($s0)                           \n"
		".L000039:                                              \n"
		"lw              $v1,44($sp)                            \n"
		"lui             $at,%hi(data_80AA050C)                 \n"
		"blez            $v0,.L000040                           \n"
		"or              $a0,$s0,$zero                          \n"
		"lwc1            $f4,2312($v1)                          \n"
		"addiu           $t1,$v0,-1                             \n"
		"swc1            $f4,36($s0)                            \n"
		"lwc1            $f6,2320($v1)                          \n"
		"sh              $t1,452($s0)                           \n"
		"swc1            $f6,44($s0)                            \n"
		".L000040:                                              \n"
		"lwc1            $f0,428($s0)                           \n"
		"lwc1            $f8,%lo(data_80AA050C)($at)            \n"
		"lui             $at,%hi(data_80AA0510)                 \n"
		"c.lt.s          $f8,$f0                                \n"
		"nop                                                    \n"
		"bc1f            .L000041                               \n"
		"nop                                                    \n"
		"lui             $at,0x3F80                             \n"
		"mtc1            $at,$f10                               \n"
		"beq             $zero,$zero,.L000042                   \n"
		"swc1            $f10,432($s0)                          \n"
		".L000041:                                              \n"
		"lwc1            $f16,%lo(data_80AA0510)($at)           \n"
		"mul.s           $f18,$f0,$f16                          \n"
		"swc1            $f18,432($s0)                          \n"
		".L000042:                                              \n"
		"jal             func_80A9F938                          \n"
		"lw              $a1,52($sp)                            \n"
		"jal             external_func_800BFC84                 \n"
		"lw              $a0,52($sp)                            \n"
		"beql            $v0,$zero,.L000043                     \n"
		"lw              $ra,36($sp)                            \n"
		"jal             external_func_8002D570                 \n"
		"or              $a0,$s0,$zero                          \n"
		"lw              $ra,36($sp)                            \n"
		".L000043:                                              \n"
		"lw              $s0,32($sp)                            \n"
		"addiu           $sp,$sp,48                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void data_80A9EFE8(entity_t* en, z64_global_t* gl) /* 1 internal, 8 external, 183 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_80A9EFE8: \n"
	);
	asm(
		"addiu           $sp,$sp,-64                            \n"
		"sw              $s0,36($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,44($sp)                            \n"
		"sw              $s1,40($sp)                            \n"
		"or              $a2,$a1,$zero                          \n"
		"lw              $s1,7236($a1)                          \n"
		"or              $a0,$a1,$zero                          \n"
		"addiu           $a1,$s0,332                            \n"
		"sw              $a1,48($sp)                            \n"
		"jal             external_func_8005C364                 \n"
		"sw              $a2,68($sp)                            \n"
		"lui             $a3,%hi(data_80AA0420)                 \n"
		"lw              $a1,48($sp)                            \n"
		"addiu           $a3,$a3,%lo(data_80AA0420)             \n"
		"lw              $a0,68($sp)                            \n"
		"jal             external_func_8005C4AC                 \n"
		"or              $a2,$s0,$zero                          \n"
		"lwc1            $f4,36($s0)                            \n"
		"lwc1            $f8,40($s0)                            \n"
		"lwc1            $f16,44($s0)                           \n"
		"trunc.w.s       $f6,$f4                                \n"
		"lh              $t7,28($s0)                            \n"
		"addiu           $a0,$s0,412                            \n"
		"trunc.w.s       $f10,$f8                               \n"
		"addiu           $t8,$t7,-1                             \n"
		"mfc1            $a1,$f6                                \n"
		"trunc.w.s       $f18,$f16                              \n"
		"mfc1            $a2,$f10                               \n"
		"sb              $t8,455($s0)                           \n"
		"addiu           $t2,$zero,255                          \n"
		"mfc1            $a3,$f18                               \n"
		"addiu           $t3,$zero,255                          \n"
		"addiu           $t4,$zero,255                          \n"
		"sll             $a1,$a1,16                             \n"
		"sll             $a2,$a2,16                             \n"
		"sll             $a3,$a3,16                             \n"
		"sra             $a3,$a3,16                             \n"
		"sra             $a2,$a2,16                             \n"
		"sra             $a1,$a1,16                             \n"
		"sw              $t4,24($sp)                            \n"
		"sw              $t3,20($sp)                            \n"
		"sw              $t2,16($sp)                            \n"
		"sw              $a0,48($sp)                            \n"
		"jal             external_func_80079D8C                 \n"
		"sw              $zero,28($sp)                          \n"
		"lw              $a0,68($sp)                            \n"
		"lw              $a2,48($sp)                            \n"
		"jal             external_func_8007A764                 \n"
		"addiu           $a1,$a0,1960                           \n"
		"mtc1            $zero,$f0                              \n"
		"addiu           $t5,$zero,40                           \n"
		"addiu           $t6,$zero,-20                          \n"
		"addiu           $t7,$zero,8                            \n"
		"sw              $v0,408($s0)                           \n"
		"sh              $zero,396($s0)                         \n"
		"sh              $t5,398($s0)                           \n"
		"sh              $t6,400($s0)                           \n"
		"sh              $t7,452($s0)                           \n"
		"swc1            $f0,436($s0)                           \n"
		"lw              $t9,2312($s1)                          \n"
		"ori             $at,$zero,0x8000                       \n"
		"addiu           $t2,$zero,-1                           \n"
		"sw              $t9,36($s0)                            \n"
		"lw              $t8,2316($s1)                          \n"
		"lui             $a1,0x3DCC                             \n"
		"ori             $a1,$a1,0xcccd                         \n"
		"sw              $t8,40($s0)                            \n"
		"lw              $t9,2320($s1)                          \n"
		"swc1            $f0,428($s0)                           \n"
		"swc1            $f0,444($s0)                           \n"
		"sw              $t9,44($s0)                            \n"
		"lh              $t0,182($s1)                           \n"
		"sb              $t2,3($s0)                             \n"
		"or              $a0,$s0,$zero                          \n"
		"addu            $t1,$t0,$at                            \n"
		"jal             external_func_8002D62C                 \n"
		"sh              $t1,182($s0)                           \n"
		"sb              $zero,458($s0)                         \n"
		"lw              $t3,1664($s1)                          \n"
		"lui             $v0,0x8016                             \n"
		"or              $a0,$s0,$zero                          \n"
		"sll             $t4,$t3,14                             \n"
		"bgez            $t4,.L000000                           \n"
		"lui             $a1,%hi(data_80A9F408)                 \n"
		"addiu           $v0,$v0,-6560                          \n"
		"lbu             $t5,58($v0)                            \n"
		"beq             $t5,$zero,.L000001                     \n"
		"nop                                                    \n"
		"lh              $t6,5104($v0)                          \n"
		"bne             $t6,$zero,.L000001                     \n"
		"nop                                                    \n"
		"lh              $v0,28($s0)                            \n"
		"lw              $a0,68($sp)                            \n"
		"or              $a2,$zero,$zero                        \n"
		"andi            $v0,$v0,0xff00                         \n"
		"sra             $v0,$v0,8                              \n"
		"beq             $v0,$zero,.L000002                     \n"
		"sll             $a1,$v0,16                             \n"
		"jal             external_func_80087708                 \n"
		"sra             $a1,$a1,16                             \n"
		"bne             $v0,$zero,.L000002                     \n"
		".L000001:                                              \n"
		"lui             $a3,0x8013                             \n"
		"lui             $t7,0x8013                             \n"
		"addiu           $a3,$a3,13280                          \n"
		"addiu           $t7,$t7,13288                          \n"
		"addiu           $a1,$s1,228                            \n"
		"sw              $a1,48($sp)                            \n"
		"sw              $t7,20($sp)                            \n"
		"sw              $a3,16($sp)                            \n"
		"addiu           $a0,$zero,6179                         \n"
		"jal             external_func_800F738C                 \n"
		"addiu           $a2,$zero,4                            \n"
		"lui             $a3,0x8013                             \n"
		"lui             $t8,0x8013                             \n"
		"addiu           $a3,$a3,13280                          \n"
		"addiu           $t8,$t8,13288                          \n"
		"lw              $a1,48($sp)                            \n"
		"sw              $t8,20($sp)                            \n"
		"sw              $a3,16($sp)                            \n"
		"addiu           $a0,$zero,6168                         \n"
		"jal             external_func_800F738C                 \n"
		"addiu           $a2,$zero,4                            \n"
		"jal             external_func_8002D570                 \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000003                   \n"
		"lw              $ra,44($sp)                            \n"
		".L000002:                                              \n"
		"lw              $t9,1664($s1)                          \n"
		"lui             $at,0xFFFD                             \n"
		"ori             $at,$at,0xffff                         \n"
		"and             $t0,$t9,$at                            \n"
		"sw              $t0,1664($s1)                          \n"
		"lbu             $v0,455($s0)                           \n"
		"addiu           $v1,$zero,1                            \n"
		"lui             $t2,%hi(data_80AA044C)                 \n"
		"sll             $t1,$v0,2                              \n"
		"sb              $v1,458($s0)                           \n"
		"addu            $t2,$t2,$t1                            \n"
		"lw              $t2,%lo(data_80AA044C)($t2)            \n"
		"addiu           $at,$zero,1                            \n"
		"sb              $v1,454($s0)                           \n"
		"bne             $v0,$at,.L000004                       \n"
		"sw              $t2,356($s0)                           \n"
		"addiu           $t3,$zero,2                            \n"
		"beq             $zero,$zero,.L000005                   \n"
		"sb              $t3,457($s0)                           \n"
		".L000004:                                              \n"
		"addiu           $t4,$zero,4                            \n"
		"sb              $t4,457($s0)                           \n"
		".L000005:                                              \n"
		"lui             $a1,%hi(data_80A9F9B4)                 \n"
		"addiu           $a1,$a1,%lo(data_80A9F9B4)             \n"
		"jal             func_80A9EFE0                          \n"
		"or              $a0,$s0,$zero                          \n"
		"lui             $a3,0x8013                             \n"
		"addiu           $t5,$zero,8                            \n"
		"lui             $t6,0x8013                             \n"
		"addiu           $a3,$a3,13280                          \n"
		"sh              $t5,452($s0)                           \n"
		"addiu           $t6,$t6,13288                          \n"
		"sw              $t6,20($sp)                            \n"
		"sw              $a3,16($sp)                            \n"
		"addiu           $a0,$zero,6190                         \n"
		"addiu           $a1,$s1,228                            \n"
		"jal             external_func_800F738C                 \n"
		"addiu           $a2,$zero,4                            \n"
		"lui             $at,0x3F80                             \n"
		"mtc1            $at,$f4                                \n"
		"beq             $zero,$zero,.L000006                   \n"
		"swc1            $f4,428($s0)                           \n"
		".L000000:                                              \n"
		"jal             func_80A9EFE0                          \n"
		"addiu           $a1,$a1,%lo(data_80A9F408)             \n"
		".L000006:                                              \n"
		"sw              $zero,284($s0)                         \n"
		"lw              $ra,44($sp)                            \n"
		".L000003:                                              \n"
		"lw              $s0,36($sp)                            \n"
		"lw              $s1,40($sp)                            \n"
		"jr              $ra                                    \n"
		"addiu           $sp,$sp,64                             \n"
	);
}
void data_80A9F408(entity_t* en, z64_global_t* gl) /* 2 internal, 7 external, 355 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_80A9F408: \n"
	);
	asm(
		"addiu           $sp,$sp,-80                            \n"
		"sw              $ra,60($sp)                            \n"
		"sw              $s0,56($sp)                            \n"
		"sw              $a1,84($sp)                            \n"
		"lw              $v1,7236($a1)                          \n"
		"lbu             $t2,458($a0)                           \n"
		"ori             $at,$zero,0x8000                       \n"
		"lwc1            $f4,2136($v1)                          \n"
		"or              $s0,$a0,$zero                          \n"
		"lw              $t0,284($a0)                           \n"
		"swc1            $f4,440($a0)                           \n"
		"lw              $t8,2312($v1)                          \n"
		"sw              $t8,36($a0)                            \n"
		"lw              $t7,2316($v1)                          \n"
		"sw              $t7,40($a0)                            \n"
		"lw              $t8,2320($v1)                          \n"
		"sw              $t8,44($a0)                            \n"
		"lh              $t9,182($v1)                           \n"
		"addu            $t1,$t9,$at                            \n"
		"bne             $t2,$zero,.L000011                     \n"
		"sh              $t1,182($a0)                           \n"
		"lui             $at,%hi(data_80AA04E0)                 \n"
		"lwc1            $f8,%lo(data_80AA04E0)($at)            \n"
		"lwc1            $f6,2136($v1)                          \n"
		"lui             $t3,0x8016                             \n"
		"c.le.s          $f8,$f6                                \n"
		"nop                                                    \n"
		"bc1f            .L000011                               \n"
		"nop                                                    \n"
		"lh              $t3,-1456($t3)                         \n"
		"bnel            $t3,$zero,.L000012                     \n"
		"or              $a0,$s0,$zero                          \n"
		"lh              $v0,28($a0)                            \n"
		"lw              $a0,84($sp)                            \n"
		"addiu           $a2,$zero,4                            \n"
		"andi            $v0,$v0,0xff00                         \n"
		"sra             $v0,$v0,8                              \n"
		"beq             $v0,$zero,.L000013                     \n"
		"sll             $a1,$v0,16                             \n"
		"sra             $a1,$a1,16                             \n"
		"sw              $v1,76($sp)                            \n"
		"jal             external_func_80087708                 \n"
		"sw              $t0,72($sp)                            \n"
		"lw              $v1,76($sp)                            \n"
		"bne             $v0,$zero,.L000013                     \n"
		"lw              $t0,72($sp)                            \n"
		"or              $a0,$s0,$zero                          \n"
		".L000012:                                              \n"
		"jal             func_80A9F350                          \n"
		"lw              $a1,84($sp)                            \n"
		"lui             $a1,%hi(func_80A9F350)                 \n"
		"addiu           $a1,$a1,%lo(func_80A9F350)             \n"
		"jal             func_80A9EFE0                          \n"
		"or              $a0,$s0,$zero                          \n"
		"mtc1            $zero,$f10                             \n"
		"mtc1            $zero,$f16                             \n"
		"sb              $zero,456($s0)                         \n"
		"swc1            $f10,444($s0)                          \n"
		"beq             $zero,$zero,.L000014                   \n"
		"swc1            $f16,428($s0)                          \n"
		".L000013:                                              \n"
		"addiu           $t4,$zero,1                            \n"
		"sb              $t4,458($s0)                           \n"
		".L000011:                                              \n"
		"lui             $at,%hi(data_80AA04E4)                 \n"
		"lwc1            $f18,%lo(data_80AA04E4)($at)           \n"
		"lwc1            $f0,2136($v1)                          \n"
		"lui             $at,0x4316                             \n"
		"c.le.s          $f18,$f0                               \n"
		"nop                                                    \n"
		"bc1fl           .L000015                               \n"
		"lw              $t6,1664($v1)                          \n"
		"mtc1            $at,$f4                                \n"
		"mtc1            $zero,$f12                             \n"
		"addiu           $a2,$zero,2                            \n"
		"mul.s           $f6,$f0,$f4                            \n"
		"sw              $v1,76($sp)                            \n"
		"sw              $t0,72($sp)                            \n"
		"trunc.w.s       $f8,$f6                                \n"
		"mfc1            $a1,$f8                                \n"
		"nop                                                    \n"
		"andi            $a1,$a1,0xff                           \n"
		"jal             external_func_800AA000                 \n"
		"andi            $a3,$a1,0xff                           \n"
		"lw              $v1,76($sp)                            \n"
		"lw              $t0,72($sp)                            \n"
		"lw              $t6,1664($v1)                          \n"
		".L000015:                                              \n"
		"lui             $at,%hi(data_80AA04E8)                 \n"
		"sll             $t7,$t6,14                             \n"
		"bgezl           $t7,.L000016                           \n"
		"lw              $t3,1660($v1)                          \n"
		"beq             $t0,$zero,.L000017                     \n"
		"lui             $a1,%hi(data_80A9F9B4)                 \n"
		"lw              $t8,304($t0)                           \n"
		"beq             $t8,$zero,.L000017                     \n"
		"nop                                                    \n"
		"sw              $zero,280($t0)                         \n"
		".L000017:                                              \n"
		"lwc1            $f12,%lo(data_80AA04E8)($at)           \n"
		"lwc1            $f0,2136($v1)                          \n"
		"lui             $at,%hi(data_80AA04EC)                 \n"
		"addiu           $a1,$a1,%lo(data_80A9F9B4)             \n"
		"c.le.s          $f0,$f12                               \n"
		"nop                                                    \n"
		"bc1fl           .L000018                               \n"
		"lw              $t3,1664($v1)                          \n"
		"lwc1            $f10,%lo(data_80AA04EC)($at)           \n"
		"c.le.s          $f10,$f0                               \n"
		"nop                                                    \n"
		"bc1f            .L000019                               \n"
		"nop                                                    \n"
		"lb              $t9,2114($v1)                          \n"
		"lui             $a3,0x8013                             \n"
		"addiu           $a3,$a3,13280                          \n"
		"slti            $at,$t9,24                             \n"
		"bne             $at,$zero,.L000019                     \n"
		"addiu           $a0,$zero,6179                         \n"
		"lui             $t1,0x8013                             \n"
		"addiu           $t1,$t1,13288                          \n"
		"addiu           $a1,$v1,228                            \n"
		"sw              $a1,68($sp)                            \n"
		"sw              $t1,20($sp)                            \n"
		"addiu           $a2,$zero,4                            \n"
		"jal             external_func_800F738C                 \n"
		"sw              $a3,16($sp)                            \n"
		"lui             $a3,0x8013                             \n"
		"lui             $t2,0x8013                             \n"
		"addiu           $a3,$a3,13280                          \n"
		"addiu           $t2,$t2,13288                          \n"
		"lw              $a1,68($sp)                            \n"
		"sw              $t2,20($sp)                            \n"
		"sw              $a3,16($sp)                            \n"
		"addiu           $a0,$zero,6168                         \n"
		"jal             external_func_800F738C                 \n"
		"addiu           $a2,$zero,4                            \n"
		".L000019:                                              \n"
		"jal             external_func_8002D570                 \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000020                   \n"
		"lw              $ra,60($sp)                            \n"
		"lw              $t3,1664($v1)                          \n"
		".L000018:                                              \n"
		"lui             $at,0xFFFD                             \n"
		"ori             $at,$at,0xffff                         \n"
		"and             $t4,$t3,$at                            \n"
		"sw              $t4,1664($v1)                          \n"
		"lh              $t5,28($s0)                            \n"
		"addiu           $a0,$zero,1                            \n"
		"lui             $at,0x8016                             \n"
		"andi            $t6,$t5,0xff00                         \n"
		"sra             $t7,$t6,8                              \n"
		"beq             $t7,$zero,.L000021                     \n"
		"nop                                                    \n"
		"sh              $a0,-1456($at)                         \n"
		".L000021:                                              \n"
		"lui             $at,%hi(data_80AA04F0)                 \n"
		"lwc1            $f18,%lo(data_80AA04F0)($at)           \n"
		"lwc1            $f16,2136($v1)                         \n"
		"addiu           $a0,$zero,1                            \n"
		"c.lt.s          $f16,$f18                              \n"
		"nop                                                    \n"
		"bc1fl           .L000022                               \n"
		"lbu             $v0,455($s0)                           \n"
		"lbu             $v0,455($s0)                           \n"
		"lui             $t9,%hi(data_80AA044C)                 \n"
		"addiu           $t1,$zero,1                            \n"
		"sll             $t8,$v0,2                              \n"
		"addu            $t9,$t9,$t8                            \n"
		"lw              $t9,%lo(data_80AA044C)($t9)            \n"
		"sb              $t1,454($s0)                           \n"
		"bne             $a0,$v0,.L000023                       \n"
		"sw              $t9,356($s0)                           \n"
		"addiu           $t2,$zero,2                            \n"
		"beq             $zero,$zero,.L000024                   \n"
		"sb              $t2,457($s0)                           \n"
		".L000023:                                              \n"
		"addiu           $t3,$zero,4                            \n"
		"beq             $zero,$zero,.L000024                   \n"
		"sb              $t3,457($s0)                           \n"
		"lbu             $v0,455($s0)                           \n"
		".L000022:                                              \n"
		"lui             $t5,%hi(data_80AA0458)                 \n"
		"addiu           $t7,$zero,8                            \n"
		"sll             $t4,$v0,2                              \n"
		"addu            $t5,$t5,$t4                            \n"
		"lw              $t5,%lo(data_80AA0458)($t5)            \n"
		"sb              $zero,454($s0)                         \n"
		"bne             $a0,$v0,.L000025                       \n"
		"sw              $t5,356($s0)                           \n"
		"addiu           $t6,$zero,4                            \n"
		"beq             $zero,$zero,.L000024                   \n"
		"sb              $t6,457($s0)                           \n"
		".L000025:                                              \n"
		"sb              $t7,457($s0)                           \n"
		".L000024:                                              \n"
		"or              $a0,$s0,$zero                          \n"
		"jal             func_80A9EFE0                          \n"
		"sw              $v1,76($sp)                            \n"
		"lbu             $t9,454($s0)                           \n"
		"lw              $v1,76($sp)                            \n"
		"addiu           $t8,$zero,8                            \n"
		"lui             $a3,0x8013                             \n"
		"sh              $t8,452($s0)                           \n"
		"lui             $a0,%hi(data_80AA0464)                 \n"
		"lui             $t2,0x8013                             \n"
		"sll             $t1,$t9,1                              \n"
		"addiu           $a3,$a3,13280                          \n"
		"addu            $a0,$a0,$t1                            \n"
		"addiu           $t2,$t2,13288                          \n"
		"sw              $t2,20($sp)                            \n"
		"lhu             $a0,%lo(data_80AA0464)($a0)            \n"
		"sw              $a3,16($sp)                            \n"
		"addiu           $a2,$zero,4                            \n"
		"jal             external_func_800F738C                 \n"
		"addiu           $a1,$v1,228                            \n"
		"lui             $at,0x3F80                             \n"
		"mtc1            $at,$f4                                \n"
		"beq             $zero,$zero,.L000014                   \n"
		"swc1            $f4,428($s0)                           \n"
		"lw              $t3,1660($v1)                          \n"
		".L000016:                                              \n"
		"lui             $at,%hi(data_80AA04F4)                 \n"
		"andi            $t4,$t3,0x1000                         \n"
		"bne             $t4,$zero,.L000026                     \n"
		"nop                                                    \n"
		"lw              $v0,284($s0)                           \n"
		"beq             $v0,$zero,.L000027                     \n"
		"nop                                                    \n"
		"sw              $zero,280($v0)                         \n"
		".L000027:                                              \n"
		"jal             external_func_8002D570                 \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000020                   \n"
		"lw              $ra,60($sp)                            \n"
		".L000026:                                              \n"
		"lwc1            $f12,%lo(data_80AA04F4)($at)           \n"
		"lwc1            $f0,2136($v1)                          \n"
		"lui             $at,%hi(data_80AA04FC)                 \n"
		"c.lt.s          $f12,$f0                               \n"
		"nop                                                    \n"
		"bc1f            .L000028                               \n"
		"nop                                                    \n"
		"lw              $t6,284($s0)                           \n"
		"addiu           $t5,$zero,255                          \n"
		"sb              $t5,456($s0)                           \n"
		"bnel            $t6,$zero,.L000029                     \n"
		"lwc1            $f16,2136($v1)                         \n"
		"lwc1            $f6,36($s0)                            \n"
		"lw              $a2,84($sp)                            \n"
		"or              $a1,$s0,$zero                          \n"
		"swc1            $f6,16($sp)                            \n"
		"lwc1            $f8,40($s0)                            \n"
		"addiu           $a3,$zero,257                          \n"
		"addiu           $a0,$a2,7204                           \n"
		"swc1            $f8,20($sp)                            \n"
		"lwc1            $f10,44($s0)                           \n"
		"sw              $zero,28($sp)                          \n"
		"swc1            $f10,24($sp)                           \n"
		"lh              $t8,182($s0)                           \n"
		"sw              $zero,36($sp)                          \n"
		"sw              $t8,32($sp)                            \n"
		"lbu             $t9,455($s0)                           \n"
		"sw              $v1,76($sp)                            \n"
		"addiu           $t1,$t9,2                              \n"
		"jal             external_func_80032458                 \n"
		"sw              $t1,40($sp)                            \n"
		"lui             $at,%hi(data_80AA04F8)                 \n"
		"lwc1            $f12,%lo(data_80AA04F8)($at)           \n"
		"lw              $v1,76($sp)                            \n"
		"lwc1            $f16,2136($v1)                         \n"
		".L000029:                                              \n"
		"lui             $at,0x3FC0                             \n"
		"mtc1            $at,$f4                                \n"
		"sub.s           $f18,$f16,$f12                         \n"
		"lwc1            $f0,444($s0)                           \n"
		"lui             $at,0x3F00                             \n"
		"mtc1            $at,$f10                               \n"
		"mul.s           $f6,$f18,$f4                           \n"
		"sub.s           $f8,$f6,$f0                            \n"
		"mul.s           $f16,$f8,$f10                          \n"
		"add.s           $f18,$f0,$f16                          \n"
		"beq             $zero,$zero,.L000030                   \n"
		"swc1            $f18,444($s0)                          \n"
		".L000028:                                              \n"
		"lwc1            $f2,%lo(data_80AA04FC)($at)            \n"
		"lui             $at,0x437F                             \n"
		"c.lt.s          $f2,$f0                                \n"
		"nop                                                    \n"
		"bc1fl           .L000030                               \n"
		"sb              $zero,456($s0)                         \n"
		"sub.s           $f4,$f0,$f2                            \n"
		"mtc1            $at,$f6                                \n"
		"lui             $at,0x41A0                             \n"
		"mtc1            $at,$f10                               \n"
		"mul.s           $f8,$f4,$f6                            \n"
		"lui             $at,0x4120                             \n"
		"mul.s           $f16,$f8,$f10                          \n"
		"mtc1            $at,$f8                                \n"
		"trunc.w.s       $f18,$f16                              \n"
		"mfc1            $t3,$f18                               \n"
		"nop                                                    \n"
		"sb              $t3,456($s0)                           \n"
		"lwc1            $f4,2136($v1)                          \n"
		"sub.s           $f6,$f4,$f2                            \n"
		"mul.s           $f10,$f6,$f8                           \n"
		"beq             $zero,$zero,.L000030                   \n"
		"swc1            $f10,428($s0)                          \n"
		"sb              $zero,456($s0)                         \n"
		".L000030:                                              \n"
		"lui             $at,%hi(data_80AA0500)                 \n"
		"lwc1            $f16,%lo(data_80AA0500)($at)           \n"
		"lwc1            $f0,2136($v1)                          \n"
		"addiu           $a0,$v1,228                            \n"
		"c.lt.s          $f16,$f0                               \n"
		"nop                                                    \n"
		"bc1fl           .L000031                               \n"
		"c.lt.s          $f12,$f0                               \n"
		"jal             external_func_800F4254                 \n"
		"addiu           $a1,$zero,2                            \n"
		"beq             $zero,$zero,.L000032                   \n"
		"nop                                                    \n"
		"c.lt.s          $f12,$f0                               \n"
		".L000031:                                              \n"
		"addiu           $a0,$v1,228                            \n"
		"lui             $at,%hi(data_80AA0504)                 \n"
		"bc1f            .L000033                               \n"
		"nop                                                    \n"
		"jal             external_func_800F4254                 \n"
		"addiu           $a1,$zero,1                            \n"
		"beq             $zero,$zero,.L000032                   \n"
		"nop                                                    \n"
		".L000033:                                              \n"
		"lwc1            $f18,%lo(data_80AA0504)($at)           \n"
		"addiu           $a0,$v1,228                            \n"
		"c.lt.s          $f18,$f0                               \n"
		"nop                                                    \n"
		"bc1f            .L000032                               \n"
		"nop                                                    \n"
		"jal             external_func_800F4254                 \n"
		"or              $a1,$zero,$zero                        \n"
		".L000032:                                              \n"
		"jal             external_func_800BFC84                 \n"
		"lw              $a0,84($sp)                            \n"
		"beql            $v0,$zero,.L000020                     \n"
		"lw              $ra,60($sp)                            \n"
		"jal             external_func_8002D570                 \n"
		"or              $a0,$s0,$zero                          \n"
		".L000014:                                              \n"
		"lw              $ra,60($sp)                            \n"
		".L000020:                                              \n"
		"lw              $s0,56($sp)                            \n"
		"addiu           $sp,$sp,80                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
const z64_actor_init_t init_vars = {
	.number = 0xDEAD, .padding = 0xBEEF, /* <-- magic values, do not change */
	.type = 0x07,
	.room = 0x00,
	.flags = 0x00000000,
	.object = OBJ_ID,
	.instance_size = sizeof(entity_t),
	.init = data_80A9EFE8,
	.dest = data_80A9F2A8,
	.main = data_80A9FB1C,
	.draw = data_80A9FCE8
};
