SUBDIRS := $(wildcard */.)

all: $(SUBDIRS)
$(SUBDIRS):
	$(MAKE) -C $@

.PHONY: all $(SUBDIRS)

En_Dekunuts:
	cd "96 - En_Dekunuts" && $(MAKE) routine

En_Nutsball:
	cd "403 - En_Nutsball" && $(MAKE) routine
