void data_80ABBE90(entity_t* en, z64_global_t* gl) /* 0 internal, 6 external, 68 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_80ABBE90: \n"
	);
	asm(
		"addiu           $sp,$sp,-72                            \n"
		"sw              $s1,24($sp)                            \n"
		"or              $s1,$a1,$zero                          \n"
		"sw              $ra,28($sp)                            \n"
		"sw              $s0,20($sp)                            \n"
		"sw              $a0,72($sp)                            \n"
		"lw              $a1,0($a1)                             \n"
		"lui             $a2,%hi(data_80ABC010)                 \n"
		"addiu           $a2,$a2,%lo(data_80ABC010)             \n"
		"addiu           $a0,$sp,48                             \n"
		"addiu           $a3,$zero,327                          \n"
		"jal             0x800C6AC4                 \n"
		"or              $s0,$a1,$zero                          \n"
		"jal             0x80093D18                 \n"
		"lw              $a0,0($s1)                             \n"
		"lui             $at,0x0001                             \n"
		"ori             $at,$at,0x1da0                         \n"
		"addu            $a0,$s1,$at                            \n"
		"jal             0x800D0930                 \n"
		"addiu           $a1,$zero,1                            \n"
		"lw              $t6,72($sp)                            \n"
		"lui             $at,%hi(data_80ABC04C)                 \n"
		"lwc1            $f8,%lo(data_80ABC04C)($at)            \n"
		"lh              $t7,24($t6)                            \n"
		"addiu           $a1,$zero,1                            \n"
		"mtc1            $t7,$f4                                \n"
		"nop                                                    \n"
		"cvt.s.w         $f6,$f4                                \n"
		"mul.s           $f12,$f6,$f8                           \n"
		"jal             0x800D0ED4                 \n"
		"nop                                                    \n"
		"lw              $v0,704($s0)                           \n"
		"lui             $t9,0xDA38                             \n"
		"ori             $t9,$t9,0x3                            \n"
		"addiu           $t8,$v0,8                              \n"
		"sw              $t8,704($s0)                           \n"
		"sw              $t9,0($v0)                             \n"
		"lw              $a0,0($s1)                             \n"
		"lui             $a1,%hi(data_80ABC024)                 \n"
		"addiu           $a1,$a1,%lo(data_80ABC024)             \n"
		"addiu           $a2,$zero,333                          \n"
		"jal             0x800D1A88                 \n"
		"sw              $v0,44($sp)                            \n"
		"lw              $v1,44($sp)                            \n"
		"lui             $t1,0xDE00                             \n"
		"lui             $t5,%hi(data_80ABBFF8)                 \n"
		"sw              $v0,4($v1)                             \n"
		"lw              $v0,704($s0)                           \n"
		"lui             $a2,%hi(data_80ABC038)                 \n"
		"addiu           $a2,$a2,%lo(data_80ABC038)             \n"
		"addiu           $t0,$v0,8                              \n"
		"sw              $t0,704($s0)                           \n"
		"sw              $t1,0($v0)                             \n"
		"lw              $t2,72($sp)                            \n"
		"addiu           $a0,$sp,48                             \n"
		"addiu           $a3,$zero,337                          \n"
		"lh              $t3,28($t2)                            \n"
		"sll             $t4,$t3,2                              \n"
		"addu            $t5,$t5,$t4                            \n"
		"lw              $t5,%lo(data_80ABBFF8)($t5)            \n"
		"sw              $t5,4($v0)                             \n"
		"jal             0x800C6B54                 \n"
		"lw              $a1,0($s1)                             \n"
		"lw              $ra,28($sp)                            \n"
		"lw              $s0,20($sp)                            \n"
		"lw              $s1,24($sp)                            \n"
		"jr              $ra                                    \n"
		"addiu           $sp,$sp,72                             \n"
	);
}
