void data_80A9F9B4(entity_t* en, z64_global_t* gl) /* 1 internal, 7 external, 96 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_80A9F9B4: \n"
	);
	asm(
		"addiu           $sp,$sp,-48                            \n"
		"sw              $ra,36($sp)                            \n"
		"sw              $s0,32($sp)                            \n"
		"sw              $a1,52($sp)                            \n"
		"lw              $t7,7236($a1)                          \n"
		"or              $s0,$a0,$zero                          \n"
		"addiu           $a0,$a0,428                            \n"
		"addiu           $a1,$zero,0                            \n"
		"lui             $a2,0x3D80                             \n"
		"jal             0x80077A00                 \n"
		"sw              $t7,44($sp)                            \n"
		"beql            $v0,$zero,.L000038                     \n"
		"lbu             $t8,457($s0)                           \n"
		"jal             0x8002D570                 \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000039                   \n"
		"lhu             $v0,452($s0)                           \n"
		"lbu             $t8,457($s0)                           \n"
		".L000038:                                              \n"
		"mtc1            $zero,$f6                              \n"
		"lui             $a2,0x3F19                             \n"
		"mtc1            $t8,$f4                                \n"
		"lui             $a3,0x3F4C                             \n"
		"ori             $a3,$a3,0xcccd                         \n"
		"cvt.s.w         $f4,$f4                                \n"
		"ori             $a2,$a2,0x999a                         \n"
		"addiu           $a0,$s0,80                             \n"
		"swc1            $f6,16($sp)                            \n"
		"mfc1            $a1,$f4                                \n"
		"jal             0x80078310                 \n"
		"nop                                                    \n"
		"or              $a0,$s0,$zero                          \n"
		"jal             0x8002D62C                 \n"
		"lw              $a1,80($s0)                            \n"
		"lui             $at,0x41C8                             \n"
		"mtc1            $at,$f10                               \n"
		"lwc1            $f8,80($s0)                            \n"
		"addiu           $a2,$s0,332                            \n"
		"or              $a1,$a2,$zero                          \n"
		"mul.s           $f16,$f8,$f10                          \n"
		"or              $a0,$s0,$zero                          \n"
		"trunc.w.s       $f18,$f16                              \n"
		"mfc1            $t0,$f18                               \n"
		"nop                                                    \n"
		"sh              $t0,396($s0)                           \n"
		"jal             0x800626DC                 \n"
		"sw              $a2,40($sp)                            \n"
		"lw              $a0,52($sp)                            \n"
		"lui             $at,0x0001                             \n"
		"ori             $at,$at,0x1e60                         \n"
		"lw              $a2,40($sp)                            \n"
		"jal             0x8005D79C                 \n"
		"addu            $a1,$a0,$at                            \n"
		"lhu             $v0,452($s0)                           \n"
		".L000039:                                              \n"
		"lw              $v1,44($sp)                            \n"
		"lui             $at,%hi(data_80AA050C)                 \n"
		"blez            $v0,.L000040                           \n"
		"or              $a0,$s0,$zero                          \n"
		"lwc1            $f4,2312($v1)                          \n"
		"addiu           $t1,$v0,-1                             \n"
		"swc1            $f4,36($s0)                            \n"
		"lwc1            $f6,2320($v1)                          \n"
		"sh              $t1,452($s0)                           \n"
		"swc1            $f6,44($s0)                            \n"
		".L000040:                                              \n"
		"lwc1            $f0,428($s0)                           \n"
		"lwc1            $f8,%lo(data_80AA050C)($at)            \n"
		"lui             $at,%hi(data_80AA0510)                 \n"
		"c.lt.s          $f8,$f0                                \n"
		"nop                                                    \n"
		"bc1f            .L000041                               \n"
		"nop                                                    \n"
		"lui             $at,0x3F80                             \n"
		"mtc1            $at,$f10                               \n"
		"beq             $zero,$zero,.L000042                   \n"
		"swc1            $f10,432($s0)                          \n"
		".L000041:                                              \n"
		"lwc1            $f16,%lo(data_80AA0510)($at)           \n"
		"mul.s           $f18,$f0,$f16                          \n"
		"swc1            $f18,432($s0)                          \n"
		".L000042:                                              \n"
		"jal             func_80A9F938                          \n"
		"lw              $a1,52($sp)                            \n"
		"jal             0x800BFC84                 \n"
		"lw              $a0,52($sp)                            \n"
		"beql            $v0,$zero,.L000043                     \n"
		"lw              $ra,36($sp)                            \n"
		"jal             0x8002D570                 \n"
		"or              $a0,$s0,$zero                          \n"
		"lw              $ra,36($sp)                            \n"
		".L000043:                                              \n"
		"lw              $s0,32($sp)                            \n"
		"addiu           $sp,$sp,48                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
