void data_80A9F408(entity_t* en, z64_global_t* gl) /* 2 internal, 7 external, 355 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_80A9F408: \n"
	);
	asm(
		"addiu           $sp,$sp,-80                            \n"
		"sw              $ra,60($sp)                            \n"
		"sw              $s0,56($sp)                            \n"
		"sw              $a1,84($sp)                            \n"
		"lw              $v1,7236($a1)                          \n"
		"lbu             $t2,458($a0)                           \n"
		"ori             $at,$zero,0x8000                       \n"
		"lwc1            $f4,2136($v1)                          \n"
		"or              $s0,$a0,$zero                          \n"
		"lw              $t0,284($a0)                           \n"
		"swc1            $f4,440($a0)                           \n"
		"lw              $t8,2312($v1)                          \n"
		"sw              $t8,36($a0)                            \n"
		"lw              $t7,2316($v1)                          \n"
		"sw              $t7,40($a0)                            \n"
		"lw              $t8,2320($v1)                          \n"
		"sw              $t8,44($a0)                            \n"
		"lh              $t9,182($v1)                           \n"
		"addu            $t1,$t9,$at                            \n"
		"bne             $t2,$zero,.L000011                     \n"
		"sh              $t1,182($a0)                           \n"
		"lui             $at,%hi(data_80AA04E0)                 \n"
		"lwc1            $f8,%lo(data_80AA04E0)($at)            \n"
		"lwc1            $f6,2136($v1)                          \n"
		"lui             $t3,0x8016                             \n"
		"c.le.s          $f8,$f6                                \n"
		"nop                                                    \n"
		"bc1f            .L000011                               \n"
		"nop                                                    \n"
		"lh              $t3,-1456($t3)                         \n"
		"bnel            $t3,$zero,.L000012                     \n"
		"or              $a0,$s0,$zero                          \n"
		"lh              $v0,28($a0)                            \n"
		"lw              $a0,84($sp)                            \n"
		"addiu           $a2,$zero,4                            \n"
		"andi            $v0,$v0,0xff00                         \n"
		"sra             $v0,$v0,8                              \n"
		"beq             $v0,$zero,.L000013                     \n"
		"sll             $a1,$v0,16                             \n"
		"sra             $a1,$a1,16                             \n"
		"sw              $v1,76($sp)                            \n"
		"jal             0x80087708                 \n"
		"sw              $t0,72($sp)                            \n"
		"lw              $v1,76($sp)                            \n"
		"bne             $v0,$zero,.L000013                     \n"
		"lw              $t0,72($sp)                            \n"
		"or              $a0,$s0,$zero                          \n"
		".L000012:                                              \n"
		"jal             func_80A9F350                          \n"
		"lw              $a1,84($sp)                            \n"
		"lui             $a1,%hi(func_80A9F350)                 \n"
		"addiu           $a1,$a1,%lo(func_80A9F350)             \n"
		"jal             func_80A9EFE0                          \n"
		"or              $a0,$s0,$zero                          \n"
		"mtc1            $zero,$f10                             \n"
		"mtc1            $zero,$f16                             \n"
		"sb              $zero,456($s0)                         \n"
		"swc1            $f10,444($s0)                          \n"
		"beq             $zero,$zero,.L000014                   \n"
		"swc1            $f16,428($s0)                          \n"
		".L000013:                                              \n"
		"addiu           $t4,$zero,1                            \n"
		"sb              $t4,458($s0)                           \n"
		".L000011:                                              \n"
		"lui             $at,%hi(data_80AA04E4)                 \n"
		"lwc1            $f18,%lo(data_80AA04E4)($at)           \n"
		"lwc1            $f0,2136($v1)                          \n"
		"lui             $at,0x4316                             \n"
		"c.le.s          $f18,$f0                               \n"
		"nop                                                    \n"
		"bc1fl           .L000015                               \n"
		"lw              $t6,1664($v1)                          \n"
		"mtc1            $at,$f4                                \n"
		"mtc1            $zero,$f12                             \n"
		"addiu           $a2,$zero,2                            \n"
		"mul.s           $f6,$f0,$f4                            \n"
		"sw              $v1,76($sp)                            \n"
		"sw              $t0,72($sp)                            \n"
		"trunc.w.s       $f8,$f6                                \n"
		"mfc1            $a1,$f8                                \n"
		"nop                                                    \n"
		"andi            $a1,$a1,0xff                           \n"
		"jal             0x800AA000                 \n"
		"andi            $a3,$a1,0xff                           \n"
		"lw              $v1,76($sp)                            \n"
		"lw              $t0,72($sp)                            \n"
		"lw              $t6,1664($v1)                          \n"
		".L000015:                                              \n"
		"lui             $at,%hi(data_80AA04E8)                 \n"
		"sll             $t7,$t6,14                             \n"
		"bgezl           $t7,.L000016                           \n"
		"lw              $t3,1660($v1)                          \n"
		"beq             $t0,$zero,.L000017                     \n"
		"lui             $a1,%hi(data_80A9F9B4)                 \n"
		"lw              $t8,304($t0)                           \n"
		"beq             $t8,$zero,.L000017                     \n"
		"nop                                                    \n"
		"sw              $zero,280($t0)                         \n"
		".L000017:                                              \n"
		"lwc1            $f12,%lo(data_80AA04E8)($at)           \n"
		"lwc1            $f0,2136($v1)                          \n"
		"lui             $at,%hi(data_80AA04EC)                 \n"
		"addiu           $a1,$a1,%lo(data_80A9F9B4)             \n"
		"c.le.s          $f0,$f12                               \n"
		"nop                                                    \n"
		"bc1fl           .L000018                               \n"
		"lw              $t3,1664($v1)                          \n"
		"lwc1            $f10,%lo(data_80AA04EC)($at)           \n"
		"c.le.s          $f10,$f0                               \n"
		"nop                                                    \n"
		"bc1f            .L000019                               \n"
		"nop                                                    \n"
		"lb              $t9,2114($v1)                          \n"
		"lui             $a3,0x8013                             \n"
		"addiu           $a3,$a3,13280                          \n"
		"slti            $at,$t9,24                             \n"
		"bne             $at,$zero,.L000019                     \n"
		"addiu           $a0,$zero,6179                         \n"
		"lui             $t1,0x8013                             \n"
		"addiu           $t1,$t1,13288                          \n"
		"addiu           $a1,$v1,228                            \n"
		"sw              $a1,68($sp)                            \n"
		"sw              $t1,20($sp)                            \n"
		"addiu           $a2,$zero,4                            \n"
		"jal             0x800F738C                 \n"
		"sw              $a3,16($sp)                            \n"
		"lui             $a3,0x8013                             \n"
		"lui             $t2,0x8013                             \n"
		"addiu           $a3,$a3,13280                          \n"
		"addiu           $t2,$t2,13288                          \n"
		"lw              $a1,68($sp)                            \n"
		"sw              $t2,20($sp)                            \n"
		"sw              $a3,16($sp)                            \n"
		"addiu           $a0,$zero,6168                         \n"
		"jal             0x800F738C                 \n"
		"addiu           $a2,$zero,4                            \n"
		".L000019:                                              \n"
		"jal             0x8002D570                 \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000020                   \n"
		"lw              $ra,60($sp)                            \n"
		"lw              $t3,1664($v1)                          \n"
		".L000018:                                              \n"
		"lui             $at,0xFFFD                             \n"
		"ori             $at,$at,0xffff                         \n"
		"and             $t4,$t3,$at                            \n"
		"sw              $t4,1664($v1)                          \n"
		"lh              $t5,28($s0)                            \n"
		"addiu           $a0,$zero,1                            \n"
		"lui             $at,0x8016                             \n"
		"andi            $t6,$t5,0xff00                         \n"
		"sra             $t7,$t6,8                              \n"
		"beq             $t7,$zero,.L000021                     \n"
		"nop                                                    \n"
		"sh              $a0,-1456($at)                         \n"
		".L000021:                                              \n"
		"lui             $at,%hi(data_80AA04F0)                 \n"
		"lwc1            $f18,%lo(data_80AA04F0)($at)           \n"
		"lwc1            $f16,2136($v1)                         \n"
		"addiu           $a0,$zero,1                            \n"
		"c.lt.s          $f16,$f18                              \n"
		"nop                                                    \n"
		"bc1fl           .L000022                               \n"
		"lbu             $v0,455($s0)                           \n"
		"lbu             $v0,455($s0)                           \n"
		"lui             $t9,%hi(data_80AA044C)                 \n"
		"addiu           $t1,$zero,1                            \n"
		"sll             $t8,$v0,2                              \n"
		"addu            $t9,$t9,$t8                            \n"
		"lw              $t9,%lo(data_80AA044C)($t9)            \n"
		"sb              $t1,454($s0)                           \n"
		"bne             $a0,$v0,.L000023                       \n"
		"sw              $t9,356($s0)                           \n"
		"addiu           $t2,$zero,2                            \n"
		"beq             $zero,$zero,.L000024                   \n"
		"sb              $t2,457($s0)                           \n"
		".L000023:                                              \n"
		"addiu           $t3,$zero,4                            \n"
		"beq             $zero,$zero,.L000024                   \n"
		"sb              $t3,457($s0)                           \n"
		"lbu             $v0,455($s0)                           \n"
		".L000022:                                              \n"
		"lui             $t5,%hi(data_80AA0458)                 \n"
		"addiu           $t7,$zero,8                            \n"
		"sll             $t4,$v0,2                              \n"
		"addu            $t5,$t5,$t4                            \n"
		"lw              $t5,%lo(data_80AA0458)($t5)            \n"
		"sb              $zero,454($s0)                         \n"
		"bne             $a0,$v0,.L000025                       \n"
		"sw              $t5,356($s0)                           \n"
		"addiu           $t6,$zero,4                            \n"
		"beq             $zero,$zero,.L000024                   \n"
		"sb              $t6,457($s0)                           \n"
		".L000025:                                              \n"
		"sb              $t7,457($s0)                           \n"
		".L000024:                                              \n"
		"or              $a0,$s0,$zero                          \n"
		"jal             func_80A9EFE0                          \n"
		"sw              $v1,76($sp)                            \n"
		"lbu             $t9,454($s0)                           \n"
		"lw              $v1,76($sp)                            \n"
		"addiu           $t8,$zero,8                            \n"
		"lui             $a3,0x8013                             \n"
		"sh              $t8,452($s0)                           \n"
		"lui             $a0,%hi(data_80AA0464)                 \n"
		"lui             $t2,0x8013                             \n"
		"sll             $t1,$t9,1                              \n"
		"addiu           $a3,$a3,13280                          \n"
		"addu            $a0,$a0,$t1                            \n"
		"addiu           $t2,$t2,13288                          \n"
		"sw              $t2,20($sp)                            \n"
		"lhu             $a0,%lo(data_80AA0464)($a0)            \n"
		"sw              $a3,16($sp)                            \n"
		"addiu           $a2,$zero,4                            \n"
		"jal             0x800F738C                 \n"
		"addiu           $a1,$v1,228                            \n"
		"lui             $at,0x3F80                             \n"
		"mtc1            $at,$f4                                \n"
		"beq             $zero,$zero,.L000014                   \n"
		"swc1            $f4,428($s0)                           \n"
		"lw              $t3,1660($v1)                          \n"
		".L000016:                                              \n"
		"lui             $at,%hi(data_80AA04F4)                 \n"
		"andi            $t4,$t3,0x1000                         \n"
		"bne             $t4,$zero,.L000026                     \n"
		"nop                                                    \n"
		"lw              $v0,284($s0)                           \n"
		"beq             $v0,$zero,.L000027                     \n"
		"nop                                                    \n"
		"sw              $zero,280($v0)                         \n"
		".L000027:                                              \n"
		"jal             0x8002D570                 \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000020                   \n"
		"lw              $ra,60($sp)                            \n"
		".L000026:                                              \n"
		"lwc1            $f12,%lo(data_80AA04F4)($at)           \n"
		"lwc1            $f0,2136($v1)                          \n"
		"lui             $at,%hi(data_80AA04FC)                 \n"
		"c.lt.s          $f12,$f0                               \n"
		"nop                                                    \n"
		"bc1f            .L000028                               \n"
		"nop                                                    \n"
		"lw              $t6,284($s0)                           \n"
		"addiu           $t5,$zero,255                          \n"
		"sb              $t5,456($s0)                           \n"
		"bnel            $t6,$zero,.L000029                     \n"
		"lwc1            $f16,2136($v1)                         \n"
		"lwc1            $f6,36($s0)                            \n"
		"lw              $a2,84($sp)                            \n"
		"or              $a1,$s0,$zero                          \n"
		"swc1            $f6,16($sp)                            \n"
		"lwc1            $f8,40($s0)                            \n"
		"addiu           $a3,$zero,257                          \n"
		"addiu           $a0,$a2,7204                           \n"
		"swc1            $f8,20($sp)                            \n"
		"lwc1            $f10,44($s0)                           \n"
		"sw              $zero,28($sp)                          \n"
		"swc1            $f10,24($sp)                           \n"
		"lh              $t8,182($s0)                           \n"
		"sw              $zero,36($sp)                          \n"
		"sw              $t8,32($sp)                            \n"
		"lbu             $t9,455($s0)                           \n"
		"sw              $v1,76($sp)                            \n"
		"addiu           $t1,$t9,2                              \n"
		"jal             0x80032458                 \n"
		"sw              $t1,40($sp)                            \n"
		"lui             $at,%hi(data_80AA04F8)                 \n"
		"lwc1            $f12,%lo(data_80AA04F8)($at)           \n"
		"lw              $v1,76($sp)                            \n"
		"lwc1            $f16,2136($v1)                         \n"
		".L000029:                                              \n"
		"lui             $at,0x3FC0                             \n"
		"mtc1            $at,$f4                                \n"
		"sub.s           $f18,$f16,$f12                         \n"
		"lwc1            $f0,444($s0)                           \n"
		"lui             $at,0x3F00                             \n"
		"mtc1            $at,$f10                               \n"
		"mul.s           $f6,$f18,$f4                           \n"
		"sub.s           $f8,$f6,$f0                            \n"
		"mul.s           $f16,$f8,$f10                          \n"
		"add.s           $f18,$f0,$f16                          \n"
		"beq             $zero,$zero,.L000030                   \n"
		"swc1            $f18,444($s0)                          \n"
		".L000028:                                              \n"
		"lwc1            $f2,%lo(data_80AA04FC)($at)            \n"
		"lui             $at,0x437F                             \n"
		"c.lt.s          $f2,$f0                                \n"
		"nop                                                    \n"
		"bc1fl           .L000030                               \n"
		"sb              $zero,456($s0)                         \n"
		"sub.s           $f4,$f0,$f2                            \n"
		"mtc1            $at,$f6                                \n"
		"lui             $at,0x41A0                             \n"
		"mtc1            $at,$f10                               \n"
		"mul.s           $f8,$f4,$f6                            \n"
		"lui             $at,0x4120                             \n"
		"mul.s           $f16,$f8,$f10                          \n"
		"mtc1            $at,$f8                                \n"
		"trunc.w.s       $f18,$f16                              \n"
		"mfc1            $t3,$f18                               \n"
		"nop                                                    \n"
		"sb              $t3,456($s0)                           \n"
		"lwc1            $f4,2136($v1)                          \n"
		"sub.s           $f6,$f4,$f2                            \n"
		"mul.s           $f10,$f6,$f8                           \n"
		"beq             $zero,$zero,.L000030                   \n"
		"swc1            $f10,428($s0)                          \n"
		"sb              $zero,456($s0)                         \n"
		".L000030:                                              \n"
		"lui             $at,%hi(data_80AA0500)                 \n"
		"lwc1            $f16,%lo(data_80AA0500)($at)           \n"
		"lwc1            $f0,2136($v1)                          \n"
		"addiu           $a0,$v1,228                            \n"
		"c.lt.s          $f16,$f0                               \n"
		"nop                                                    \n"
		"bc1fl           .L000031                               \n"
		"c.lt.s          $f12,$f0                               \n"
		"jal             0x800F4254                 \n"
		"addiu           $a1,$zero,2                            \n"
		"beq             $zero,$zero,.L000032                   \n"
		"nop                                                    \n"
		"c.lt.s          $f12,$f0                               \n"
		".L000031:                                              \n"
		"addiu           $a0,$v1,228                            \n"
		"lui             $at,%hi(data_80AA0504)                 \n"
		"bc1f            .L000033                               \n"
		"nop                                                    \n"
		"jal             0x800F4254                 \n"
		"addiu           $a1,$zero,1                            \n"
		"beq             $zero,$zero,.L000032                   \n"
		"nop                                                    \n"
		".L000033:                                              \n"
		"lwc1            $f18,%lo(data_80AA0504)($at)           \n"
		"addiu           $a0,$v1,228                            \n"
		"c.lt.s          $f18,$f0                               \n"
		"nop                                                    \n"
		"bc1f            .L000032                               \n"
		"nop                                                    \n"
		"jal             0x800F4254                 \n"
		"or              $a1,$zero,$zero                        \n"
		".L000032:                                              \n"
		"jal             0x800BFC84                 \n"
		"lw              $a0,84($sp)                            \n"
		"beql            $v0,$zero,.L000020                     \n"
		"lw              $ra,60($sp)                            \n"
		"jal             0x8002D570                 \n"
		"or              $a0,$s0,$zero                          \n"
		".L000014:                                              \n"
		"lw              $ra,60($sp)                            \n"
		".L000020:                                              \n"
		"lw              $s0,56($sp)                            \n"
		"addiu           $sp,$sp,80                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
