void data_80A9FB1C(entity_t* en, z64_global_t* gl) /* 1 internal, 1 external, 121 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_80A9FB1C: \n"
	);
	asm(
		"addiu           $sp,$sp,-48                            \n"
		"sw              $s0,40($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,44($sp)                            \n"
		"sw              $a1,52($sp)                            \n"
		"lw              $t9,448($s0)                           \n"
		"jalr            $t9                                    \n"
		"nop                                                    \n"
		"lw              $a0,52($sp)                            \n"
		"jal             func_80A9F314                          \n"
		"lw              $a1,444($s0)                           \n"
		"lwc1            $f4,36($s0)                            \n"
		"lui             $at,0x437F                             \n"
		"lwc1            $f0,428($s0)                           \n"
		"trunc.w.s       $f6,$f4                                \n"
		"mtc1            $at,$f4                                \n"
		"lwc1            $f8,40($s0)                            \n"
		"lwc1            $f16,44($s0)                           \n"
		"mfc1            $a1,$f6                                \n"
		"mul.s           $f6,$f0,$f4                            \n"
		"trunc.w.s       $f10,$f8                               \n"
		"addiu           $v0,$zero,1                            \n"
		"sll             $a1,$a1,16                             \n"
		"sra             $a1,$a1,16                             \n"
		"mfc1            $a2,$f10                               \n"
		"trunc.w.s       $f18,$f16                              \n"
		"lui             $at,0x4F00                             \n"
		"sll             $a2,$a2,16                             \n"
		"sra             $a2,$a2,16                             \n"
		"cfc1            $t0,$f31                               \n"
		"ctc1            $v0,$f31                               \n"
		"mfc1            $a3,$f18                               \n"
		"addiu           $a0,$s0,412                            \n"
		"cvt.w.s         $f8,$f6                                \n"
		"sll             $a3,$a3,16                             \n"
		"sra             $a3,$a3,16                             \n"
		"cfc1            $v0,$f31                               \n"
		"nop                                                    \n"
		"andi            $v0,$v0,0x78                           \n"
		"beql            $v0,$zero,.L000044                     \n"
		"mfc1            $v0,$f8                                \n"
		"mtc1            $at,$f8                                \n"
		"addiu           $v0,$zero,1                            \n"
		"sub.s           $f8,$f6,$f8                            \n"
		"ctc1            $v0,$f31                               \n"
		"nop                                                    \n"
		"cvt.w.s         $f8,$f8                                \n"
		"cfc1            $v0,$f31                               \n"
		"nop                                                    \n"
		"andi            $v0,$v0,0x78                           \n"
		"bne             $v0,$zero,.L000045                     \n"
		"nop                                                    \n"
		"mfc1            $v0,$f8                                \n"
		"lui             $at,0x8000                             \n"
		"beq             $zero,$zero,.L000046                   \n"
		"or              $v0,$v0,$at                            \n"
		".L000045:                                              \n"
		"beq             $zero,$zero,.L000046                   \n"
		"addiu           $v0,$zero,-1                           \n"
		"mfc1            $v0,$f8                                \n"
		".L000044:                                              \n"
		"nop                                                    \n"
		"bltz            $v0,.L000045                           \n"
		"nop                                                    \n"
		".L000046:                                              \n"
		"lui             $at,0x42C8                             \n"
		"ctc1            $t0,$f31                               \n"
		"mtc1            $at,$f10                               \n"
		"addiu           $t2,$zero,1                            \n"
		"andi            $v0,$v0,0xff                           \n"
		"mul.s           $f16,$f0,$f10                          \n"
		"sw              $v0,16($sp)                            \n"
		"sw              $v0,20($sp)                            \n"
		"lui             $at,0x4F00                             \n"
		"cfc1            $t1,$f31                               \n"
		"ctc1            $t2,$f31                               \n"
		"nop                                                    \n"
		"cvt.w.s         $f18,$f16                              \n"
		"cfc1            $t2,$f31                               \n"
		"nop                                                    \n"
		"andi            $t2,$t2,0x78                           \n"
		"beql            $t2,$zero,.L000047                     \n"
		"mfc1            $t2,$f18                               \n"
		"mtc1            $at,$f18                               \n"
		"addiu           $t2,$zero,1                            \n"
		"sub.s           $f18,$f16,$f18                         \n"
		"ctc1            $t2,$f31                               \n"
		"nop                                                    \n"
		"cvt.w.s         $f18,$f18                              \n"
		"cfc1            $t2,$f31                               \n"
		"nop                                                    \n"
		"andi            $t2,$t2,0x78                           \n"
		"bne             $t2,$zero,.L000048                     \n"
		"nop                                                    \n"
		"mfc1            $t2,$f18                               \n"
		"lui             $at,0x8000                             \n"
		"beq             $zero,$zero,.L000049                   \n"
		"or              $t2,$t2,$at                            \n"
		".L000048:                                              \n"
		"beq             $zero,$zero,.L000049                   \n"
		"addiu           $t2,$zero,-1                           \n"
		"mfc1            $t2,$f18                               \n"
		".L000047:                                              \n"
		"nop                                                    \n"
		"bltz            $t2,.L000048                           \n"
		"nop                                                    \n"
		".L000049:                                              \n"
		"lui             $at,0x4448                             \n"
		"mtc1            $at,$f4                                \n"
		"ctc1            $t1,$f31                               \n"
		"sw              $t2,24($sp)                            \n"
		"mul.s           $f6,$f0,$f4                            \n"
		"trunc.w.s       $f8,$f6                                \n"
		"mfc1            $t4,$f8                                \n"
		"jal             0x80079D8C                 \n"
		"sw              $t4,28($sp)                            \n"
		"lw              $ra,44($sp)                            \n"
		"lw              $s0,40($sp)                            \n"
		"addiu           $sp,$sp,48                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
