void func_80A9F938(entity_t* en) /* 0 internal, 0 external, 35 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_80A9F938: \n"
	);
	asm(
		"sw              $a1,4($sp)                             \n"
		"lhu             $t6,452($a0)                           \n"
		"slti            $at,$t6,2                              \n"
		"beql            $at,$zero,.L000034                     \n"
		"lwc1            $f0,432($a0)                           \n"
		"lbu             $v0,456($a0)                           \n"
		"slti            $at,$v0,40                             \n"
		"beq             $at,$zero,.L000035                     \n"
		"addiu           $t7,$v0,-40                            \n"
		"beq             $zero,$zero,.L000036                   \n"
		"sb              $zero,456($a0)                         \n"
		".L000035:                                              \n"
		"sb              $t7,456($a0)                           \n"
		".L000036:                                              \n"
		"lwc1            $f0,432($a0)                           \n"
		".L000034:                                              \n"
		"lwc1            $f2,444($a0)                           \n"
		"lwc1            $f12,428($a0)                          \n"
		"add.s           $f6,$f0,$f0                            \n"
		"lwc1            $f4,436($a0)                           \n"
		"lui             $at,%hi(data_80AA0508)                 \n"
		"c.lt.s          $f2,$f12                               \n"
		"add.s           $f8,$f4,$f6                            \n"
		"bc1f            .L000037                               \n"
		"swc1            $f8,436($a0)                           \n"
		"sub.s           $f10,$f12,$f2                          \n"
		"lwc1            $f16,%lo(data_80AA0508)($at)           \n"
		"mul.s           $f18,$f10,$f16                         \n"
		"add.s           $f4,$f2,$f18                           \n"
		"jr              $ra                                    \n"
		"swc1            $f4,444($a0)                           \n"
		".L000037:                                              \n"
		"swc1            $f12,444($a0)                          \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
