void data_80ABBA50(entity_t* en, z64_global_t* gl) /* 0 internal, 5 external, 49 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_80ABBA50: \n"
	);
	asm(
		"addiu           $sp,$sp,-48                            \n"
		"sw              $s0,24($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,28($sp)                            \n"
		"sw              $a1,52($sp)                            \n"
		"lui             $a2,0x8003                             \n"
		"addiu           $a2,$a2,-18964                         \n"
		"lui             $a1,0x43C8                             \n"
		"addiu           $a0,$a0,180                            \n"
		"jal             0x8002B1E0                 \n"
		"lui             $a3,0x4150                             \n"
		"addiu           $a1,$s0,340                            \n"
		"sw              $a1,36($sp)                            \n"
		"jal             0x8005C364                 \n"
		"lw              $a0,52($sp)                            \n"
		"lui             $a3,%hi(data_80ABBFC0)                 \n"
		"lw              $a1,36($sp)                            \n"
		"addiu           $a3,$a3,%lo(data_80ABBFC0)             \n"
		"lw              $a0,52($sp)                            \n"
		"jal             0x8005C4AC                 \n"
		"or              $a2,$s0,$zero                          \n"
		"lh              $t6,28($s0)                            \n"
		"lw              $a0,52($sp)                            \n"
		"lui             $at,0x0001                             \n"
		"lui             $a1,%hi(data_80ABBFEC)                 \n"
		"sll             $t7,$t6,1                              \n"
		"addu            $a1,$a1,$t7                            \n"
		"ori             $at,$at,0x17a4                         \n"
		"lh              $a1,%lo(data_80ABBFEC)($a1)            \n"
		"jal             0x8009812C                 \n"
		"addu            $a0,$a0,$at                            \n"
		"sb              $v0,336($s0)                           \n"
		"lb              $t8,336($s0)                           \n"
		"lui             $t9,%hi(data_80ABBB34)                 \n"
		"addiu           $t9,$t9,%lo(data_80ABBB34)             \n"
		"bgezl           $t8,.L000000                           \n"
		"sw              $t9,332($s0)                           \n"
		"jal             0x8002D570                 \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000001                   \n"
		"lw              $ra,28($sp)                            \n"
		"sw              $t9,332($s0)                           \n"
		".L000000:                                              \n"
		"lw              $ra,28($sp)                            \n"
		".L000001:                                              \n"
		"lw              $s0,24($sp)                            \n"
		"addiu           $sp,$sp,48                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
