void data_809E9E80(entity_t* en) /* 2 internal, 3 external, 65 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809E9E80: \n"
	);
	asm(
		"addiu           $sp,$sp,-40                            \n"
		"sw              $s0,24($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,28($sp)                            \n"
		"addiu           $a0,$a0,332                            \n"
		"sw              $a1,44($sp)                            \n"
		"jal             0x800A49FC                 \n"
		"sw              $a0,36($sp)                            \n"
		"lw              $a0,36($sp)                            \n"
		"jal             0x800A56C8                 \n"
		"addiu           $a1,$zero,0                            \n"
		"beq             $v0,$zero,.L000029                     \n"
		"addiu           $a0,$s0,182                            \n"
		"lh              $v0,406($s0)                           \n"
		"beq             $v0,$zero,.L000029                     \n"
		"addiu           $t6,$v0,-1                             \n"
		"sh              $t6,406($s0)                           \n"
		".L000029:                                              \n"
		"lh              $v0,406($s0)                           \n"
		"addiu           $a2,$zero,2                            \n"
		"addiu           $a3,$zero,3640                         \n"
		"andi            $t7,$v0,0x1000                         \n"
		"bnel            $t7,$zero,.L000030                     \n"
		"addiu           $at,$zero,4096                         \n"
		"jal             0x800787BC                 \n"
		"lh              $a1,138($s0)                           \n"
		"lh              $v0,406($s0)                           \n"
		"addiu           $at,$zero,4096                         \n"
		".L000030:                                              \n"
		"bne             $v0,$at,.L000031                       \n"
		"lui             $at,0x43F0                             \n"
		"mtc1            $at,$f4                                \n"
		"lwc1            $f0,144($s0)                           \n"
		"lui             $at,0x42F0                             \n"
		"c.lt.s          $f4,$f0                                \n"
		"nop                                                    \n"
		"bc1t            .L000032                               \n"
		"nop                                                    \n"
		"mtc1            $at,$f6                                \n"
		"nop                                                    \n"
		"c.lt.s          $f0,$f6                                \n"
		"nop                                                    \n"
		"bc1f            .L000033                               \n"
		"nop                                                    \n"
		".L000032:                                              \n"
		"jal             func_809E9868                          \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000034                   \n"
		"lw              $ra,28($sp)                            \n"
		".L000033:                                              \n"
		"jal             func_809E97B8                          \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000034                   \n"
		"lw              $ra,28($sp)                            \n"
		".L000031:                                              \n"
		"bnel            $v0,$zero,.L000034                     \n"
		"lw              $ra,28($sp)                            \n"
		"jal             func_809E97B8                          \n"
		"or              $a0,$s0,$zero                          \n"
		"lw              $ra,28($sp)                            \n"
		".L000034:                                              \n"
		"lw              $s0,24($sp)                            \n"
		"addiu           $sp,$sp,40                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
