void data_809E9B98(entity_t* en) /* 3 internal, 3 external, 169 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809E9B98: \n"
	);
	asm(
		"addiu           $sp,$sp,-48                            \n"
		"sw              $ra,28($sp)                            \n"
		"sw              $s0,24($sp)                            \n"
		"sw              $a1,52($sp)                            \n"
		"lui             $at,0x3F00                             \n"
		"mtc1            $at,$f6                                \n"
		"lwc1            $f4,360($a0)                           \n"
		"or              $s0,$a0,$zero                          \n"
		"or              $v1,$zero,$zero                        \n"
		"c.lt.s          $f4,$f6                                \n"
		"addiu           $a0,$s0,332                            \n"
		"lui             $a1,0x4110                             \n"
		"bc1f            .L000010                               \n"
		"nop                                                    \n"
		"addiu           $v1,$zero,1                            \n"
		".L000010:                                              \n"
		"beql            $v1,$zero,.L000011                     \n"
		"sw              $v1,44($sp)                            \n"
		"lh              $v0,406($s0)                           \n"
		"beq             $v0,$zero,.L000012                     \n"
		"addiu           $t6,$v0,-1                             \n"
		"sh              $t6,406($s0)                           \n"
		".L000012:                                              \n"
		"sw              $v1,44($sp)                            \n"
		".L000011:                                              \n"
		"jal             0x800A56C8                 \n"
		"sw              $a0,32($sp)                            \n"
		"lui             $at,0x4110                             \n"
		"mtc1            $at,$f12                               \n"
		"beq             $v0,$zero,.L000013                     \n"
		"lw              $a0,32($sp)                            \n"
		"lbu             $t7,729($s0)                           \n"
		"ori             $t8,$t7,0x1                            \n"
		"beq             $zero,$zero,.L000014                   \n"
		"sb              $t8,729($s0)                           \n"
		".L000013:                                              \n"
		"jal             0x800A56C8                 \n"
		"lui             $a1,0x4100                             \n"
		"lui             $at,0x4110                             \n"
		"mtc1            $at,$f12                               \n"
		"beq             $v0,$zero,.L000014                     \n"
		"or              $a0,$s0,$zero                          \n"
		"jal             0x8002F828                 \n"
		"addiu           $a1,$zero,14460                        \n"
		"lui             $at,0x4110                             \n"
		"mtc1            $at,$f12                               \n"
		"nop                                                    \n"
		".L000014:                                              \n"
		"lwc1            $f0,356($s0)                           \n"
		"lui             $at,0x4140                             \n"
		"c.lt.s          $f0,$f12                               \n"
		"nop                                                    \n"
		"bc1fl           .L000015                               \n"
		"mtc1            $at,$f14                               \n"
		"beq             $zero,$zero,.L000016                   \n"
		"mov.s           $f0,$f12                               \n"
		"mtc1            $at,$f14                               \n"
		".L000015:                                              \n"
		"nop                                                    \n"
		"c.lt.s          $f14,$f0                               \n"
		"nop                                                    \n"
		"bc1fl           .L000017                               \n"
		"mov.s           $f2,$f0                                \n"
		"beq             $zero,$zero,.L000017                   \n"
		"mov.s           $f2,$f14                               \n"
		"mov.s           $f2,$f0                                \n"
		".L000017:                                              \n"
		"mov.s           $f0,$f2                                \n"
		".L000016:                                              \n"
		"sub.s           $f8,$f0,$f12                           \n"
		"lui             $at,0x40A0                             \n"
		"mtc1            $at,$f16                               \n"
		"lui             $at,0x42F0                             \n"
		"mul.s           $f10,$f8,$f12                          \n"
		"add.s           $f18,$f10,$f16                         \n"
		"trunc.w.s       $f4,$f18                               \n"
		"mfc1            $t0,$f4                                \n"
		"nop                                                    \n"
		"sh              $t0,778($s0)                           \n"
		"lw              $t1,44($sp)                            \n"
		"bne             $t1,$zero,.L000018                     \n"
		"nop                                                    \n"
		"lwc1            $f6,144($s0)                           \n"
		"mtc1            $at,$f8                                \n"
		"nop                                                    \n"
		"c.lt.s          $f6,$f8                                \n"
		"nop                                                    \n"
		"bc1f            .L000018                               \n"
		"nop                                                    \n"
		"jal             func_809E9868                          \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000019                   \n"
		"lw              $t3,44($sp)                            \n"
		".L000018:                                              \n"
		"jal             0x800A49FC                 \n"
		"lw              $a0,32($sp)                            \n"
		"beq             $v0,$zero,.L000020                     \n"
		"lui             $at,0x42F0                             \n"
		"lwc1            $f2,144($s0)                           \n"
		"mtc1            $at,$f10                               \n"
		"nop                                                    \n"
		"c.lt.s          $f2,$f10                               \n"
		"nop                                                    \n"
		"bc1fl           .L000021                               \n"
		"lh              $t2,406($s0)                           \n"
		"jal             func_809E9868                          \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000019                   \n"
		"lw              $t3,44($sp)                            \n"
		"lh              $t2,406($s0)                           \n"
		".L000021:                                              \n"
		"lui             $at,0x43A0                             \n"
		"bne             $t2,$zero,.L000022                     \n"
		"nop                                                    \n"
		"mtc1            $at,$f16                               \n"
		"nop                                                    \n"
		"c.lt.s          $f16,$f2                               \n"
		"nop                                                    \n"
		"bc1f            .L000022                               \n"
		"nop                                                    \n"
		"jal             func_809E9770                          \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000019                   \n"
		"lw              $t3,44($sp)                            \n"
		".L000022:                                              \n"
		"jal             func_809E9800                          \n"
		"or              $a0,$s0,$zero                          \n"
		".L000020:                                              \n"
		"lw              $t3,44($sp)                            \n"
		".L000019:                                              \n"
		"lui             $at,0x4320                             \n"
		"beql            $t3,$zero,.L000023                     \n"
		"lw              $ra,28($sp)                            \n"
		"lwc1            $f2,144($s0)                           \n"
		"mtc1            $at,$f18                               \n"
		"nop                                                    \n"
		"c.lt.s          $f18,$f2                               \n"
		"nop                                                    \n"
		"bc1fl           .L000023                               \n"
		"lw              $ra,28($sp)                            \n"
		"lwc1            $f0,148($s0)                           \n"
		"lui             $at,0x42F0                             \n"
		"mtc1            $at,$f4                                \n"
		"abs.s           $f0,$f0                                \n"
		"c.lt.s          $f0,$f4                                \n"
		"nop                                                    \n"
		"bc1fl           .L000023                               \n"
		"lw              $ra,28($sp)                            \n"
		"lh              $t4,406($s0)                           \n"
		"lui             $at,0x43F0                             \n"
		"beql            $t4,$zero,.L000024                     \n"
		"lui             $at,0x3F80                             \n"
		"mtc1            $at,$f6                                \n"
		"nop                                                    \n"
		"c.lt.s          $f2,$f6                                \n"
		"nop                                                    \n"
		"bc1f            .L000025                               \n"
		"lui             $at,0x3F80                             \n"
		".L000024:                                              \n"
		"mtc1            $at,$f8                                \n"
		"nop                                                    \n"
		"swc1            $f8,360($s0)                           \n"
		".L000025:                                              \n"
		"lw              $ra,28($sp)                            \n"
		".L000023:                                              \n"
		"lw              $s0,24($sp)                            \n"
		"addiu           $sp,$sp,48                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
