void data_809E9560(entity_t* en, z64_global_t* gl) /* 1 internal, 7 external, 94 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809E9560: \n"
	);
	asm(
		"addiu           $sp,$sp,-80                            \n"
		"sw              $s1,56($sp)                            \n"
		"or              $s1,$a1,$zero                          \n"
		"sw              $ra,60($sp)                            \n"
		"sw              $s0,52($sp)                            \n"
		"lui             $a1,%hi(data_809EABA4)                 \n"
		"or              $s0,$a0,$zero                          \n"
		"jal             0x800780DC                 \n"
		"addiu           $a1,$a1,%lo(data_809EABA4)             \n"
		"lh              $t6,28($s0)                            \n"
		"addiu           $at,$zero,10                           \n"
		"addiu           $a0,$s0,180                            \n"
		"bne             $t6,$at,.L000000                       \n"
		"addiu           $a1,$zero,0                            \n"
		"lw              $t7,4($s0)                             \n"
		"addiu           $at,$zero,-6                           \n"
		"and             $t8,$t7,$at                            \n"
		"beq             $zero,$zero,.L000001                   \n"
		"sw              $t8,4($s0)                             \n"
		".L000000:                                              \n"
		"lui             $a2,0x8003                             \n"
		"addiu           $a2,$a2,-18964                         \n"
		"jal             0x8002B1E0                 \n"
		"lui             $a3,0x420C                             \n"
		"lui             $a2,0x0600                             \n"
		"lui             $a3,0x0600                             \n"
		"addiu           $t9,$s0,412                            \n"
		"addiu           $t0,$s0,562                            \n"
		"addiu           $t1,$zero,25                           \n"
		"sw              $t1,24($sp)                            \n"
		"sw              $t0,20($sp)                            \n"
		"sw              $t9,16($sp)                            \n"
		"addiu           $a3,$a3,3692                           \n"
		"addiu           $a2,$a2,12904                          \n"
		"or              $a0,$s1,$zero                          \n"
		"jal             0x800A457C                 \n"
		"addiu           $a1,$s0,332                            \n"
		"addiu           $a1,$s0,712                            \n"
		"sw              $a1,68($sp)                            \n"
		"jal             0x8005C364                 \n"
		"or              $a0,$s1,$zero                          \n"
		"lui             $a3,%hi(data_809EAB50)                 \n"
		"lw              $a1,68($sp)                            \n"
		"addiu           $a3,$a3,%lo(data_809EAB50)             \n"
		"or              $a0,$s1,$zero                          \n"
		"jal             0x8005C4AC                 \n"
		"or              $a2,$s0,$zero                          \n"
		"lui             $a1,%hi(data_809EAB84)                 \n"
		"lui             $a2,%hi(data_809EAB7C)                 \n"
		"addiu           $a2,$a2,%lo(data_809EAB7C)             \n"
		"addiu           $a1,$a1,%lo(data_809EAB84)             \n"
		"jal             0x80061ED4                 \n"
		"addiu           $a0,$s0,152                            \n"
		"lh              $t2,28($s0)                            \n"
		"lh              $t5,28($s0)                            \n"
		"addiu           $at,$zero,255                          \n"
		"sra             $t3,$t2,8                              \n"
		"andi            $t4,$t3,0xff                           \n"
		"sh              $t4,410($s0)                           \n"
		"lh              $v0,410($s0)                           \n"
		"andi            $t6,$t5,0xff                           \n"
		"sh              $t6,28($s0)                            \n"
		"beq             $v0,$at,.L000002                       \n"
		"addiu           $t7,$zero,1                            \n"
		"bne             $v0,$zero,.L000003                     \n"
		"nop                                                    \n"
		".L000002:                                              \n"
		"sh              $t7,410($s0)                           \n"
		".L000003:                                              \n"
		"jal             func_809E96FC                          \n"
		"or              $a0,$s0,$zero                          \n"
		"lwc1            $f4,36($s0)                            \n"
		"addiu           $t9,$zero,10                           \n"
		"addiu           $a0,$s1,7204                           \n"
		"swc1            $f4,16($sp)                            \n"
		"lwc1            $f6,40($s0)                            \n"
		"or              $a1,$s0,$zero                          \n"
		"or              $a2,$s1,$zero                          \n"
		"swc1            $f6,20($sp)                            \n"
		"lwc1            $f8,44($s0)                            \n"
		"sw              $zero,28($sp)                          \n"
		"addiu           $a3,$zero,96                           \n"
		"swc1            $f8,24($sp)                            \n"
		"lh              $t8,50($s0)                            \n"
		"sw              $t9,40($sp)                            \n"
		"sw              $zero,36($sp)                          \n"
		"jal             0x80032458                 \n"
		"sw              $t8,32($sp)                            \n"
		".L000001:                                              \n"
		"lw              $ra,60($sp)                            \n"
		"lw              $s0,52($sp)                            \n"
		"lw              $s1,56($sp)                            \n"
		"jr              $ra                                    \n"
		"addiu           $sp,$sp,80                             \n"
	);
}
