void data_809E9F6C(entity_t* en, z64_global_t* gl) /* 1 internal, 8 external, 90 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809E9F6C: \n"
	);
	asm(
		"addiu           $sp,$sp,-72                            \n"
		"sw              $s0,48($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,52($sp)                            \n"
		"sw              $a1,76($sp)                            \n"
		"lh              $a1,138($s0)                           \n"
		"addiu           $a0,$a0,182                            \n"
		"addiu           $a2,$zero,2                            \n"
		"jal             0x800787BC                 \n"
		"addiu           $a3,$zero,3640                         \n"
		"addiu           $a0,$s0,332                            \n"
		"jal             0x800A49FC                 \n"
		"sw              $a0,56($sp)                            \n"
		"beq             $v0,$zero,.L000035                     \n"
		"lw              $a0,56($sp)                            \n"
		"jal             func_809E9800                          \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000036                   \n"
		"lw              $ra,52($sp)                            \n"
		".L000035:                                              \n"
		"jal             0x800A56C8                 \n"
		"lui             $a1,0x40C0                             \n"
		"beql            $v0,$zero,.L000037                     \n"
		"lh              $t9,406($s0)                           \n"
		"jal             0x80077870                 \n"
		"lh              $a0,182($s0)                           \n"
		"lui             $at,0x41B8                             \n"
		"mtc1            $at,$f4                                \n"
		"lwc1            $f8,36($s0)                            \n"
		"lui             $at,0x4140                             \n"
		"mul.s           $f6,$f0,$f4                            \n"
		"mtc1            $at,$f18                               \n"
		"add.s           $f10,$f6,$f8                           \n"
		"swc1            $f10,60($sp)                           \n"
		"lwc1            $f16,40($s0)                           \n"
		"add.s           $f4,$f16,$f18                          \n"
		"swc1            $f4,64($sp)                            \n"
		"jal             0x80077834                 \n"
		"lh              $a0,182($s0)                           \n"
		"lui             $at,0x41B8                             \n"
		"mtc1            $at,$f6                                \n"
		"lwc1            $f10,44($s0)                           \n"
		"lwc1            $f16,64($sp)                           \n"
		"mul.s           $f8,$f0,$f6                            \n"
		"lw              $a1,76($sp)                            \n"
		"swc1            $f16,16($sp)                           \n"
		"addiu           $a2,$zero,403                          \n"
		"lw              $a3,60($sp)                            \n"
		"addiu           $a0,$a1,7204                           \n"
		"add.s           $f2,$f8,$f10                           \n"
		"swc1            $f2,20($sp)                            \n"
		"lh              $t6,180($s0)                           \n"
		"sw              $t6,24($sp)                            \n"
		"lh              $t7,182($s0)                           \n"
		"sw              $t7,28($sp)                            \n"
		"lh              $t8,184($s0)                           \n"
		"sw              $zero,36($sp)                          \n"
		"jal             0x80031F50                 \n"
		"sw              $t8,32($sp)                            \n"
		"beq             $v0,$zero,.L000038                     \n"
		"or              $a0,$s0,$zero                          \n"
		"jal             0x8002F828                 \n"
		"addiu           $a1,$zero,14462                        \n"
		"beq             $zero,$zero,.L000036                   \n"
		"lw              $ra,52($sp)                            \n"
		"lh              $t9,406($s0)                           \n"
		".L000037:                                              \n"
		"lw              $a0,56($sp)                            \n"
		"slti            $at,$t9,2                              \n"
		"bnel            $at,$zero,.L000036                     \n"
		"lw              $ra,52($sp)                            \n"
		"jal             0x800A56C8                 \n"
		"lui             $a1,0x4140                             \n"
		"beq             $v0,$zero,.L000038                     \n"
		"lw              $a0,56($sp)                            \n"
		"lui             $a1,0x0600                             \n"
		"addiu           $a1,$a1,452                            \n"
		"jal             0x800A5240                 \n"
		"lui             $a2,0xC040                             \n"
		"lh              $v0,406($s0)                           \n"
		"beq             $v0,$zero,.L000038                     \n"
		"addiu           $t0,$v0,-1                             \n"
		"sh              $t0,406($s0)                           \n"
		".L000038:                                              \n"
		"lw              $ra,52($sp)                            \n"
		".L000036:                                              \n"
		"lw              $s0,48($sp)                            \n"
		"addiu           $sp,$sp,72                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
