void data_809EA5B0(entity_t* en, z64_global_t* gl) /* 0 internal, 6 external, 89 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809EA5B0: \n"
	);
	asm(
		"addiu           $sp,$sp,-104                           \n"
		"sw              $s0,68($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,76($sp)                            \n"
		"sw              $s1,72($sp)                            \n"
		"or              $s1,$a1,$zero                          \n"
		"jal             0x800A49FC                 \n"
		"addiu           $a0,$a0,332                            \n"
		"beq             $v0,$zero,.L000067                     \n"
		"lui             $a2,%hi(data_809EABB0)                 \n"
		"lwc1            $f4,36($s0)                            \n"
		"lui             $at,0x4190                             \n"
		"mtc1            $at,$f8                                \n"
		"swc1            $f4,88($sp)                            \n"
		"lwc1            $f6,40($s0)                            \n"
		"addiu           $t6,$zero,200                          \n"
		"addiu           $a2,$a2,%lo(data_809EABB0)             \n"
		"add.s           $f10,$f6,$f8                           \n"
		"addiu           $t7,$zero,255                          \n"
		"addiu           $t8,$zero,255                          \n"
		"addiu           $t9,$zero,255                          \n"
		"swc1            $f10,92($sp)                           \n"
		"lwc1            $f16,44($s0)                           \n"
		"sw              $t6,16($sp)                            \n"
		"addiu           $t6,$zero,1                            \n"
		"addiu           $t0,$zero,255                          \n"
		"addiu           $t1,$zero,150                          \n"
		"addiu           $t2,$zero,150                          \n"
		"addiu           $t3,$zero,150                          \n"
		"addiu           $t4,$zero,1                            \n"
		"addiu           $t5,$zero,13                           \n"
		"sw              $t5,56($sp)                            \n"
		"sw              $t4,52($sp)                            \n"
		"sw              $t3,48($sp)                            \n"
		"sw              $t2,44($sp)                            \n"
		"sw              $t1,40($sp)                            \n"
		"sw              $t0,36($sp)                            \n"
		"sw              $t6,60($sp)                            \n"
		"sw              $t9,32($sp)                            \n"
		"sw              $t8,28($sp)                            \n"
		"sw              $t7,24($sp)                            \n"
		"sw              $zero,20($sp)                          \n"
		"or              $a3,$a2,$zero                          \n"
		"or              $a0,$s1,$zero                          \n"
		"addiu           $a1,$sp,88                             \n"
		"jal             0x8002A6B8                 \n"
		"swc1            $f16,96($sp)                           \n"
		"lwc1            $f18,40($s0)                           \n"
		"lui             $at,0x4120                             \n"
		"mtc1            $at,$f4                                \n"
		"addiu           $t7,$zero,12                           \n"
		"addiu           $t8,$zero,3                            \n"
		"add.s           $f6,$f18,$f4                           \n"
		"addiu           $t9,$zero,15                           \n"
		"addiu           $t0,$zero,-1                           \n"
		"addiu           $t1,$zero,10                           \n"
		"swc1            $f6,92($sp)                            \n"
		"sw              $t1,32($sp)                            \n"
		"sw              $t0,28($sp)                            \n"
		"sw              $t9,24($sp)                            \n"
		"sw              $t8,20($sp)                            \n"
		"sw              $t7,16($sp)                            \n"
		"sw              $zero,36($sp)                          \n"
		"or              $a0,$s1,$zero                          \n"
		"addiu           $a1,$sp,88                             \n"
		"lui             $a2,0x4040                             \n"
		"jal             0x800297A4                 \n"
		"or              $a3,$zero,$zero                        \n"
		"or              $a0,$s1,$zero                          \n"
		"or              $a1,$s0,$zero                          \n"
		"addiu           $a2,$s0,36                             \n"
		"jal             0x8001F940                 \n"
		"addiu           $a3,$zero,48                           \n"
		"lw              $a2,284($s0)                           \n"
		"or              $a0,$s1,$zero                          \n"
		"addiu           $a1,$s1,7204                           \n"
		"beq             $a2,$zero,.L000068                     \n"
		"nop                                                    \n"
		"jal             0x80033748                 \n"
		"addiu           $a3,$zero,6                            \n"
		".L000068:                                              \n"
		"jal             0x8002D570                 \n"
		"or              $a0,$s0,$zero                          \n"
		".L000067:                                              \n"
		"lw              $ra,76($sp)                            \n"
		"lw              $s0,68($sp)                            \n"
		"lw              $s1,72($sp)                            \n"
		"jr              $ra                                    \n"
		"addiu           $sp,$sp,104                            \n"
	);
}
