void data_809EA82C(entity_t* en, z64_global_t* gl) /* 1 internal, 7 external, 93 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809EA82C: \n"
	);
	asm(
		"addiu           $sp,$sp,-56                            \n"
		"sw              $ra,36($sp)                            \n"
		"sw              $s1,32($sp)                            \n"
		"sw              $s0,28($sp)                            \n"
		"lh              $t6,28($a0)                            \n"
		"addiu           $at,$zero,10                           \n"
		"or              $s0,$a0,$zero                          \n"
		"beq             $t6,$at,.L000076                       \n"
		"or              $s1,$a1,$zero                          \n"
		"jal             func_809EA70C                          \n"
		"nop                                                    \n"
		"lw              $t9,400($s0)                           \n"
		"or              $a0,$s0,$zero                          \n"
		"or              $a1,$s1,$zero                          \n"
		"jalr            $t9                                    \n"
		"nop                                                    \n"
		"jal             0x8002D8E0                 \n"
		"or              $a0,$s0,$zero                          \n"
		"lh              $t7,776($s0)                           \n"
		"lh              $t8,778($s0)                           \n"
		"addiu           $t0,$zero,29                           \n"
		"mtc1            $t7,$f4                                \n"
		"mtc1            $t8,$f6                                \n"
		"sw              $t0,20($sp)                            \n"
		"cvt.s.w         $f4,$f4                                \n"
		"or              $a0,$s1,$zero                          \n"
		"or              $a1,$s0,$zero                          \n"
		"lui             $a2,0x41A0                             \n"
		"cvt.s.w         $f8,$f6                                \n"
		"mfc1            $a3,$f4                                \n"
		"jal             0x8002E4B4                 \n"
		"swc1            $f8,16($sp)                            \n"
		"addiu           $a1,$s0,712                            \n"
		"sw              $a1,40($sp)                            \n"
		"jal             0x800626DC                 \n"
		"or              $a0,$s0,$zero                          \n"
		"lbu             $t1,729($s0)                           \n"
		"lui             $at,0x0001                             \n"
		"ori             $at,$at,0x1e60                         \n"
		"andi            $t2,$t1,0x1                            \n"
		"beq             $t2,$zero,.L000077                     \n"
		"or              $a0,$s1,$zero                          \n"
		"addu            $a1,$s1,$at                            \n"
		"jal             0x8005D9F4                 \n"
		"lw              $a2,40($sp)                            \n"
		".L000077:                                              \n"
		"lui             $at,0x0001                             \n"
		"ori             $at,$at,0x1e60                         \n"
		"addu            $a1,$s1,$at                            \n"
		"or              $a0,$s1,$zero                          \n"
		"jal             0x8005DC4C                 \n"
		"lw              $a2,40($sp)                            \n"
		"lw              $v1,400($s0)                           \n"
		"lui             $t3,%hi(data_809E9B98)                 \n"
		"addiu           $t3,$t3,%lo(data_809E9B98)             \n"
		"bne             $t3,$v1,.L000078                       \n"
		"lui             $t4,%hi(data_809EA0C4)                 \n"
		"or              $a0,$s0,$zero                          \n"
		"jal             0x8002D5B8                 \n"
		"lw              $a1,356($s0)                           \n"
		"beq             $zero,$zero,.L000079                   \n"
		"lw              $ra,36($sp)                            \n"
		".L000078:                                              \n"
		"addiu           $t4,$t4,%lo(data_809EA0C4)             \n"
		"bne             $t4,$v1,.L000080                       \n"
		"or              $a0,$s0,$zero                          \n"
		"lui             $a0,0x0600                             \n"
		"jal             0x800A2000                 \n"
		"addiu           $a0,$a0,1240                           \n"
		"lui             $at,0x41A0                             \n"
		"mtc1            $at,$f0                                \n"
		"lwc1            $f10,356($s0)                          \n"
		"mtc1            $v0,$f18                               \n"
		"or              $a0,$s0,$zero                          \n"
		"mul.s           $f16,$f10,$f0                          \n"
		"cvt.s.w         $f4,$f18                               \n"
		"div.s           $f6,$f16,$f4                           \n"
		"sub.s           $f8,$f0,$f6                            \n"
		"mfc1            $a1,$f8                                \n"
		"jal             0x8002D5B8                 \n"
		"nop                                                    \n"
		"beq             $zero,$zero,.L000079                   \n"
		"lw              $ra,36($sp)                            \n"
		".L000080:                                              \n"
		"jal             0x8002D5B8                 \n"
		"lui             $a1,0x41A0                             \n"
		".L000076:                                              \n"
		"lw              $ra,36($sp)                            \n"
		".L000079:                                              \n"
		"lw              $s0,28($sp)                            \n"
		"lw              $s1,32($sp)                            \n"
		"jr              $ra                                    \n"
		"addiu           $sp,$sp,56                             \n"
	);
}
