void func_809E9AB4(entity_t* en) /* 0 internal, 4 external, 37 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_809E9AB4: \n"
	);
	asm(
		"addiu           $sp,$sp,-40                            \n"
		"sw              $s0,32($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,36($sp)                            \n"
		"lui             $a1,0x0600                             \n"
		"addiu           $a1,$a1,872                            \n"
		"addiu           $a0,$a0,332                            \n"
		"jal             0x800A534C                 \n"
		"lui             $a2,0xC040                             \n"
		"mtc1            $zero,$f4                              \n"
		"lui             $t7,%hi(data_809EA534)                 \n"
		"addiu           $t6,$zero,5                            \n"
		"addiu           $t7,$t7,%lo(data_809EA534)             \n"
		"sh              $t6,406($s0)                           \n"
		"sw              $t7,400($s0)                           \n"
		"or              $a0,$s0,$zero                          \n"
		"addiu           $a1,$zero,14494                        \n"
		"jal             0x8002F828                 \n"
		"swc1            $f4,104($s0)                           \n"
		"lui             $a0,0x0600                             \n"
		"jal             0x800A2000                 \n"
		"addiu           $a0,$a0,872                            \n"
		"lh              $t8,406($s0)                           \n"
		"or              $a0,$s0,$zero                          \n"
		"or              $a1,$zero,$zero                        \n"
		"multu           $v0,$t8                                \n"
		"addiu           $a2,$zero,255                          \n"
		"or              $a3,$zero,$zero                        \n"
		"mflo            $t9                                    \n"
		"sw              $t9,16($sp)                            \n"
		"jal             0x8003426C                 \n"
		"nop                                                    \n"
		"lw              $ra,36($sp)                            \n"
		"lw              $s0,32($sp)                            \n"
		"addiu           $sp,$sp,40                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
