void func_809EA70C(entity_t* en, z64_global_t* gl) /* 3 internal, 4 external, 79 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_809EA70C: \n"
	);
	asm(
		"addiu           $sp,$sp,-40                            \n"
		"sw              $ra,36($sp)                            \n"
		"sw              $s0,32($sp)                            \n"
		"sw              $a1,44($sp)                            \n"
		"lbu             $v0,729($a0)                           \n"
		"or              $s0,$a0,$zero                          \n"
		"addiu           $a1,$s0,736                            \n"
		"andi            $t6,$v0,0x2                            \n"
		"beq             $t6,$zero,.L000069                     \n"
		"andi            $t7,$v0,0xfffd                         \n"
		"sb              $t7,729($a0)                           \n"
		"jal             0x80035650                 \n"
		"addiu           $a2,$zero,1                            \n"
		"lbu             $t8,174($s0)                           \n"
		"addiu           $at,$zero,50                           \n"
		"bne             $t8,$at,.L000070                       \n"
		"nop                                                    \n"
		"lbu             $v0,177($s0)                           \n"
		"addiu           $at,$zero,1                            \n"
		"bne             $v0,$zero,.L000071                     \n"
		"nop                                                    \n"
		"lbu             $t9,176($s0)                           \n"
		"beql            $t9,$zero,.L000072                     \n"
		"lw              $ra,36($sp)                            \n"
		".L000071:                                              \n"
		"beq             $v0,$at,.L000073                       \n"
		"addiu           $at,$zero,2                            \n"
		"bne             $v0,$at,.L000074                       \n"
		"lw              $a0,44($sp)                            \n"
		"addiu           $t0,$zero,50                           \n"
		"sw              $t0,16($sp)                            \n"
		"or              $a1,$s0,$zero                          \n"
		"addiu           $a2,$s0,36                             \n"
		"jal             0x8002A65C                 \n"
		"addiu           $a3,$zero,40                           \n"
		".L000074:                                              \n"
		"jal             func_809E99D8                          \n"
		"or              $a0,$s0,$zero                          \n"
		"jal             0x80035628                 \n"
		"or              $a0,$s0,$zero                          \n"
		"bne             $v0,$zero,.L000075                     \n"
		"lw              $a0,44($sp)                            \n"
		"jal             0x80032C7C                 \n"
		"or              $a1,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000072                   \n"
		"lw              $ra,36($sp)                            \n"
		".L000073:                                              \n"
		"lw              $t2,400($s0)                           \n"
		"lui             $t1,%hi(data_809EA534)                 \n"
		"addiu           $t1,$t1,%lo(data_809EA534)             \n"
		"beql            $t1,$t2,.L000072                       \n"
		"lw              $ra,36($sp)                            \n"
		"jal             func_809E9AB4                          \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000072                   \n"
		"lw              $ra,36($sp)                            \n"
		".L000070:                                              \n"
		"jal             func_809E98B4                          \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000072                   \n"
		"lw              $ra,36($sp)                            \n"
		".L000069:                                              \n"
		"lbu             $t3,174($s0)                           \n"
		"addiu           $at,$zero,255                          \n"
		"lw              $t4,44($sp)                            \n"
		"bnel            $t3,$at,.L000072                       \n"
		"lw              $ra,36($sp)                            \n"
		"lbu             $t5,7206($t4)                          \n"
		"beql            $t5,$zero,.L000072                     \n"
		"lw              $ra,36($sp)                            \n"
		"jal             func_809E98B4                          \n"
		"or              $a0,$s0,$zero                          \n"
		".L000075:                                              \n"
		"lw              $ra,36($sp)                            \n"
		".L000072:                                              \n"
		"lw              $s0,32($sp)                            \n"
		"addiu           $sp,$sp,40                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
