void func_809E99D8(entity_t* en) /* 0 internal, 5 external, 57 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_809E99D8: \n"
	);
	asm(
		"addiu           $sp,$sp,-40                            \n"
		"sw              $s0,32($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,36($sp)                            \n"
		"lui             $a1,0x0600                             \n"
		"addiu           $a1,$a1,872                            \n"
		"addiu           $a0,$a0,332                            \n"
		"jal             0x800A5240                 \n"
		"lui             $a2,0xC040                             \n"
		"lw              $t6,772($s0)                           \n"
		"lui             $at,0x0001                             \n"
		"ori             $at,$at,0xf824                         \n"
		"lw              $t7,0($t6)                             \n"
		"or              $a0,$s0,$zero                          \n"
		"and             $t8,$t7,$at                            \n"
		"beq             $t8,$zero,.L000008                     \n"
		"nop                                                    \n"
		"lw              $t9,720($s0)                           \n"
		"lh              $t0,50($t9)                            \n"
		"beq             $zero,$zero,.L000009                   \n"
		"sh              $t0,50($s0)                            \n"
		".L000008:                                              \n"
		"jal             0x8002DA78                 \n"
		"lw              $a1,720($s0)                           \n"
		"ori             $at,$zero,0x8000                       \n"
		"addu            $t1,$v0,$at                            \n"
		"sh              $t1,50($s0)                            \n"
		".L000009:                                              \n"
		"lbu             $t2,729($s0)                           \n"
		"lui             $at,0x4120                             \n"
		"mtc1            $at,$f4                                \n"
		"lui             $t4,%hi(data_809EA4E8)                 \n"
		"addiu           $t4,$t4,%lo(data_809EA4E8)             \n"
		"andi            $t3,$t2,0xfffe                         \n"
		"sb              $t3,729($s0)                           \n"
		"sw              $t4,400($s0)                           \n"
		"or              $a0,$s0,$zero                          \n"
		"addiu           $a1,$zero,14464                        \n"
		"jal             0x8002F828                 \n"
		"swc1            $f4,104($s0)                           \n"
		"or              $a0,$s0,$zero                          \n"
		"jal             0x8002F828                 \n"
		"addiu           $a1,$zero,14651                        \n"
		"lui             $a0,0x0600                             \n"
		"jal             0x800A2000                 \n"
		"addiu           $a0,$a0,872                            \n"
		"or              $a0,$s0,$zero                          \n"
		"addiu           $a1,$zero,16384                        \n"
		"addiu           $a2,$zero,255                          \n"
		"or              $a3,$zero,$zero                        \n"
		"jal             0x8003426C                 \n"
		"sw              $v0,16($sp)                            \n"
		"lw              $ra,36($sp)                            \n"
		"lw              $s0,32($sp)                            \n"
		"addiu           $sp,$sp,40                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
