[-] zzcovl v0.01 r0  <z64.me> (based on zovldis by Kjartan Skjervoy <kskjer@gmail.com> and Rhett Osborne <rmo@spinout182.com>)
[-] Built: Jul 27 2019 14:55:38
[-] Input file: En_Dekunuts-nzle.zovl
[-] Start address 0x809E9560.
#include <z64ovl/oot/debug.h>

#define OBJ_ID 74

typedef struct {
	z64_actor_t actor;
	uint8_t unknown[472];
} entity_t; /* 0314 */


/*** function prototypes ***/
void data_809E96C8(void); /* 0 internal, 1 external, 14 lines */
void func_809E9770(void); /* 0 internal, 1 external, 18 lines */
void func_809E97B8(void); /* 0 internal, 1 external, 18 lines */
void func_809E9920(void); /* 0 internal, 1 external, 22 lines */
void func_809E9978(void); /* 0 internal, 1 external, 25 lines */
void func_809E9800(void); /* 0 internal, 1 external, 28 lines */
void data_809EA98C(void); /* 0 internal, 1 external, 84 lines */
void func_809E9868(void); /* 0 internal, 2 external, 19 lines */
void func_809E9B48(void); /* 0 internal, 2 external, 20 lines */
void func_809E98B4(void); /* 0 internal, 2 external, 27 lines */
void data_809EAAC4(void); /* 0 internal, 2 external, 29 lines */
void func_809E96FC(void); /* 0 internal, 3 external, 29 lines */
void func_809E9AB4(void); /* 0 internal, 4 external, 37 lines */
void func_809E99D8(void); /* 0 internal, 5 external, 57 lines */
void data_809EA5B0(void); /* 0 internal, 6 external, 89 lines */
void data_809EA4E8(void); /* 1 internal, 2 external, 20 lines */
void data_809EA1D8(void); /* 1 internal, 2 external, 27 lines */
void data_809EA480(void); /* 1 internal, 2 external, 28 lines */
void data_809E9DFC(void); /* 1 internal, 2 external, 36 lines */
void data_809E9560(void); /* 1 internal, 7 external, 94 lines */
void data_809EA0C4(void); /* 1 internal, 3 external, 75 lines */
void data_809E9F6C(void); /* 1 internal, 8 external, 90 lines */
void data_809EA534(void); /* 1 internal, 3 external, 35 lines */
void data_809E9E80(void); /* 2 internal, 3 external, 65 lines */
void data_809EA82C(void); /* 1 internal, 7 external, 93 lines */
void data_809EA240(void); /* 2 internal, 7 external, 158 lines */
void data_809E9B98(void); /* 3 internal, 3 external, 169 lines */
void func_809EA70C(void); /* 3 internal, 4 external, 79 lines */


/*** variables ***/
const uint32_t data_809EAB50[] =
{
	0x06000939,
	0x10010000,
	0x00000000,
	0x00000000,
	0x00000000,
	0xFFCFFFFF,
	0x00000000,
	0x00010100,
	0x00120020,
	0x00000000,
	0x00000000
};
const uint32_t data_809EAB7C[] =
{
	0x01000012,
	0x0020FF00
};
const uint32_t data_809EAB84[] =
{
	0x10020102,
	0x01020202,
	0x01020424,
	0x02020202,
	0x02240000,
	0x00000104,
	0x02020804,
	0x00000400
};
const uint32_t data_809EABA4[] =
{
	0x8917004D,
	0xB06CFFFF,
	0x304C0A28
};
const uint32_t data_809EABB0[] =
{
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
const uint32_t data_809EABC0[] =
{
	0x3DAA9930
};
const uint32_t data_809EABC4[] =
{
	0x3DEF0069
};
const uint32_t data_809EABC8[] =
{
	0x3FD9999A
};
const uint32_t data_809EABCC[] =
{
	0x3F333333
};
const uint32_t data_809EABD0[] =
{
	0x3E2AB367,
	0x00000000,
	0x00000000,
	0x00000000
};


/*** functions ***/
void data_809E96C8(void) /* 0 internal, 1 external, 14 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809E96C8: \n"
	);
	asm(
		"addiu           $sp,$sp,-24                            \n"
		"sw              $ra,20($sp)                            \n"
		"lh              $t6,28($a0)                            \n"
		"or              $a2,$a0,$zero                          \n"
		"addiu           $at,$zero,10                           \n"
		"beq             $t6,$at,.L000004                       \n"
		"or              $a0,$a1,$zero                          \n"
		"jal             external_func_8005C3AC                 \n"
		"addiu           $a1,$a2,712                            \n"
		".L000004:                                              \n"
		"lw              $ra,20($sp)                            \n"
		"addiu           $sp,$sp,24                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void func_809E9770(void) /* 0 internal, 1 external, 18 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_809E9770: \n"
	);
	asm(
		"addiu           $sp,$sp,-24                            \n"
		"sw              $ra,20($sp)                            \n"
		"or              $a2,$a0,$zero                          \n"
		"lui             $a1,0x0600                             \n"
		"addiu           $a1,$a1,2800                           \n"
		"sw              $a2,24($sp)                            \n"
		"jal             external_func_800A52F8                 \n"
		"addiu           $a0,$a0,332                            \n"
		"lw              $a2,24($sp)                            \n"
		"lui             $t7,%hi(data_809E9DFC)                 \n"
		"addiu           $t6,$zero,2                            \n"
		"addiu           $t7,$t7,%lo(data_809E9DFC)             \n"
		"sh              $t6,406($a2)                           \n"
		"sw              $t7,400($a2)                           \n"
		"lw              $ra,20($sp)                            \n"
		"addiu           $sp,$sp,24                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void func_809E97B8(void) /* 0 internal, 1 external, 18 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_809E97B8: \n"
	);
	asm(
		"addiu           $sp,$sp,-24                            \n"
		"sw              $ra,20($sp)                            \n"
		"or              $a2,$a0,$zero                          \n"
		"lui             $a1,0x0600                             \n"
		"addiu           $a1,$a1,452                            \n"
		"sw              $a2,24($sp)                            \n"
		"jal             external_func_800A51E8                 \n"
		"addiu           $a0,$a0,332                            \n"
		"lw              $a2,24($sp)                            \n"
		"lui             $t7,%hi(data_809E9F6C)                 \n"
		"addiu           $t7,$t7,%lo(data_809E9F6C)             \n"
		"lh              $t6,410($a2)                           \n"
		"sw              $t7,400($a2)                           \n"
		"sh              $t6,406($a2)                           \n"
		"lw              $ra,20($sp)                            \n"
		"addiu           $sp,$sp,24                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void func_809E9920(void) /* 0 internal, 1 external, 22 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_809E9920: \n"
	);
	asm(
		"addiu           $sp,$sp,-24                            \n"
		"sw              $ra,20($sp)                            \n"
		"or              $a2,$a0,$zero                          \n"
		"lui             $a1,0x0600                             \n"
		"addiu           $a1,$a1,13904                          \n"
		"sw              $a2,24($sp)                            \n"
		"jal             external_func_800A52F8                 \n"
		"addiu           $a0,$a0,332                            \n"
		"lw              $a2,24($sp)                            \n"
		"lui             $t9,%hi(data_809EA240)                 \n"
		"addiu           $t6,$zero,2                            \n"
		"lbu             $t7,729($a2)                           \n"
		"addiu           $t9,$t9,%lo(data_809EA240)             \n"
		"sh              $t6,406($a2)                           \n"
		"ori             $t8,$t7,0x1                            \n"
		"sb              $zero,404($a2)                         \n"
		"sb              $t8,729($a2)                           \n"
		"sw              $t9,400($a2)                           \n"
		"lw              $ra,20($sp)                            \n"
		"addiu           $sp,$sp,24                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void func_809E9978(void) /* 0 internal, 1 external, 25 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_809E9978: \n"
	);
	asm(
		"addiu           $sp,$sp,-24                            \n"
		"sw              $ra,20($sp)                            \n"
		"or              $a2,$a0,$zero                          \n"
		"lui             $a1,0x0600                             \n"
		"addiu           $a1,$a1,4132                           \n"
		"sw              $a2,24($sp)                            \n"
		"jal             external_func_800A52F8                 \n"
		"addiu           $a0,$a0,332                            \n"
		"lw              $a2,24($sp)                            \n"
		"mtc1            $zero,$f4                              \n"
		"addiu           $t6,$zero,3                            \n"
		"lbu             $v0,405($a2)                           \n"
		"lui             $t8,%hi(data_809EA480)                 \n"
		"sh              $t6,406($a2)                           \n"
		"beq             $v0,$zero,.L000007                     \n"
		"swc1            $f4,104($a2)                           \n"
		"addiu           $t7,$v0,-1                             \n"
		"sb              $t7,405($a2)                           \n"
		".L000007:                                              \n"
		"addiu           $t8,$t8,%lo(data_809EA480)             \n"
		"sw              $t8,400($a2)                           \n"
		"lw              $ra,20($sp)                            \n"
		"addiu           $sp,$sp,24                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void func_809E9800(void) /* 0 internal, 1 external, 28 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_809E9800: \n"
	);
	asm(
		"addiu           $sp,$sp,-24                            \n"
		"sw              $ra,20($sp)                            \n"
		"or              $a3,$a0,$zero                          \n"
		"lui             $a1,0x0600                             \n"
		"addiu           $a1,$a1,3692                           \n"
		"sw              $a3,24($sp)                            \n"
		"addiu           $a0,$a0,332                            \n"
		"jal             external_func_800A534C                 \n"
		"lui             $a2,0xC040                             \n"
		"lw              $a3,24($sp)                            \n"
		"lui             $t6,%hi(data_809E9F6C)                 \n"
		"addiu           $t6,$t6,%lo(data_809E9F6C)             \n"
		"lw              $t7,400($a3)                           \n"
		"lui             $t0,%hi(data_809E9E80)                 \n"
		"addiu           $t9,$zero,1                            \n"
		"bne             $t6,$t7,.L000005                       \n"
		"addiu           $t0,$t0,%lo(data_809E9E80)             \n"
		"addiu           $t8,$zero,4098                         \n"
		"beq             $zero,$zero,.L000006                   \n"
		"sh              $t8,406($a3)                           \n"
		".L000005:                                              \n"
		"sh              $t9,406($a3)                           \n"
		".L000006:                                              \n"
		"sw              $t0,400($a3)                           \n"
		"lw              $ra,20($sp)                            \n"
		"addiu           $sp,$sp,24                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void data_809EA98C(void) /* 0 internal, 1 external, 84 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809EA98C: \n"
	);
	asm(
		"addiu           $sp,$sp,-24                            \n"
		"addiu           $at,$zero,7                            \n"
		"sw              $ra,20($sp)                            \n"
		"sw              $a0,24($sp)                            \n"
		"sw              $a2,32($sp)                            \n"
		"bne             $a1,$at,.L000081                       \n"
		"sw              $a3,36($sp)                            \n"
		"lw              $v0,44($sp)                            \n"
		"lui             $t6,%hi(data_809E9F6C)                 \n"
		"addiu           $t6,$t6,%lo(data_809E9F6C)             \n"
		"lw              $t7,400($v0)                           \n"
		"lui             $at,0x40C0                             \n"
		"bnel            $t6,$t7,.L000082                       \n"
		"or              $v0,$zero,$zero                        \n"
		"mtc1            $at,$f18                               \n"
		"lwc1            $f0,356($v0)                           \n"
		"lui             $at,0x40E0                             \n"
		"c.le.s          $f0,$f18                               \n"
		"nop                                                    \n"
		"bc1fl           .L000083                               \n"
		"mtc1            $at,$f2                                \n"
		"lui             $at,0x3F80                             \n"
		"mtc1            $at,$f18                               \n"
		"lui             $at,%hi(data_809EABC0)                 \n"
		"lwc1            $f4,%lo(data_809EABC0)($at)            \n"
		"lui             $at,%hi(data_809EABC4)                 \n"
		"lwc1            $f8,%lo(data_809EABC4)($at)            \n"
		"mul.s           $f6,$f0,$f4                            \n"
		"nop                                                    \n"
		"mul.s           $f10,$f0,$f8                           \n"
		"sub.s           $f12,$f18,$f6                          \n"
		"add.s           $f14,$f10,$f18                         \n"
		"beq             $zero,$zero,.L000084                   \n"
		"mov.s           $f16,$f14                              \n"
		"mtc1            $at,$f2                                \n"
		".L000083:                                              \n"
		"lui             $at,0x4120                             \n"
		"c.le.s          $f0,$f2                                \n"
		"nop                                                    \n"
		"bc1fl           .L000085                               \n"
		"mtc1            $at,$f4                                \n"
		"lui             $at,0x3F00                             \n"
		"mtc1            $at,$f4                                \n"
		"lui             $at,%hi(data_809EABC8)                 \n"
		"lwc1            $f6,%lo(data_809EABC8)($at)            \n"
		"sub.s           $f0,$f0,$f18                           \n"
		"lui             $at,%hi(data_809EABCC)                 \n"
		"lwc1            $f8,%lo(data_809EABCC)($at)            \n"
		"add.s           $f12,$f4,$f0                           \n"
		"mul.s           $f10,$f0,$f8                           \n"
		"sub.s           $f14,$f6,$f10                          \n"
		"beq             $zero,$zero,.L000084                   \n"
		"mov.s           $f16,$f14                              \n"
		"mtc1            $at,$f4                                \n"
		".L000085:                                              \n"
		"lui             $at,0x3F80                             \n"
		"c.le.s          $f0,$f4                                \n"
		"nop                                                    \n"
		"bc1f            .L000086                               \n"
		"nop                                                    \n"
		"mtc1            $at,$f14                               \n"
		"sub.s           $f8,$f0,$f2                            \n"
		"lui             $at,%hi(data_809EABD0)                 \n"
		"lwc1            $f6,%lo(data_809EABD0)($at)            \n"
		"lui             $at,0x3FC0                             \n"
		"mtc1            $at,$f4                                \n"
		"mul.s           $f10,$f8,$f6                           \n"
		"mov.s           $f16,$f14                              \n"
		"beq             $zero,$zero,.L000084                   \n"
		"sub.s           $f12,$f4,$f10                          \n"
		".L000086:                                              \n"
		"beq             $zero,$zero,.L000082                   \n"
		"or              $v0,$zero,$zero                        \n"
		".L000084:                                              \n"
		"mfc1            $a2,$f16                               \n"
		"jal             external_func_800D0A8C                 \n"
		"addiu           $a3,$zero,1                            \n"
		".L000081:                                              \n"
		"or              $v0,$zero,$zero                        \n"
		".L000082:                                              \n"
		"lw              $ra,20($sp)                            \n"
		"addiu           $sp,$sp,24                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void func_809E9868(void) /* 0 internal, 2 external, 19 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_809E9868: \n"
	);
	asm(
		"addiu           $sp,$sp,-24                            \n"
		"sw              $ra,20($sp)                            \n"
		"sw              $a0,24($sp)                            \n"
		"lui             $a1,0x0600                             \n"
		"addiu           $a1,$a1,1240                           \n"
		"addiu           $a0,$a0,332                            \n"
		"jal             external_func_800A5240                 \n"
		"lui             $a2,0xC0A0                             \n"
		"lw              $a0,24($sp)                            \n"
		"jal             external_func_8002F828                 \n"
		"addiu           $a1,$zero,14461                        \n"
		"lw              $t7,24($sp)                            \n"
		"lui             $t6,%hi(data_809EA0C4)                 \n"
		"addiu           $t6,$t6,%lo(data_809EA0C4)             \n"
		"sw              $t6,400($t7)                           \n"
		"lw              $ra,20($sp)                            \n"
		"addiu           $sp,$sp,24                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void func_809E9B48(void) /* 0 internal, 2 external, 20 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_809E9B48: \n"
	);
	asm(
		"addiu           $sp,$sp,-24                            \n"
		"sw              $ra,20($sp)                            \n"
		"or              $a2,$a0,$zero                          \n"
		"lui             $a1,0x0600                             \n"
		"addiu           $a1,$a1,1712                           \n"
		"sw              $a2,24($sp)                            \n"
		"jal             external_func_800A51E8                 \n"
		"addiu           $a0,$a0,332                            \n"
		"lw              $a0,24($sp)                            \n"
		"mtc1            $zero,$f4                              \n"
		"lui             $t6,%hi(data_809EA5B0)                 \n"
		"addiu           $t6,$t6,%lo(data_809EA5B0)             \n"
		"addiu           $a1,$zero,14465                        \n"
		"sw              $t6,400($a0)                           \n"
		"jal             external_func_8002F828                 \n"
		"swc1            $f4,104($a0)                           \n"
		"lw              $ra,20($sp)                            \n"
		"addiu           $sp,$sp,24                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void func_809E98B4(void) /* 0 internal, 2 external, 27 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_809E98B4: \n"
	);
	asm(
		"addiu           $sp,$sp,-24                            \n"
		"sw              $ra,20($sp)                            \n"
		"or              $a3,$a0,$zero                          \n"
		"lui             $a1,0x0600                             \n"
		"addiu           $a1,$a1,2244                           \n"
		"sw              $a3,24($sp)                            \n"
		"addiu           $a0,$a0,332                            \n"
		"jal             external_func_800A5240                 \n"
		"lui             $a2,0xC040                             \n"
		"lw              $a0,24($sp)                            \n"
		"addiu           $t6,$zero,37                           \n"
		"addiu           $t7,$zero,50                           \n"
		"addiu           $a1,$zero,14464                        \n"
		"sh              $t6,778($a0)                           \n"
		"jal             external_func_8002F828                 \n"
		"sb              $t7,174($a0)                           \n"
		"lw              $a3,24($sp)                            \n"
		"lui             $t0,%hi(data_809EA1D8)                 \n"
		"addiu           $t0,$t0,%lo(data_809EA1D8)             \n"
		"lbu             $t8,729($a3)                           \n"
		"sw              $t0,400($a3)                           \n"
		"andi            $t9,$t8,0xfffe                         \n"
		"sb              $t9,729($a3)                           \n"
		"lw              $ra,20($sp)                            \n"
		"addiu           $sp,$sp,24                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void data_809EAAC4(void) /* 0 internal, 2 external, 29 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809EAAC4: \n"
	);
	asm(
		"addiu           $sp,$sp,-32                            \n"
		"sw              $ra,28($sp)                            \n"
		"sw              $a0,32($sp)                            \n"
		"sw              $a1,36($sp)                            \n"
		"lh              $t7,28($a0)                            \n"
		"addiu           $at,$zero,10                           \n"
		"lw              $a0,36($sp)                            \n"
		"bne             $t7,$at,.L000087                       \n"
		"lw              $t8,32($sp)                            \n"
		"or              $a0,$a1,$zero                          \n"
		"lui             $a1,0x0600                             \n"
		"jal             external_func_80035260                 \n"
		"addiu           $a1,$a1,8856                           \n"
		"beq             $zero,$zero,.L000088                   \n"
		"lw              $ra,28($sp)                            \n"
		".L000087:                                              \n"
		"lw              $a1,336($t8)                           \n"
		"lw              $a2,364($t8)                           \n"
		"lui             $a3,%hi(data_809EA98C)                 \n"
		"addiu           $a3,$a3,%lo(data_809EA98C)             \n"
		"sw              $t8,20($sp)                            \n"
		"jal             external_func_800A15C8                 \n"
		"sw              $zero,16($sp)                          \n"
		"lw              $ra,28($sp)                            \n"
		".L000088:                                              \n"
		"addiu           $sp,$sp,32                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
		"nop                                                    \n"
	);
}
void func_809E96FC(void) /* 0 internal, 3 external, 29 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_809E96FC: \n"
	);
	asm(
		"addiu           $sp,$sp,-32                            \n"
		"sw              $s0,24($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,28($sp)                            \n"
		"lui             $a1,0x0600                             \n"
		"addiu           $a1,$a1,3356                           \n"
		"addiu           $a0,$a0,332                            \n"
		"jal             external_func_800A529C                 \n"
		"addiu           $a2,$zero,0                            \n"
		"addiu           $a0,$zero,100                          \n"
		"jal             external_func_80077D90                 \n"
		"addiu           $a1,$zero,50                           \n"
		"addiu           $t6,$zero,5                            \n"
		"sh              $v0,406($s0)                           \n"
		"sh              $t6,778($s0)                           \n"
		"addiu           $a0,$s0,36                             \n"
		"jal             external_func_80077E40                 \n"
		"addiu           $a1,$s0,8                              \n"
		"lbu             $t7,729($s0)                           \n"
		"lui             $t9,%hi(data_809E9B98)                 \n"
		"addiu           $t9,$t9,%lo(data_809E9B98)             \n"
		"andi            $t8,$t7,0xfffe                         \n"
		"sb              $t8,729($s0)                           \n"
		"sw              $t9,400($s0)                           \n"
		"lw              $ra,28($sp)                            \n"
		"lw              $s0,24($sp)                            \n"
		"addiu           $sp,$sp,32                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void func_809E9AB4(void) /* 0 internal, 4 external, 37 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_809E9AB4: \n"
	);
	asm(
		"addiu           $sp,$sp,-40                            \n"
		"sw              $s0,32($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,36($sp)                            \n"
		"lui             $a1,0x0600                             \n"
		"addiu           $a1,$a1,872                            \n"
		"addiu           $a0,$a0,332                            \n"
		"jal             external_func_800A534C                 \n"
		"lui             $a2,0xC040                             \n"
		"mtc1            $zero,$f4                              \n"
		"lui             $t7,%hi(data_809EA534)                 \n"
		"addiu           $t6,$zero,5                            \n"
		"addiu           $t7,$t7,%lo(data_809EA534)             \n"
		"sh              $t6,406($s0)                           \n"
		"sw              $t7,400($s0)                           \n"
		"or              $a0,$s0,$zero                          \n"
		"addiu           $a1,$zero,14494                        \n"
		"jal             external_func_8002F828                 \n"
		"swc1            $f4,104($s0)                           \n"
		"lui             $a0,0x0600                             \n"
		"jal             external_func_800A2000                 \n"
		"addiu           $a0,$a0,872                            \n"
		"lh              $t8,406($s0)                           \n"
		"or              $a0,$s0,$zero                          \n"
		"or              $a1,$zero,$zero                        \n"
		"multu           $v0,$t8                                \n"
		"addiu           $a2,$zero,255                          \n"
		"or              $a3,$zero,$zero                        \n"
		"mflo            $t9                                    \n"
		"sw              $t9,16($sp)                            \n"
		"jal             external_func_8003426C                 \n"
		"nop                                                    \n"
		"lw              $ra,36($sp)                            \n"
		"lw              $s0,32($sp)                            \n"
		"addiu           $sp,$sp,40                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void func_809E99D8(void) /* 0 internal, 5 external, 57 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_809E99D8: \n"
	);
	asm(
		"addiu           $sp,$sp,-40                            \n"
		"sw              $s0,32($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,36($sp)                            \n"
		"lui             $a1,0x0600                             \n"
		"addiu           $a1,$a1,872                            \n"
		"addiu           $a0,$a0,332                            \n"
		"jal             external_func_800A5240                 \n"
		"lui             $a2,0xC040                             \n"
		"lw              $t6,772($s0)                           \n"
		"lui             $at,0x0001                             \n"
		"ori             $at,$at,0xf824                         \n"
		"lw              $t7,0($t6)                             \n"
		"or              $a0,$s0,$zero                          \n"
		"and             $t8,$t7,$at                            \n"
		"beq             $t8,$zero,.L000008                     \n"
		"nop                                                    \n"
		"lw              $t9,720($s0)                           \n"
		"lh              $t0,50($t9)                            \n"
		"beq             $zero,$zero,.L000009                   \n"
		"sh              $t0,50($s0)                            \n"
		".L000008:                                              \n"
		"jal             external_func_8002DA78                 \n"
		"lw              $a1,720($s0)                           \n"
		"ori             $at,$zero,0x8000                       \n"
		"addu            $t1,$v0,$at                            \n"
		"sh              $t1,50($s0)                            \n"
		".L000009:                                              \n"
		"lbu             $t2,729($s0)                           \n"
		"lui             $at,0x4120                             \n"
		"mtc1            $at,$f4                                \n"
		"lui             $t4,%hi(data_809EA4E8)                 \n"
		"addiu           $t4,$t4,%lo(data_809EA4E8)             \n"
		"andi            $t3,$t2,0xfffe                         \n"
		"sb              $t3,729($s0)                           \n"
		"sw              $t4,400($s0)                           \n"
		"or              $a0,$s0,$zero                          \n"
		"addiu           $a1,$zero,14464                        \n"
		"jal             external_func_8002F828                 \n"
		"swc1            $f4,104($s0)                           \n"
		"or              $a0,$s0,$zero                          \n"
		"jal             external_func_8002F828                 \n"
		"addiu           $a1,$zero,14651                        \n"
		"lui             $a0,0x0600                             \n"
		"jal             external_func_800A2000                 \n"
		"addiu           $a0,$a0,872                            \n"
		"or              $a0,$s0,$zero                          \n"
		"addiu           $a1,$zero,16384                        \n"
		"addiu           $a2,$zero,255                          \n"
		"or              $a3,$zero,$zero                        \n"
		"jal             external_func_8003426C                 \n"
		"sw              $v0,16($sp)                            \n"
		"lw              $ra,36($sp)                            \n"
		"lw              $s0,32($sp)                            \n"
		"addiu           $sp,$sp,40                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void data_809EA5B0(void) /* 0 internal, 6 external, 89 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809EA5B0: \n"
	);
	asm(
		"addiu           $sp,$sp,-104                           \n"
		"sw              $s0,68($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,76($sp)                            \n"
		"sw              $s1,72($sp)                            \n"
		"or              $s1,$a1,$zero                          \n"
		"jal             external_func_800A49FC                 \n"
		"addiu           $a0,$a0,332                            \n"
		"beq             $v0,$zero,.L000067                     \n"
		"lui             $a2,%hi(data_809EABB0)                 \n"
		"lwc1            $f4,36($s0)                            \n"
		"lui             $at,0x4190                             \n"
		"mtc1            $at,$f8                                \n"
		"swc1            $f4,88($sp)                            \n"
		"lwc1            $f6,40($s0)                            \n"
		"addiu           $t6,$zero,200                          \n"
		"addiu           $a2,$a2,%lo(data_809EABB0)             \n"
		"add.s           $f10,$f6,$f8                           \n"
		"addiu           $t7,$zero,255                          \n"
		"addiu           $t8,$zero,255                          \n"
		"addiu           $t9,$zero,255                          \n"
		"swc1            $f10,92($sp)                           \n"
		"lwc1            $f16,44($s0)                           \n"
		"sw              $t6,16($sp)                            \n"
		"addiu           $t6,$zero,1                            \n"
		"addiu           $t0,$zero,255                          \n"
		"addiu           $t1,$zero,150                          \n"
		"addiu           $t2,$zero,150                          \n"
		"addiu           $t3,$zero,150                          \n"
		"addiu           $t4,$zero,1                            \n"
		"addiu           $t5,$zero,13                           \n"
		"sw              $t5,56($sp)                            \n"
		"sw              $t4,52($sp)                            \n"
		"sw              $t3,48($sp)                            \n"
		"sw              $t2,44($sp)                            \n"
		"sw              $t1,40($sp)                            \n"
		"sw              $t0,36($sp)                            \n"
		"sw              $t6,60($sp)                            \n"
		"sw              $t9,32($sp)                            \n"
		"sw              $t8,28($sp)                            \n"
		"sw              $t7,24($sp)                            \n"
		"sw              $zero,20($sp)                          \n"
		"or              $a3,$a2,$zero                          \n"
		"or              $a0,$s1,$zero                          \n"
		"addiu           $a1,$sp,88                             \n"
		"jal             external_func_8002A6B8                 \n"
		"swc1            $f16,96($sp)                           \n"
		"lwc1            $f18,40($s0)                           \n"
		"lui             $at,0x4120                             \n"
		"mtc1            $at,$f4                                \n"
		"addiu           $t7,$zero,12                           \n"
		"addiu           $t8,$zero,3                            \n"
		"add.s           $f6,$f18,$f4                           \n"
		"addiu           $t9,$zero,15                           \n"
		"addiu           $t0,$zero,-1                           \n"
		"addiu           $t1,$zero,10                           \n"
		"swc1            $f6,92($sp)                            \n"
		"sw              $t1,32($sp)                            \n"
		"sw              $t0,28($sp)                            \n"
		"sw              $t9,24($sp)                            \n"
		"sw              $t8,20($sp)                            \n"
		"sw              $t7,16($sp)                            \n"
		"sw              $zero,36($sp)                          \n"
		"or              $a0,$s1,$zero                          \n"
		"addiu           $a1,$sp,88                             \n"
		"lui             $a2,0x4040                             \n"
		"jal             external_func_800297A4                 \n"
		"or              $a3,$zero,$zero                        \n"
		"or              $a0,$s1,$zero                          \n"
		"or              $a1,$s0,$zero                          \n"
		"addiu           $a2,$s0,36                             \n"
		"jal             external_func_8001F940                 \n"
		"addiu           $a3,$zero,48                           \n"
		"lw              $a2,284($s0)                           \n"
		"or              $a0,$s1,$zero                          \n"
		"addiu           $a1,$s1,7204                           \n"
		"beq             $a2,$zero,.L000068                     \n"
		"nop                                                    \n"
		"jal             external_func_80033748                 \n"
		"addiu           $a3,$zero,6                            \n"
		".L000068:                                              \n"
		"jal             external_func_8002D570                 \n"
		"or              $a0,$s0,$zero                          \n"
		".L000067:                                              \n"
		"lw              $ra,76($sp)                            \n"
		"lw              $s0,68($sp)                            \n"
		"lw              $s1,72($sp)                            \n"
		"jr              $ra                                    \n"
		"addiu           $sp,$sp,104                            \n"
	);
}
void data_809EA4E8(void) /* 1 internal, 2 external, 20 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809EA4E8: \n"
	);
	asm(
		"addiu           $sp,$sp,-24                            \n"
		"sw              $ra,20($sp)                            \n"
		"sw              $a0,24($sp)                            \n"
		"sw              $a1,28($sp)                            \n"
		"addiu           $a1,$zero,0                            \n"
		"addiu           $a0,$a0,104                            \n"
		"jal             external_func_80077A00                 \n"
		"lui             $a2,0x3F80                             \n"
		"lw              $a0,24($sp)                            \n"
		"jal             external_func_800A49FC                 \n"
		"addiu           $a0,$a0,332                            \n"
		"beql            $v0,$zero,.L000062                     \n"
		"lw              $ra,20($sp)                            \n"
		"jal             func_809E9B48                          \n"
		"lw              $a0,24($sp)                            \n"
		"lw              $ra,20($sp)                            \n"
		".L000062:                                              \n"
		"addiu           $sp,$sp,24                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void data_809EA1D8(void) /* 1 internal, 2 external, 27 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809EA1D8: \n"
	);
	asm(
		"addiu           $sp,$sp,-32                            \n"
		"sw              $s0,24($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,28($sp)                            \n"
		"sw              $a1,36($sp)                            \n"
		"jal             external_func_800A49FC                 \n"
		"addiu           $a0,$a0,332                            \n"
		"beq             $v0,$zero,.L000045                     \n"
		"ori             $at,$zero,0x8000                       \n"
		"lh              $t6,138($s0)                           \n"
		"addiu           $t8,$zero,3                            \n"
		"sb              $t8,405($s0)                           \n"
		"addu            $t7,$t6,$at                            \n"
		"sh              $t7,408($s0)                           \n"
		"jal             func_809E9920                          \n"
		"or              $a0,$s0,$zero                          \n"
		".L000045:                                              \n"
		"addiu           $a0,$s0,182                            \n"
		"lh              $a1,138($s0)                           \n"
		"addiu           $a2,$zero,2                            \n"
		"jal             external_func_800787BC                 \n"
		"addiu           $a3,$zero,3640                         \n"
		"lw              $ra,28($sp)                            \n"
		"lw              $s0,24($sp)                            \n"
		"addiu           $sp,$sp,32                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void data_809EA480(void) /* 1 internal, 2 external, 28 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809EA480: \n"
	);
	asm(
		"addiu           $sp,$sp,-32                            \n"
		"or              $a2,$a0,$zero                          \n"
		"sw              $ra,20($sp)                            \n"
		"addiu           $a0,$a0,332                            \n"
		"sw              $a1,36($sp)                            \n"
		"sw              $a0,28($sp)                            \n"
		"jal             external_func_800A49FC                 \n"
		"sw              $a2,32($sp)                            \n"
		"lw              $a0,28($sp)                            \n"
		"jal             external_func_800A56C8                 \n"
		"addiu           $a1,$zero,0                            \n"
		"beq             $v0,$zero,.L000060                     \n"
		"lw              $a2,32($sp)                            \n"
		"lh              $v0,406($a2)                           \n"
		"beq             $v0,$zero,.L000060                     \n"
		"addiu           $t6,$v0,-1                             \n"
		"sh              $t6,406($a2)                           \n"
		".L000060:                                              \n"
		"lh              $t7,406($a2)                           \n"
		"bnel            $t7,$zero,.L000061                     \n"
		"lw              $ra,20($sp)                            \n"
		"jal             func_809E9920                          \n"
		"or              $a0,$a2,$zero                          \n"
		"lw              $ra,20($sp)                            \n"
		".L000061:                                              \n"
		"addiu           $sp,$sp,32                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void data_809E9DFC(void) /* 1 internal, 2 external, 36 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809E9DFC: \n"
	);
	asm(
		"addiu           $sp,$sp,-32                            \n"
		"or              $a2,$a0,$zero                          \n"
		"sw              $ra,20($sp)                            \n"
		"addiu           $a0,$a0,332                            \n"
		"sw              $a1,36($sp)                            \n"
		"sw              $a0,28($sp)                            \n"
		"jal             external_func_800A49FC                 \n"
		"sw              $a2,32($sp)                            \n"
		"lw              $a0,28($sp)                            \n"
		"jal             external_func_800A56C8                 \n"
		"addiu           $a1,$zero,0                            \n"
		"beq             $v0,$zero,.L000026                     \n"
		"lw              $a2,32($sp)                            \n"
		"lh              $v0,406($a2)                           \n"
		"beq             $v0,$zero,.L000026                     \n"
		"addiu           $t6,$v0,-1                             \n"
		"sh              $t6,406($a2)                           \n"
		".L000026:                                              \n"
		"lui             $at,0x42F0                             \n"
		"mtc1            $at,$f6                                \n"
		"lwc1            $f4,144($a2)                           \n"
		"c.lt.s          $f4,$f6                                \n"
		"nop                                                    \n"
		"bc1t            .L000027                               \n"
		"nop                                                    \n"
		"lh              $t7,406($a2)                           \n"
		"bnel            $t7,$zero,.L000028                     \n"
		"lw              $ra,20($sp)                            \n"
		".L000027:                                              \n"
		"jal             func_809E9868                          \n"
		"or              $a0,$a2,$zero                          \n"
		"lw              $ra,20($sp)                            \n"
		".L000028:                                              \n"
		"addiu           $sp,$sp,32                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void data_809E9560(void) /* 1 internal, 7 external, 94 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809E9560: \n"
	);
	asm(
		"addiu           $sp,$sp,-80                            \n"
		"sw              $s1,56($sp)                            \n"
		"or              $s1,$a1,$zero                          \n"
		"sw              $ra,60($sp)                            \n"
		"sw              $s0,52($sp)                            \n"
		"lui             $a1,%hi(data_809EABA4)                 \n"
		"or              $s0,$a0,$zero                          \n"
		"jal             external_func_800780DC                 \n"
		"addiu           $a1,$a1,%lo(data_809EABA4)             \n"
		"lh              $t6,28($s0)                            \n"
		"addiu           $at,$zero,10                           \n"
		"addiu           $a0,$s0,180                            \n"
		"bne             $t6,$at,.L000000                       \n"
		"addiu           $a1,$zero,0                            \n"
		"lw              $t7,4($s0)                             \n"
		"addiu           $at,$zero,-6                           \n"
		"and             $t8,$t7,$at                            \n"
		"beq             $zero,$zero,.L000001                   \n"
		"sw              $t8,4($s0)                             \n"
		".L000000:                                              \n"
		"lui             $a2,0x8003                             \n"
		"addiu           $a2,$a2,-18964                         \n"
		"jal             external_func_8002B1E0                 \n"
		"lui             $a3,0x420C                             \n"
		"lui             $a2,0x0600                             \n"
		"lui             $a3,0x0600                             \n"
		"addiu           $t9,$s0,412                            \n"
		"addiu           $t0,$s0,562                            \n"
		"addiu           $t1,$zero,25                           \n"
		"sw              $t1,24($sp)                            \n"
		"sw              $t0,20($sp)                            \n"
		"sw              $t9,16($sp)                            \n"
		"addiu           $a3,$a3,3692                           \n"
		"addiu           $a2,$a2,12904                          \n"
		"or              $a0,$s1,$zero                          \n"
		"jal             external_func_800A457C                 \n"
		"addiu           $a1,$s0,332                            \n"
		"addiu           $a1,$s0,712                            \n"
		"sw              $a1,68($sp)                            \n"
		"jal             external_func_8005C364                 \n"
		"or              $a0,$s1,$zero                          \n"
		"lui             $a3,%hi(data_809EAB50)                 \n"
		"lw              $a1,68($sp)                            \n"
		"addiu           $a3,$a3,%lo(data_809EAB50)             \n"
		"or              $a0,$s1,$zero                          \n"
		"jal             external_func_8005C4AC                 \n"
		"or              $a2,$s0,$zero                          \n"
		"lui             $a1,%hi(data_809EAB84)                 \n"
		"lui             $a2,%hi(data_809EAB7C)                 \n"
		"addiu           $a2,$a2,%lo(data_809EAB7C)             \n"
		"addiu           $a1,$a1,%lo(data_809EAB84)             \n"
		"jal             external_func_80061ED4                 \n"
		"addiu           $a0,$s0,152                            \n"
		"lh              $t2,28($s0)                            \n"
		"lh              $t5,28($s0)                            \n"
		"addiu           $at,$zero,255                          \n"
		"sra             $t3,$t2,8                              \n"
		"andi            $t4,$t3,0xff                           \n"
		"sh              $t4,410($s0)                           \n"
		"lh              $v0,410($s0)                           \n"
		"andi            $t6,$t5,0xff                           \n"
		"sh              $t6,28($s0)                            \n"
		"beq             $v0,$at,.L000002                       \n"
		"addiu           $t7,$zero,1                            \n"
		"bne             $v0,$zero,.L000003                     \n"
		"nop                                                    \n"
		".L000002:                                              \n"
		"sh              $t7,410($s0)                           \n"
		".L000003:                                              \n"
		"jal             func_809E96FC                          \n"
		"or              $a0,$s0,$zero                          \n"
		"lwc1            $f4,36($s0)                            \n"
		"addiu           $t9,$zero,10                           \n"
		"addiu           $a0,$s1,7204                           \n"
		"swc1            $f4,16($sp)                            \n"
		"lwc1            $f6,40($s0)                            \n"
		"or              $a1,$s0,$zero                          \n"
		"or              $a2,$s1,$zero                          \n"
		"swc1            $f6,20($sp)                            \n"
		"lwc1            $f8,44($s0)                            \n"
		"sw              $zero,28($sp)                          \n"
		"addiu           $a3,$zero,96                           \n"
		"swc1            $f8,24($sp)                            \n"
		"lh              $t8,50($s0)                            \n"
		"sw              $t9,40($sp)                            \n"
		"sw              $zero,36($sp)                          \n"
		"jal             external_func_80032458                 \n"
		"sw              $t8,32($sp)                            \n"
		".L000001:                                              \n"
		"lw              $ra,60($sp)                            \n"
		"lw              $s0,52($sp)                            \n"
		"lw              $s1,56($sp)                            \n"
		"jr              $ra                                    \n"
		"addiu           $sp,$sp,80                             \n"
	);
}
void data_809EA0C4(void) /* 1 internal, 3 external, 75 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809EA0C4: \n"
	);
	asm(
		"addiu           $sp,$sp,-48                            \n"
		"sw              $s0,24($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,28($sp)                            \n"
		"addiu           $a0,$a0,332                            \n"
		"sw              $a1,52($sp)                            \n"
		"jal             external_func_800A49FC                 \n"
		"sw              $a0,36($sp)                            \n"
		"beq             $v0,$zero,.L000039                     \n"
		"lui             $at,0x3F80                             \n"
		"jal             func_809E96FC                          \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000040                   \n"
		"lw              $a0,36($sp)                            \n"
		".L000039:                                              \n"
		"mtc1            $at,$f2                                \n"
		"lwc1            $f0,356($s0)                           \n"
		"lui             $at,0x4040                             \n"
		"c.lt.s          $f0,$f2                                \n"
		"nop                                                    \n"
		"bc1fl           .L000041                               \n"
		"mtc1            $at,$f4                                \n"
		"beq             $zero,$zero,.L000042                   \n"
		"mov.s           $f0,$f2                                \n"
		"mtc1            $at,$f4                                \n"
		".L000041:                                              \n"
		"lui             $at,0x4040                             \n"
		"c.lt.s          $f4,$f0                                \n"
		"nop                                                    \n"
		"bc1fl           .L000043                               \n"
		"mov.s           $f2,$f0                                \n"
		"mtc1            $at,$f2                                \n"
		"beq             $zero,$zero,.L000042                   \n"
		"mov.s           $f0,$f2                                \n"
		"mov.s           $f2,$f0                                \n"
		".L000043:                                              \n"
		"mov.s           $f0,$f2                                \n"
		".L000042:                                              \n"
		"lui             $at,0x4040                             \n"
		"mtc1            $at,$f6                                \n"
		"lui             $at,0x4140                             \n"
		"mtc1            $at,$f10                               \n"
		"sub.s           $f8,$f6,$f0                            \n"
		"lui             $at,0x40A0                             \n"
		"mtc1            $at,$f18                               \n"
		"mul.s           $f16,$f8,$f10                          \n"
		"add.s           $f4,$f16,$f18                          \n"
		"trunc.w.s       $f6,$f4                                \n"
		"mfc1            $t7,$f6                                \n"
		"nop                                                    \n"
		"sh              $t7,778($s0)                           \n"
		"lw              $a0,36($sp)                            \n"
		".L000040:                                              \n"
		"jal             external_func_800A56C8                 \n"
		"lui             $a1,0x4080                             \n"
		"beq             $v0,$zero,.L000044                     \n"
		"addiu           $a0,$s0,36                             \n"
		"lbu             $t8,729($s0)                           \n"
		"andi            $t9,$t8,0xfffe                         \n"
		"sb              $t9,729($s0)                           \n"
		".L000044:                                              \n"
		"lw              $a1,8($s0)                             \n"
		"lui             $a2,0x3F00                             \n"
		"jal             external_func_8007841C                 \n"
		"lui             $a3,0x4040                             \n"
		"addiu           $a0,$s0,44                             \n"
		"lw              $a1,16($s0)                            \n"
		"lui             $a2,0x3F00                             \n"
		"jal             external_func_8007841C                 \n"
		"lui             $a3,0x4040                             \n"
		"lw              $ra,28($sp)                            \n"
		"lw              $s0,24($sp)                            \n"
		"addiu           $sp,$sp,48                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void data_809E9F6C(void) /* 1 internal, 8 external, 90 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809E9F6C: \n"
	);
	asm(
		"addiu           $sp,$sp,-72                            \n"
		"sw              $s0,48($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,52($sp)                            \n"
		"sw              $a1,76($sp)                            \n"
		"lh              $a1,138($s0)                           \n"
		"addiu           $a0,$a0,182                            \n"
		"addiu           $a2,$zero,2                            \n"
		"jal             external_func_800787BC                 \n"
		"addiu           $a3,$zero,3640                         \n"
		"addiu           $a0,$s0,332                            \n"
		"jal             external_func_800A49FC                 \n"
		"sw              $a0,56($sp)                            \n"
		"beq             $v0,$zero,.L000035                     \n"
		"lw              $a0,56($sp)                            \n"
		"jal             func_809E9800                          \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000036                   \n"
		"lw              $ra,52($sp)                            \n"
		".L000035:                                              \n"
		"jal             external_func_800A56C8                 \n"
		"lui             $a1,0x40C0                             \n"
		"beql            $v0,$zero,.L000037                     \n"
		"lh              $t9,406($s0)                           \n"
		"jal             external_func_80077870                 \n"
		"lh              $a0,182($s0)                           \n"
		"lui             $at,0x41B8                             \n"
		"mtc1            $at,$f4                                \n"
		"lwc1            $f8,36($s0)                            \n"
		"lui             $at,0x4140                             \n"
		"mul.s           $f6,$f0,$f4                            \n"
		"mtc1            $at,$f18                               \n"
		"add.s           $f10,$f6,$f8                           \n"
		"swc1            $f10,60($sp)                           \n"
		"lwc1            $f16,40($s0)                           \n"
		"add.s           $f4,$f16,$f18                          \n"
		"swc1            $f4,64($sp)                            \n"
		"jal             external_func_80077834                 \n"
		"lh              $a0,182($s0)                           \n"
		"lui             $at,0x41B8                             \n"
		"mtc1            $at,$f6                                \n"
		"lwc1            $f10,44($s0)                           \n"
		"lwc1            $f16,64($sp)                           \n"
		"mul.s           $f8,$f0,$f6                            \n"
		"lw              $a1,76($sp)                            \n"
		"swc1            $f16,16($sp)                           \n"
		"addiu           $a2,$zero,403                          \n"
		"lw              $a3,60($sp)                            \n"
		"addiu           $a0,$a1,7204                           \n"
		"add.s           $f2,$f8,$f10                           \n"
		"swc1            $f2,20($sp)                            \n"
		"lh              $t6,180($s0)                           \n"
		"sw              $t6,24($sp)                            \n"
		"lh              $t7,182($s0)                           \n"
		"sw              $t7,28($sp)                            \n"
		"lh              $t8,184($s0)                           \n"
		"sw              $zero,36($sp)                          \n"
		"jal             external_func_80031F50                 \n"
		"sw              $t8,32($sp)                            \n"
		"beq             $v0,$zero,.L000038                     \n"
		"or              $a0,$s0,$zero                          \n"
		"jal             external_func_8002F828                 \n"
		"addiu           $a1,$zero,14462                        \n"
		"beq             $zero,$zero,.L000036                   \n"
		"lw              $ra,52($sp)                            \n"
		"lh              $t9,406($s0)                           \n"
		".L000037:                                              \n"
		"lw              $a0,56($sp)                            \n"
		"slti            $at,$t9,2                              \n"
		"bnel            $at,$zero,.L000036                     \n"
		"lw              $ra,52($sp)                            \n"
		"jal             external_func_800A56C8                 \n"
		"lui             $a1,0x4140                             \n"
		"beq             $v0,$zero,.L000038                     \n"
		"lw              $a0,56($sp)                            \n"
		"lui             $a1,0x0600                             \n"
		"addiu           $a1,$a1,452                            \n"
		"jal             external_func_800A5240                 \n"
		"lui             $a2,0xC040                             \n"
		"lh              $v0,406($s0)                           \n"
		"beq             $v0,$zero,.L000038                     \n"
		"addiu           $t0,$v0,-1                             \n"
		"sh              $t0,406($s0)                           \n"
		".L000038:                                              \n"
		"lw              $ra,52($sp)                            \n"
		".L000036:                                              \n"
		"lw              $s0,48($sp)                            \n"
		"addiu           $sp,$sp,72                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void data_809EA534(void) /* 1 internal, 3 external, 35 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809EA534: \n"
	);
	asm(
		"addiu           $sp,$sp,-32                            \n"
		"or              $a2,$a0,$zero                          \n"
		"sw              $ra,20($sp)                            \n"
		"addiu           $a0,$a0,332                            \n"
		"sw              $a1,36($sp)                            \n"
		"sw              $a0,28($sp)                            \n"
		"jal             external_func_800A49FC                 \n"
		"sw              $a2,32($sp)                            \n"
		"lw              $a0,28($sp)                            \n"
		"jal             external_func_800A56C8                 \n"
		"addiu           $a1,$zero,0                            \n"
		"beq             $v0,$zero,.L000063                     \n"
		"lw              $a2,32($sp)                            \n"
		"lh              $v0,406($a2)                           \n"
		"or              $a0,$a2,$zero                          \n"
		"beq             $v0,$zero,.L000064                     \n"
		"addiu           $t6,$v0,-1                             \n"
		"sh              $t6,406($a2)                           \n"
		"lh              $v0,406($a2)                           \n"
		".L000064:                                              \n"
		"bne             $v0,$zero,.L000065                     \n"
		"nop                                                    \n"
		"jal             func_809E9920                          \n"
		"or              $a0,$a2,$zero                          \n"
		"beq             $zero,$zero,.L000066                   \n"
		"lw              $ra,20($sp)                            \n"
		".L000065:                                              \n"
		"jal             external_func_8002F828                 \n"
		"addiu           $a1,$zero,14466                        \n"
		".L000063:                                              \n"
		"lw              $ra,20($sp)                            \n"
		".L000066:                                              \n"
		"addiu           $sp,$sp,32                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void data_809E9E80(void) /* 2 internal, 3 external, 65 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809E9E80: \n"
	);
	asm(
		"addiu           $sp,$sp,-40                            \n"
		"sw              $s0,24($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,28($sp)                            \n"
		"addiu           $a0,$a0,332                            \n"
		"sw              $a1,44($sp)                            \n"
		"jal             external_func_800A49FC                 \n"
		"sw              $a0,36($sp)                            \n"
		"lw              $a0,36($sp)                            \n"
		"jal             external_func_800A56C8                 \n"
		"addiu           $a1,$zero,0                            \n"
		"beq             $v0,$zero,.L000029                     \n"
		"addiu           $a0,$s0,182                            \n"
		"lh              $v0,406($s0)                           \n"
		"beq             $v0,$zero,.L000029                     \n"
		"addiu           $t6,$v0,-1                             \n"
		"sh              $t6,406($s0)                           \n"
		".L000029:                                              \n"
		"lh              $v0,406($s0)                           \n"
		"addiu           $a2,$zero,2                            \n"
		"addiu           $a3,$zero,3640                         \n"
		"andi            $t7,$v0,0x1000                         \n"
		"bnel            $t7,$zero,.L000030                     \n"
		"addiu           $at,$zero,4096                         \n"
		"jal             external_func_800787BC                 \n"
		"lh              $a1,138($s0)                           \n"
		"lh              $v0,406($s0)                           \n"
		"addiu           $at,$zero,4096                         \n"
		".L000030:                                              \n"
		"bne             $v0,$at,.L000031                       \n"
		"lui             $at,0x43F0                             \n"
		"mtc1            $at,$f4                                \n"
		"lwc1            $f0,144($s0)                           \n"
		"lui             $at,0x42F0                             \n"
		"c.lt.s          $f4,$f0                                \n"
		"nop                                                    \n"
		"bc1t            .L000032                               \n"
		"nop                                                    \n"
		"mtc1            $at,$f6                                \n"
		"nop                                                    \n"
		"c.lt.s          $f0,$f6                                \n"
		"nop                                                    \n"
		"bc1f            .L000033                               \n"
		"nop                                                    \n"
		".L000032:                                              \n"
		"jal             func_809E9868                          \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000034                   \n"
		"lw              $ra,28($sp)                            \n"
		".L000033:                                              \n"
		"jal             func_809E97B8                          \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000034                   \n"
		"lw              $ra,28($sp)                            \n"
		".L000031:                                              \n"
		"bnel            $v0,$zero,.L000034                     \n"
		"lw              $ra,28($sp)                            \n"
		"jal             func_809E97B8                          \n"
		"or              $a0,$s0,$zero                          \n"
		"lw              $ra,28($sp)                            \n"
		".L000034:                                              \n"
		"lw              $s0,24($sp)                            \n"
		"addiu           $sp,$sp,40                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void data_809EA82C(void) /* 1 internal, 7 external, 93 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809EA82C: \n"
	);
	asm(
		"addiu           $sp,$sp,-56                            \n"
		"sw              $ra,36($sp)                            \n"
		"sw              $s1,32($sp)                            \n"
		"sw              $s0,28($sp)                            \n"
		"lh              $t6,28($a0)                            \n"
		"addiu           $at,$zero,10                           \n"
		"or              $s0,$a0,$zero                          \n"
		"beq             $t6,$at,.L000076                       \n"
		"or              $s1,$a1,$zero                          \n"
		"jal             func_809EA70C                          \n"
		"nop                                                    \n"
		"lw              $t9,400($s0)                           \n"
		"or              $a0,$s0,$zero                          \n"
		"or              $a1,$s1,$zero                          \n"
		"jalr            $t9                                    \n"
		"nop                                                    \n"
		"jal             external_func_8002D8E0                 \n"
		"or              $a0,$s0,$zero                          \n"
		"lh              $t7,776($s0)                           \n"
		"lh              $t8,778($s0)                           \n"
		"addiu           $t0,$zero,29                           \n"
		"mtc1            $t7,$f4                                \n"
		"mtc1            $t8,$f6                                \n"
		"sw              $t0,20($sp)                            \n"
		"cvt.s.w         $f4,$f4                                \n"
		"or              $a0,$s1,$zero                          \n"
		"or              $a1,$s0,$zero                          \n"
		"lui             $a2,0x41A0                             \n"
		"cvt.s.w         $f8,$f6                                \n"
		"mfc1            $a3,$f4                                \n"
		"jal             external_func_8002E4B4                 \n"
		"swc1            $f8,16($sp)                            \n"
		"addiu           $a1,$s0,712                            \n"
		"sw              $a1,40($sp)                            \n"
		"jal             external_func_800626DC                 \n"
		"or              $a0,$s0,$zero                          \n"
		"lbu             $t1,729($s0)                           \n"
		"lui             $at,0x0001                             \n"
		"ori             $at,$at,0x1e60                         \n"
		"andi            $t2,$t1,0x1                            \n"
		"beq             $t2,$zero,.L000077                     \n"
		"or              $a0,$s1,$zero                          \n"
		"addu            $a1,$s1,$at                            \n"
		"jal             external_func_8005D9F4                 \n"
		"lw              $a2,40($sp)                            \n"
		".L000077:                                              \n"
		"lui             $at,0x0001                             \n"
		"ori             $at,$at,0x1e60                         \n"
		"addu            $a1,$s1,$at                            \n"
		"or              $a0,$s1,$zero                          \n"
		"jal             external_func_8005DC4C                 \n"
		"lw              $a2,40($sp)                            \n"
		"lw              $v1,400($s0)                           \n"
		"lui             $t3,%hi(data_809E9B98)                 \n"
		"addiu           $t3,$t3,%lo(data_809E9B98)             \n"
		"bne             $t3,$v1,.L000078                       \n"
		"lui             $t4,%hi(data_809EA0C4)                 \n"
		"or              $a0,$s0,$zero                          \n"
		"jal             external_func_8002D5B8                 \n"
		"lw              $a1,356($s0)                           \n"
		"beq             $zero,$zero,.L000079                   \n"
		"lw              $ra,36($sp)                            \n"
		".L000078:                                              \n"
		"addiu           $t4,$t4,%lo(data_809EA0C4)             \n"
		"bne             $t4,$v1,.L000080                       \n"
		"or              $a0,$s0,$zero                          \n"
		"lui             $a0,0x0600                             \n"
		"jal             external_func_800A2000                 \n"
		"addiu           $a0,$a0,1240                           \n"
		"lui             $at,0x41A0                             \n"
		"mtc1            $at,$f0                                \n"
		"lwc1            $f10,356($s0)                          \n"
		"mtc1            $v0,$f18                               \n"
		"or              $a0,$s0,$zero                          \n"
		"mul.s           $f16,$f10,$f0                          \n"
		"cvt.s.w         $f4,$f18                               \n"
		"div.s           $f6,$f16,$f4                           \n"
		"sub.s           $f8,$f0,$f6                            \n"
		"mfc1            $a1,$f8                                \n"
		"jal             external_func_8002D5B8                 \n"
		"nop                                                    \n"
		"beq             $zero,$zero,.L000079                   \n"
		"lw              $ra,36($sp)                            \n"
		".L000080:                                              \n"
		"jal             external_func_8002D5B8                 \n"
		"lui             $a1,0x41A0                             \n"
		".L000076:                                              \n"
		"lw              $ra,36($sp)                            \n"
		".L000079:                                              \n"
		"lw              $s0,28($sp)                            \n"
		"lw              $s1,32($sp)                            \n"
		"jr              $ra                                    \n"
		"addiu           $sp,$sp,56                             \n"
	);
}
void data_809EA240(void) /* 2 internal, 7 external, 158 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809EA240: \n"
	);
	asm(
		"addiu           $sp,$sp,-56                            \n"
		"sw              $s0,32($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,36($sp)                            \n"
		"addiu           $a0,$a0,332                            \n"
		"sw              $a1,60($sp)                            \n"
		"jal             external_func_800A49FC                 \n"
		"sw              $a0,40($sp)                            \n"
		"lw              $a0,40($sp)                            \n"
		"jal             external_func_800A56C8                 \n"
		"addiu           $a1,$zero,0                            \n"
		"beq             $v0,$zero,.L000046                     \n"
		"addiu           $t8,$zero,1                            \n"
		"lh              $v0,406($s0)                           \n"
		"beq             $v0,$zero,.L000046                     \n"
		"addiu           $t6,$v0,-1                             \n"
		"sh              $t6,406($s0)                           \n"
		".L000046:                                              \n"
		"lbu             $t7,404($s0)                           \n"
		"or              $a0,$s0,$zero                          \n"
		"beql            $t7,$zero,.L000047                     \n"
		"sb              $t8,404($s0)                           \n"
		"jal             external_func_8002F828                 \n"
		"addiu           $a1,$zero,14463                        \n"
		"beq             $zero,$zero,.L000047                   \n"
		"sb              $zero,404($s0)                         \n"
		"sb              $t8,404($s0)                           \n"
		".L000047:                                              \n"
		"addiu           $a0,$s0,104                            \n"
		"lui             $a1,0x40F0                             \n"
		"jal             external_func_80077A00                 \n"
		"lui             $a2,0x3F80                             \n"
		"lh              $a1,408($s0)                           \n"
		"addiu           $t9,$zero,182                          \n"
		"sw              $t9,16($sp)                            \n"
		"addiu           $a0,$s0,50                             \n"
		"addiu           $a2,$zero,1                            \n"
		"jal             external_func_8007869C                 \n"
		"addiu           $a3,$zero,3640                         \n"
		"bnel            $v0,$zero,.L000048                     \n"
		"lh              $t8,50($s0)                            \n"
		"lhu             $v0,136($s0)                           \n"
		"or              $a0,$s0,$zero                          \n"
		"andi            $t0,$v0,0x20                           \n"
		"beq             $t0,$zero,.L000049                     \n"
		"andi            $t1,$v0,0x8                            \n"
		"jal             external_func_8002DAC0                 \n"
		"addiu           $a1,$s0,8                              \n"
		"beq             $zero,$zero,.L000050                   \n"
		"sh              $v0,408($s0)                           \n"
		".L000049:                                              \n"
		"beql            $t1,$zero,.L000051                     \n"
		"lbu             $t3,405($s0)                           \n"
		"lh              $t2,126($s0)                           \n"
		"beq             $zero,$zero,.L000050                   \n"
		"sh              $t2,408($s0)                           \n"
		"lbu             $t3,405($s0)                           \n"
		".L000051:                                              \n"
		"or              $a0,$s0,$zero                          \n"
		"bnel            $t3,$zero,.L000052                     \n"
		"lh              $t6,138($s0)                           \n"
		"jal             external_func_8002DAC0                 \n"
		"addiu           $a1,$s0,8                              \n"
		"lh              $a1,138($s0)                           \n"
		"subu            $v1,$v0,$a1                            \n"
		"sll             $v1,$v1,16                             \n"
		"sra             $v1,$v1,16                             \n"
		"bltz            $v1,.L000053                           \n"
		"subu            $a0,$zero,$v1                          \n"
		"beq             $zero,$zero,.L000053                   \n"
		"or              $a0,$v1,$zero                          \n"
		".L000053:                                              \n"
		"slti            $at,$a0,8193                           \n"
		"bnel            $at,$zero,.L000054                     \n"
		"mtc1            $v1,$f4                                \n"
		"beq             $zero,$zero,.L000050                   \n"
		"sh              $v0,408($s0)                           \n"
		"mtc1            $v1,$f4                                \n"
		".L000054:                                              \n"
		"mtc1            $zero,$f8                              \n"
		"mtc1            $a1,$f18                               \n"
		"cvt.s.w         $f6,$f4                                \n"
		"lui             $at,0xBF80                             \n"
		"c.le.s          $f8,$f6                                \n"
		"nop                                                    \n"
		"bc1fl           .L000055                               \n"
		"mtc1            $at,$f0                                \n"
		"lui             $at,0x3F80                             \n"
		"mtc1            $at,$f0                                \n"
		"beq             $zero,$zero,.L000056                   \n"
		"lui             $at,0xC600                             \n"
		"mtc1            $at,$f0                                \n"
		".L000055:                                              \n"
		"nop                                                    \n"
		"lui             $at,0xC600                             \n"
		".L000056:                                              \n"
		"mtc1            $at,$f10                               \n"
		"cvt.s.w         $f4,$f18                               \n"
		"mul.s           $f16,$f0,$f10                          \n"
		"add.s           $f6,$f16,$f4                           \n"
		"trunc.w.s       $f8,$f6                                \n"
		"mfc1            $t5,$f8                                \n"
		"beq             $zero,$zero,.L000050                   \n"
		"sh              $t5,408($s0)                           \n"
		"lh              $t6,138($s0)                           \n"
		".L000052:                                              \n"
		"ori             $at,$zero,0x8000                       \n"
		"addu            $t7,$t6,$at                            \n"
		"sh              $t7,408($s0)                           \n"
		".L000050:                                              \n"
		"lh              $t8,50($s0)                            \n"
		".L000048:                                              \n"
		"lbu             $t0,405($s0)                           \n"
		"ori             $at,$zero,0x8000                       \n"
		"addu            $t9,$t8,$at                            \n"
		"bne             $t0,$zero,.L000057                     \n"
		"sh              $t9,182($s0)                           \n"
		"or              $a0,$s0,$zero                          \n"
		"jal             external_func_8002DBB0                 \n"
		"addiu           $a1,$s0,8                              \n"
		"lui             $at,0x41A0                             \n"
		"mtc1            $at,$f10                               \n"
		"nop                                                    \n"
		"c.lt.s          $f0,$f10                               \n"
		"nop                                                    \n"
		"bc1fl           .L000058                               \n"
		"lh              $t2,406($s0)                           \n"
		"lwc1            $f18,40($s0)                           \n"
		"lwc1            $f16,12($s0)                           \n"
		"lui             $at,0x4000                             \n"
		"mtc1            $at,$f4                                \n"
		"sub.s           $f0,$f18,$f16                          \n"
		"addiu           $t1,$zero,255                          \n"
		"or              $a0,$s0,$zero                          \n"
		"abs.s           $f0,$f0                                \n"
		"c.lt.s          $f0,$f4                                \n"
		"nop                                                    \n"
		"bc1fl           .L000058                               \n"
		"lh              $t2,406($s0)                           \n"
		"mtc1            $zero,$f6                              \n"
		"sb              $t1,174($s0)                           \n"
		"jal             func_809E9868                          \n"
		"swc1            $f6,104($s0)                           \n"
		"beq             $zero,$zero,.L000059                   \n"
		"lw              $ra,36($sp)                            \n"
		".L000057:                                              \n"
		"lh              $t2,406($s0)                           \n"
		".L000058:                                              \n"
		"bnel            $t2,$zero,.L000059                     \n"
		"lw              $ra,36($sp)                            \n"
		"jal             func_809E9978                          \n"
		"or              $a0,$s0,$zero                          \n"
		"lw              $ra,36($sp)                            \n"
		".L000059:                                              \n"
		"lw              $s0,32($sp)                            \n"
		"addiu           $sp,$sp,56                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void data_809E9B98(void) /* 3 internal, 3 external, 169 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809E9B98: \n"
	);
	asm(
		"addiu           $sp,$sp,-48                            \n"
		"sw              $ra,28($sp)                            \n"
		"sw              $s0,24($sp)                            \n"
		"sw              $a1,52($sp)                            \n"
		"lui             $at,0x3F00                             \n"
		"mtc1            $at,$f6                                \n"
		"lwc1            $f4,360($a0)                           \n"
		"or              $s0,$a0,$zero                          \n"
		"or              $v1,$zero,$zero                        \n"
		"c.lt.s          $f4,$f6                                \n"
		"addiu           $a0,$s0,332                            \n"
		"lui             $a1,0x4110                             \n"
		"bc1f            .L000010                               \n"
		"nop                                                    \n"
		"addiu           $v1,$zero,1                            \n"
		".L000010:                                              \n"
		"beql            $v1,$zero,.L000011                     \n"
		"sw              $v1,44($sp)                            \n"
		"lh              $v0,406($s0)                           \n"
		"beq             $v0,$zero,.L000012                     \n"
		"addiu           $t6,$v0,-1                             \n"
		"sh              $t6,406($s0)                           \n"
		".L000012:                                              \n"
		"sw              $v1,44($sp)                            \n"
		".L000011:                                              \n"
		"jal             external_func_800A56C8                 \n"
		"sw              $a0,32($sp)                            \n"
		"lui             $at,0x4110                             \n"
		"mtc1            $at,$f12                               \n"
		"beq             $v0,$zero,.L000013                     \n"
		"lw              $a0,32($sp)                            \n"
		"lbu             $t7,729($s0)                           \n"
		"ori             $t8,$t7,0x1                            \n"
		"beq             $zero,$zero,.L000014                   \n"
		"sb              $t8,729($s0)                           \n"
		".L000013:                                              \n"
		"jal             external_func_800A56C8                 \n"
		"lui             $a1,0x4100                             \n"
		"lui             $at,0x4110                             \n"
		"mtc1            $at,$f12                               \n"
		"beq             $v0,$zero,.L000014                     \n"
		"or              $a0,$s0,$zero                          \n"
		"jal             external_func_8002F828                 \n"
		"addiu           $a1,$zero,14460                        \n"
		"lui             $at,0x4110                             \n"
		"mtc1            $at,$f12                               \n"
		"nop                                                    \n"
		".L000014:                                              \n"
		"lwc1            $f0,356($s0)                           \n"
		"lui             $at,0x4140                             \n"
		"c.lt.s          $f0,$f12                               \n"
		"nop                                                    \n"
		"bc1fl           .L000015                               \n"
		"mtc1            $at,$f14                               \n"
		"beq             $zero,$zero,.L000016                   \n"
		"mov.s           $f0,$f12                               \n"
		"mtc1            $at,$f14                               \n"
		".L000015:                                              \n"
		"nop                                                    \n"
		"c.lt.s          $f14,$f0                               \n"
		"nop                                                    \n"
		"bc1fl           .L000017                               \n"
		"mov.s           $f2,$f0                                \n"
		"beq             $zero,$zero,.L000017                   \n"
		"mov.s           $f2,$f14                               \n"
		"mov.s           $f2,$f0                                \n"
		".L000017:                                              \n"
		"mov.s           $f0,$f2                                \n"
		".L000016:                                              \n"
		"sub.s           $f8,$f0,$f12                           \n"
		"lui             $at,0x40A0                             \n"
		"mtc1            $at,$f16                               \n"
		"lui             $at,0x42F0                             \n"
		"mul.s           $f10,$f8,$f12                          \n"
		"add.s           $f18,$f10,$f16                         \n"
		"trunc.w.s       $f4,$f18                               \n"
		"mfc1            $t0,$f4                                \n"
		"nop                                                    \n"
		"sh              $t0,778($s0)                           \n"
		"lw              $t1,44($sp)                            \n"
		"bne             $t1,$zero,.L000018                     \n"
		"nop                                                    \n"
		"lwc1            $f6,144($s0)                           \n"
		"mtc1            $at,$f8                                \n"
		"nop                                                    \n"
		"c.lt.s          $f6,$f8                                \n"
		"nop                                                    \n"
		"bc1f            .L000018                               \n"
		"nop                                                    \n"
		"jal             func_809E9868                          \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000019                   \n"
		"lw              $t3,44($sp)                            \n"
		".L000018:                                              \n"
		"jal             external_func_800A49FC                 \n"
		"lw              $a0,32($sp)                            \n"
		"beq             $v0,$zero,.L000020                     \n"
		"lui             $at,0x42F0                             \n"
		"lwc1            $f2,144($s0)                           \n"
		"mtc1            $at,$f10                               \n"
		"nop                                                    \n"
		"c.lt.s          $f2,$f10                               \n"
		"nop                                                    \n"
		"bc1fl           .L000021                               \n"
		"lh              $t2,406($s0)                           \n"
		"jal             func_809E9868                          \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000019                   \n"
		"lw              $t3,44($sp)                            \n"
		"lh              $t2,406($s0)                           \n"
		".L000021:                                              \n"
		"lui             $at,0x43A0                             \n"
		"bne             $t2,$zero,.L000022                     \n"
		"nop                                                    \n"
		"mtc1            $at,$f16                               \n"
		"nop                                                    \n"
		"c.lt.s          $f16,$f2                               \n"
		"nop                                                    \n"
		"bc1f            .L000022                               \n"
		"nop                                                    \n"
		"jal             func_809E9770                          \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000019                   \n"
		"lw              $t3,44($sp)                            \n"
		".L000022:                                              \n"
		"jal             func_809E9800                          \n"
		"or              $a0,$s0,$zero                          \n"
		".L000020:                                              \n"
		"lw              $t3,44($sp)                            \n"
		".L000019:                                              \n"
		"lui             $at,0x4320                             \n"
		"beql            $t3,$zero,.L000023                     \n"
		"lw              $ra,28($sp)                            \n"
		"lwc1            $f2,144($s0)                           \n"
		"mtc1            $at,$f18                               \n"
		"nop                                                    \n"
		"c.lt.s          $f18,$f2                               \n"
		"nop                                                    \n"
		"bc1fl           .L000023                               \n"
		"lw              $ra,28($sp)                            \n"
		"lwc1            $f0,148($s0)                           \n"
		"lui             $at,0x42F0                             \n"
		"mtc1            $at,$f4                                \n"
		"abs.s           $f0,$f0                                \n"
		"c.lt.s          $f0,$f4                                \n"
		"nop                                                    \n"
		"bc1fl           .L000023                               \n"
		"lw              $ra,28($sp)                            \n"
		"lh              $t4,406($s0)                           \n"
		"lui             $at,0x43F0                             \n"
		"beql            $t4,$zero,.L000024                     \n"
		"lui             $at,0x3F80                             \n"
		"mtc1            $at,$f6                                \n"
		"nop                                                    \n"
		"c.lt.s          $f2,$f6                                \n"
		"nop                                                    \n"
		"bc1f            .L000025                               \n"
		"lui             $at,0x3F80                             \n"
		".L000024:                                              \n"
		"mtc1            $at,$f8                                \n"
		"nop                                                    \n"
		"swc1            $f8,360($s0)                           \n"
		".L000025:                                              \n"
		"lw              $ra,28($sp)                            \n"
		".L000023:                                              \n"
		"lw              $s0,24($sp)                            \n"
		"addiu           $sp,$sp,48                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
void func_809EA70C(void) /* 3 internal, 4 external, 79 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Lfunc_809EA70C: \n"
	);
	asm(
		"addiu           $sp,$sp,-40                            \n"
		"sw              $ra,36($sp)                            \n"
		"sw              $s0,32($sp)                            \n"
		"sw              $a1,44($sp)                            \n"
		"lbu             $v0,729($a0)                           \n"
		"or              $s0,$a0,$zero                          \n"
		"addiu           $a1,$s0,736                            \n"
		"andi            $t6,$v0,0x2                            \n"
		"beq             $t6,$zero,.L000069                     \n"
		"andi            $t7,$v0,0xfffd                         \n"
		"sb              $t7,729($a0)                           \n"
		"jal             external_func_80035650                 \n"
		"addiu           $a2,$zero,1                            \n"
		"lbu             $t8,174($s0)                           \n"
		"addiu           $at,$zero,50                           \n"
		"bne             $t8,$at,.L000070                       \n"
		"nop                                                    \n"
		"lbu             $v0,177($s0)                           \n"
		"addiu           $at,$zero,1                            \n"
		"bne             $v0,$zero,.L000071                     \n"
		"nop                                                    \n"
		"lbu             $t9,176($s0)                           \n"
		"beql            $t9,$zero,.L000072                     \n"
		"lw              $ra,36($sp)                            \n"
		".L000071:                                              \n"
		"beq             $v0,$at,.L000073                       \n"
		"addiu           $at,$zero,2                            \n"
		"bne             $v0,$at,.L000074                       \n"
		"lw              $a0,44($sp)                            \n"
		"addiu           $t0,$zero,50                           \n"
		"sw              $t0,16($sp)                            \n"
		"or              $a1,$s0,$zero                          \n"
		"addiu           $a2,$s0,36                             \n"
		"jal             external_func_8002A65C                 \n"
		"addiu           $a3,$zero,40                           \n"
		".L000074:                                              \n"
		"jal             func_809E99D8                          \n"
		"or              $a0,$s0,$zero                          \n"
		"jal             external_func_80035628                 \n"
		"or              $a0,$s0,$zero                          \n"
		"bne             $v0,$zero,.L000075                     \n"
		"lw              $a0,44($sp)                            \n"
		"jal             external_func_80032C7C                 \n"
		"or              $a1,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000072                   \n"
		"lw              $ra,36($sp)                            \n"
		".L000073:                                              \n"
		"lw              $t2,400($s0)                           \n"
		"lui             $t1,%hi(data_809EA534)                 \n"
		"addiu           $t1,$t1,%lo(data_809EA534)             \n"
		"beql            $t1,$t2,.L000072                       \n"
		"lw              $ra,36($sp)                            \n"
		"jal             func_809E9AB4                          \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000072                   \n"
		"lw              $ra,36($sp)                            \n"
		".L000070:                                              \n"
		"jal             func_809E98B4                          \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000072                   \n"
		"lw              $ra,36($sp)                            \n"
		".L000069:                                              \n"
		"lbu             $t3,174($s0)                           \n"
		"addiu           $at,$zero,255                          \n"
		"lw              $t4,44($sp)                            \n"
		"bnel            $t3,$at,.L000072                       \n"
		"lw              $ra,36($sp)                            \n"
		"lbu             $t5,7206($t4)                          \n"
		"beql            $t5,$zero,.L000072                     \n"
		"lw              $ra,36($sp)                            \n"
		"jal             func_809E98B4                          \n"
		"or              $a0,$s0,$zero                          \n"
		".L000075:                                              \n"
		"lw              $ra,36($sp)                            \n"
		".L000072:                                              \n"
		"lw              $s0,32($sp)                            \n"
		"addiu           $sp,$sp,40                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
const z64_actor_init_t init_vars = {
	.number = 0xDEAD, .padding = 0xBEEF, /* <-- magic values, do not change */
	.type = 0x05,
	.room = 0x00,
	.flags = 0x00000005,
	.object = OBJ_ID,
	.instance_size = sizeof(entity_t),
	.init = data_809E9560,
	.dest = data_809E96C8,
	.main = data_809EA82C,
	.draw = data_809EAAC4
};
