int32_t data_809EA98C(z64_global_t* gl, int32_t limb, uint32_t* dlist, vec3f_t* translation, vec3s_t* rotation, void* _en) /* 0 internal, 1 external, 84 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809EA98C: \n"
	);
	asm(
		"addiu           $sp,$sp,-24                            \n"
		"addiu           $at,$zero,7                            \n"
		"sw              $ra,20($sp)                            \n"
		"sw              $a0,24($sp)                            \n"
		"sw              $a2,32($sp)                            \n"
		"bne             $a1,$at,.L000081                       \n"
		"sw              $a3,36($sp)                            \n"
		"lw              $v0,44($sp)                            \n"
		"lui             $t6,%hi(data_809E9F6C)                 \n"
		"addiu           $t6,$t6,%lo(data_809E9F6C)             \n"
		"lw              $t7,400($v0)                           \n"
		"lui             $at,0x40C0                             \n"
		"bnel            $t6,$t7,.L000082                       \n"
		"or              $v0,$zero,$zero                        \n"
		"mtc1            $at,$f18                               \n"
		"lwc1            $f0,356($v0)                           \n"
		"lui             $at,0x40E0                             \n"
		"c.le.s          $f0,$f18                               \n"
		"nop                                                    \n"
		"bc1fl           .L000083                               \n"
		"mtc1            $at,$f2                                \n"
		"lui             $at,0x3F80                             \n"
		"mtc1            $at,$f18                               \n"
		"lui             $at,%hi(data_809EABC0)                 \n"
		"lwc1            $f4,%lo(data_809EABC0)($at)            \n"
		"lui             $at,%hi(data_809EABC4)                 \n"
		"lwc1            $f8,%lo(data_809EABC4)($at)            \n"
		"mul.s           $f6,$f0,$f4                            \n"
		"nop                                                    \n"
		"mul.s           $f10,$f0,$f8                           \n"
		"sub.s           $f12,$f18,$f6                          \n"
		"add.s           $f14,$f10,$f18                         \n"
		"beq             $zero,$zero,.L000084                   \n"
		"mov.s           $f16,$f14                              \n"
		"mtc1            $at,$f2                                \n"
		".L000083:                                              \n"
		"lui             $at,0x4120                             \n"
		"c.le.s          $f0,$f2                                \n"
		"nop                                                    \n"
		"bc1fl           .L000085                               \n"
		"mtc1            $at,$f4                                \n"
		"lui             $at,0x3F00                             \n"
		"mtc1            $at,$f4                                \n"
		"lui             $at,%hi(data_809EABC8)                 \n"
		"lwc1            $f6,%lo(data_809EABC8)($at)            \n"
		"sub.s           $f0,$f0,$f18                           \n"
		"lui             $at,%hi(data_809EABCC)                 \n"
		"lwc1            $f8,%lo(data_809EABCC)($at)            \n"
		"add.s           $f12,$f4,$f0                           \n"
		"mul.s           $f10,$f0,$f8                           \n"
		"sub.s           $f14,$f6,$f10                          \n"
		"beq             $zero,$zero,.L000084                   \n"
		"mov.s           $f16,$f14                              \n"
		"mtc1            $at,$f4                                \n"
		".L000085:                                              \n"
		"lui             $at,0x3F80                             \n"
		"c.le.s          $f0,$f4                                \n"
		"nop                                                    \n"
		"bc1f            .L000086                               \n"
		"nop                                                    \n"
		"mtc1            $at,$f14                               \n"
		"sub.s           $f8,$f0,$f2                            \n"
		"lui             $at,%hi(data_809EABD0)                 \n"
		"lwc1            $f6,%lo(data_809EABD0)($at)            \n"
		"lui             $at,0x3FC0                             \n"
		"mtc1            $at,$f4                                \n"
		"mul.s           $f10,$f8,$f6                           \n"
		"mov.s           $f16,$f14                              \n"
		"beq             $zero,$zero,.L000084                   \n"
		"sub.s           $f12,$f4,$f10                          \n"
		".L000086:                                              \n"
		"beq             $zero,$zero,.L000082                   \n"
		"or              $v0,$zero,$zero                        \n"
		".L000084:                                              \n"
		"mfc1            $a2,$f16                               \n"
		"jal             0x800D0A8C                 \n"
		"addiu           $a3,$zero,1                            \n"
		".L000081:                                              \n"
		"or              $v0,$zero,$zero                        \n"
		".L000082:                                              \n"
		"lw              $ra,20($sp)                            \n"
		"addiu           $sp,$sp,24                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
