void data_809EA240(entity_t* en) /* 2 internal, 7 external, 158 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809EA240: \n"
	);
	asm(
		"addiu           $sp,$sp,-56                            \n"
		"sw              $s0,32($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,36($sp)                            \n"
		"addiu           $a0,$a0,332                            \n"
		"sw              $a1,60($sp)                            \n"
		"jal             0x800A49FC                 \n"
		"sw              $a0,40($sp)                            \n"
		"lw              $a0,40($sp)                            \n"
		"jal             0x800A56C8                 \n"
		"addiu           $a1,$zero,0                            \n"
		"beq             $v0,$zero,.L000046                     \n"
		"addiu           $t8,$zero,1                            \n"
		"lh              $v0,406($s0)                           \n"
		"beq             $v0,$zero,.L000046                     \n"
		"addiu           $t6,$v0,-1                             \n"
		"sh              $t6,406($s0)                           \n"
		".L000046:                                              \n"
		"lbu             $t7,404($s0)                           \n"
		"or              $a0,$s0,$zero                          \n"
		"beql            $t7,$zero,.L000047                     \n"
		"sb              $t8,404($s0)                           \n"
		"jal             0x8002F828                 \n"
		"addiu           $a1,$zero,14463                        \n"
		"beq             $zero,$zero,.L000047                   \n"
		"sb              $zero,404($s0)                         \n"
		"sb              $t8,404($s0)                           \n"
		".L000047:                                              \n"
		"addiu           $a0,$s0,104                            \n"
		"lui             $a1,0x40F0                             \n"
		"jal             0x80077A00                 \n"
		"lui             $a2,0x3F80                             \n"
		"lh              $a1,408($s0)                           \n"
		"addiu           $t9,$zero,182                          \n"
		"sw              $t9,16($sp)                            \n"
		"addiu           $a0,$s0,50                             \n"
		"addiu           $a2,$zero,1                            \n"
		"jal             0x8007869C                 \n"
		"addiu           $a3,$zero,3640                         \n"
		"bnel            $v0,$zero,.L000048                     \n"
		"lh              $t8,50($s0)                            \n"
		"lhu             $v0,136($s0)                           \n"
		"or              $a0,$s0,$zero                          \n"
		"andi            $t0,$v0,0x20                           \n"
		"beq             $t0,$zero,.L000049                     \n"
		"andi            $t1,$v0,0x8                            \n"
		"jal             0x8002DAC0                 \n"
		"addiu           $a1,$s0,8                              \n"
		"beq             $zero,$zero,.L000050                   \n"
		"sh              $v0,408($s0)                           \n"
		".L000049:                                              \n"
		"beql            $t1,$zero,.L000051                     \n"
		"lbu             $t3,405($s0)                           \n"
		"lh              $t2,126($s0)                           \n"
		"beq             $zero,$zero,.L000050                   \n"
		"sh              $t2,408($s0)                           \n"
		"lbu             $t3,405($s0)                           \n"
		".L000051:                                              \n"
		"or              $a0,$s0,$zero                          \n"
		"bnel            $t3,$zero,.L000052                     \n"
		"lh              $t6,138($s0)                           \n"
		"jal             0x8002DAC0                 \n"
		"addiu           $a1,$s0,8                              \n"
		"lh              $a1,138($s0)                           \n"
		"subu            $v1,$v0,$a1                            \n"
		"sll             $v1,$v1,16                             \n"
		"sra             $v1,$v1,16                             \n"
		"bltz            $v1,.L000053                           \n"
		"subu            $a0,$zero,$v1                          \n"
		"beq             $zero,$zero,.L000053                   \n"
		"or              $a0,$v1,$zero                          \n"
		".L000053:                                              \n"
		"slti            $at,$a0,8193                           \n"
		"bnel            $at,$zero,.L000054                     \n"
		"mtc1            $v1,$f4                                \n"
		"beq             $zero,$zero,.L000050                   \n"
		"sh              $v0,408($s0)                           \n"
		"mtc1            $v1,$f4                                \n"
		".L000054:                                              \n"
		"mtc1            $zero,$f8                              \n"
		"mtc1            $a1,$f18                               \n"
		"cvt.s.w         $f6,$f4                                \n"
		"lui             $at,0xBF80                             \n"
		"c.le.s          $f8,$f6                                \n"
		"nop                                                    \n"
		"bc1fl           .L000055                               \n"
		"mtc1            $at,$f0                                \n"
		"lui             $at,0x3F80                             \n"
		"mtc1            $at,$f0                                \n"
		"beq             $zero,$zero,.L000056                   \n"
		"lui             $at,0xC600                             \n"
		"mtc1            $at,$f0                                \n"
		".L000055:                                              \n"
		"nop                                                    \n"
		"lui             $at,0xC600                             \n"
		".L000056:                                              \n"
		"mtc1            $at,$f10                               \n"
		"cvt.s.w         $f4,$f18                               \n"
		"mul.s           $f16,$f0,$f10                          \n"
		"add.s           $f6,$f16,$f4                           \n"
		"trunc.w.s       $f8,$f6                                \n"
		"mfc1            $t5,$f8                                \n"
		"beq             $zero,$zero,.L000050                   \n"
		"sh              $t5,408($s0)                           \n"
		"lh              $t6,138($s0)                           \n"
		".L000052:                                              \n"
		"ori             $at,$zero,0x8000                       \n"
		"addu            $t7,$t6,$at                            \n"
		"sh              $t7,408($s0)                           \n"
		".L000050:                                              \n"
		"lh              $t8,50($s0)                            \n"
		".L000048:                                              \n"
		"lbu             $t0,405($s0)                           \n"
		"ori             $at,$zero,0x8000                       \n"
		"addu            $t9,$t8,$at                            \n"
		"bne             $t0,$zero,.L000057                     \n"
		"sh              $t9,182($s0)                           \n"
		"or              $a0,$s0,$zero                          \n"
		"jal             0x8002DBB0                 \n"
		"addiu           $a1,$s0,8                              \n"
		"lui             $at,0x41A0                             \n"
		"mtc1            $at,$f10                               \n"
		"nop                                                    \n"
		"c.lt.s          $f0,$f10                               \n"
		"nop                                                    \n"
		"bc1fl           .L000058                               \n"
		"lh              $t2,406($s0)                           \n"
		"lwc1            $f18,40($s0)                           \n"
		"lwc1            $f16,12($s0)                           \n"
		"lui             $at,0x4000                             \n"
		"mtc1            $at,$f4                                \n"
		"sub.s           $f0,$f18,$f16                          \n"
		"addiu           $t1,$zero,255                          \n"
		"or              $a0,$s0,$zero                          \n"
		"abs.s           $f0,$f0                                \n"
		"c.lt.s          $f0,$f4                                \n"
		"nop                                                    \n"
		"bc1fl           .L000058                               \n"
		"lh              $t2,406($s0)                           \n"
		"mtc1            $zero,$f6                              \n"
		"sb              $t1,174($s0)                           \n"
		"jal             func_809E9868                          \n"
		"swc1            $f6,104($s0)                           \n"
		"beq             $zero,$zero,.L000059                   \n"
		"lw              $ra,36($sp)                            \n"
		".L000057:                                              \n"
		"lh              $t2,406($s0)                           \n"
		".L000058:                                              \n"
		"bnel            $t2,$zero,.L000059                     \n"
		"lw              $ra,36($sp)                            \n"
		"jal             func_809E9978                          \n"
		"or              $a0,$s0,$zero                          \n"
		"lw              $ra,36($sp)                            \n"
		".L000059:                                              \n"
		"lw              $s0,32($sp)                            \n"
		"addiu           $sp,$sp,56                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
