void data_809EA0C4(entity_t* en) /* 1 internal, 3 external, 75 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809EA0C4: \n"
	);
	asm(
		"addiu           $sp,$sp,-48                            \n"
		"sw              $s0,24($sp)                            \n"
		"or              $s0,$a0,$zero                          \n"
		"sw              $ra,28($sp)                            \n"
		"addiu           $a0,$a0,332                            \n"
		"sw              $a1,52($sp)                            \n"
		"jal             0x800A49FC                 \n"
		"sw              $a0,36($sp)                            \n"
		"beq             $v0,$zero,.L000039                     \n"
		"lui             $at,0x3F80                             \n"
		"jal             func_809E96FC                          \n"
		"or              $a0,$s0,$zero                          \n"
		"beq             $zero,$zero,.L000040                   \n"
		"lw              $a0,36($sp)                            \n"
		".L000039:                                              \n"
		"mtc1            $at,$f2                                \n"
		"lwc1            $f0,356($s0)                           \n"
		"lui             $at,0x4040                             \n"
		"c.lt.s          $f0,$f2                                \n"
		"nop                                                    \n"
		"bc1fl           .L000041                               \n"
		"mtc1            $at,$f4                                \n"
		"beq             $zero,$zero,.L000042                   \n"
		"mov.s           $f0,$f2                                \n"
		"mtc1            $at,$f4                                \n"
		".L000041:                                              \n"
		"lui             $at,0x4040                             \n"
		"c.lt.s          $f4,$f0                                \n"
		"nop                                                    \n"
		"bc1fl           .L000043                               \n"
		"mov.s           $f2,$f0                                \n"
		"mtc1            $at,$f2                                \n"
		"beq             $zero,$zero,.L000042                   \n"
		"mov.s           $f0,$f2                                \n"
		"mov.s           $f2,$f0                                \n"
		".L000043:                                              \n"
		"mov.s           $f0,$f2                                \n"
		".L000042:                                              \n"
		"lui             $at,0x4040                             \n"
		"mtc1            $at,$f6                                \n"
		"lui             $at,0x4140                             \n"
		"mtc1            $at,$f10                               \n"
		"sub.s           $f8,$f6,$f0                            \n"
		"lui             $at,0x40A0                             \n"
		"mtc1            $at,$f18                               \n"
		"mul.s           $f16,$f8,$f10                          \n"
		"add.s           $f4,$f16,$f18                          \n"
		"trunc.w.s       $f6,$f4                                \n"
		"mfc1            $t7,$f6                                \n"
		"nop                                                    \n"
		"sh              $t7,778($s0)                           \n"
		"lw              $a0,36($sp)                            \n"
		".L000040:                                              \n"
		"jal             0x800A56C8                 \n"
		"lui             $a1,0x4080                             \n"
		"beq             $v0,$zero,.L000044                     \n"
		"addiu           $a0,$s0,36                             \n"
		"lbu             $t8,729($s0)                           \n"
		"andi            $t9,$t8,0xfffe                         \n"
		"sb              $t9,729($s0)                           \n"
		".L000044:                                              \n"
		"lw              $a1,8($s0)                             \n"
		"lui             $a2,0x3F00                             \n"
		"jal             0x8007841C                 \n"
		"lui             $a3,0x4040                             \n"
		"addiu           $a0,$s0,44                             \n"
		"lw              $a1,16($s0)                            \n"
		"lui             $a2,0x3F00                             \n"
		"jal             0x8007841C                 \n"
		"lui             $a3,0x4040                             \n"
		"lw              $ra,28($sp)                            \n"
		"lw              $s0,24($sp)                            \n"
		"addiu           $sp,$sp,48                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
