void data_809E9DFC(entity_t* en) /* 1 internal, 2 external, 36 lines */
{
	asm(
		".set noat        \n"
		".set noreorder   \n"
		".Ldata_809E9DFC: \n"
	);
	asm(
		"addiu           $sp,$sp,-32                            \n"
		"or              $a2,$a0,$zero                          \n"
		"sw              $ra,20($sp)                            \n"
		"addiu           $a0,$a0,332                            \n"
		"sw              $a1,36($sp)                            \n"
		"sw              $a0,28($sp)                            \n"
		"jal             0x800A49FC                 \n"
		"sw              $a2,32($sp)                            \n"
		"lw              $a0,28($sp)                            \n"
		"jal             0x800A56C8                 \n"
		"addiu           $a1,$zero,0                            \n"
		"beq             $v0,$zero,.L000026                     \n"
		"lw              $a2,32($sp)                            \n"
		"lh              $v0,406($a2)                           \n"
		"beq             $v0,$zero,.L000026                     \n"
		"addiu           $t6,$v0,-1                             \n"
		"sh              $t6,406($a2)                           \n"
		".L000026:                                              \n"
		"lui             $at,0x42F0                             \n"
		"mtc1            $at,$f6                                \n"
		"lwc1            $f4,144($a2)                           \n"
		"c.lt.s          $f4,$f6                                \n"
		"nop                                                    \n"
		"bc1t            .L000027                               \n"
		"nop                                                    \n"
		"lh              $t7,406($a2)                           \n"
		"bnel            $t7,$zero,.L000028                     \n"
		"lw              $ra,20($sp)                            \n"
		".L000027:                                              \n"
		"jal             func_809E9868                          \n"
		"or              $a0,$a2,$zero                          \n"
		"lw              $ra,20($sp)                            \n"
		".L000028:                                              \n"
		"addiu           $sp,$sp,32                             \n"
		"jr              $ra                                    \n"
		"nop                                                    \n"
	);
}
